### PR TITLE
Fix sanitizer build in travis ci

### PR DESCRIPTION
**Pull request by cordney**
The `configure.py` parameter is actually `--with-sanitizers`.

### CODE REVIEW

**Comment by webmaster128** [comment]
This should not be possible without an error raised by ./configure.py … Either the check for unused arguments disappeared or the invalid argument `-with-sanitizer` is never used.

**Comment by webmaster128** [comment]
Turns out there is some funny magic going on:

```

ok

**Comment by cordney** [comment]
Indeed, you are correct, it should produce an error. After testing, I find that it also accepts `--with-sanitizer` and enables the sanitizer build correctly. This even applies when using `--with-santize`, `--with-sanitiz` ... `--with-sa`. Only when using with `--with-s` it produces an ambigouity error:

```
configure.py: error: ambiguous option: --with-s (--with-sanitizers, --with-sphinx, --with-sqlite3?)
```

With this behavious `--with-cov` would also enable a coverage build and so on for the other options. Is this expected behaviour?

**Comment by webmaster128** [comment]
Turns out there is some funny magic happening:

```
./configure.py --with-sanitizers
./configure.py --with-sanitizer
./configure.py --with-sanitize
./configure.py --with-sanitiz
./configure.py --with-saniti
./configure.py --with-sanit
./configure.py --with-sani
./configure.py --with-san
./configure.py --with-sa
```
are accepted while

```
./configure.py --with-sanitizersX
./configure.py --with-s
```

are not.

**Comment by webmaster128** [comment]
I'd consider that a dangerous piece of shit. Maybe to support some legary behavior. The thing is that we're using the old optparse module because not too long ago Botan still supported Python 2.6. We could now move to argparse. But I don't know if that is the core of this issue.

**Comment by webmaster128** [comment]
argparse doe the same thing. See also http://stackoverflow.com/questions/33900846/disable-unique-prefix-matches-for-argparse-and-optparse

**Comment by randombit** [comment]
GNU getopt and most other arg parsers also do this, it is quite useful on the command line (eg passing `--no-opt` or `--debug` does what you expect) through our scripts probably should prefer the full option name.

**Comment by cordney** [comment]
Thanks for clarification.

**Pull request merged**
