### PR TITLE
Fix BigInt random_integer() distribution issue

### LINKED ISSUE #108: BigInt::random_integer distribution not uniform
Code:
https://github.com/randombit/botan/blob/master/src/lib/math/bigint/big_rand.cpp#L45

Test:
```cpp
#include <vector>
#include <iostream>
#include <botan/bigint.h>
#include <botan/rng.h>

using namespace Botan;

int main(){
	std::vector<int> bins(10, 0);

	RandomNumberGenerator *rng = RandomNumberGenerator::make_rng();

	for (int i = 0; i < 10000; i++){
		BigInt b = BigInt::random_integer(*rng, 0, bins.size());
		size_t x = b.to_u32bit();
		bins[x]++;
	}

	for (size_t i = 0; i < bins.size(); i++){
		std::cout << i << ": " << bins[i] << std::endl;
	}

	return 0;
}
```

Example output:
```
0: 954
1: 976
2: 1237
3: 1280
4: 945
5: 932
6: 912
7: 897
8: 948
9: 919
```

2 and 3 appear more often than expected. Note that this happens all the time, not just by chance.

Explanation:
http://stackoverflow.com/questions/10984974/why-do-people-say-there-is-modulo-bias-when-using-a-random-number-generator

Also BigInt::randomize does not work as I would have expected it to:

```cpp
#include <vector>
#include <iostream>
#include <botan/bigint.h>
#include <botan/rng.h>

using namespace Botan;

int main(){
	std::vector<int> bins(10, 0);

	RandomNumberGenerator *rng = RandomNumberGenerator::make_rng();

	for (int i = 0; i < 10000; i++){
		BigInt b;
		b.randomize(*rng, 3);
		size_t x = b.to_u32bit();
		bins[x]++;
	}

	for (size_t i = 0; i < bins.size(); i++){
		std::cout << i << ": " << bins[i] << std::endl;
	}

	return 0;
}
```

Output:
```
0: 0
1: 0
2: 0
3: 0
4: 2508
5: 2429
6: 2526
7: 2537
8: 0
9: 0
```

I would have expected it to generate random 3 bit integers, so something in the range [0, 8) but instead it generates numbers in the range [4, 8) and the code is not commented to explain this behaviour.

https://github.com/randombit/botan/blob/master/src/lib/math/bigint/big_rand.cpp#L29

### PR DESCRIPTION
**Pull request by webmaster128**
Fixes #108

### CODE REVIEW

**Comment by 983** [comment]
Looks ok to me. However I can only prove presence of bugs, not their absence.
Though I am wondering what all the other algorithms are using to generate random `BigInt`s if changing the method signature does not break anything.

One small thing:
Maybe you could add a comment to `random_integer` like
```
Generate a random integer that is at least as big as min and strictly less than max
```
to avoid off-by-one errors. It would be even safer to put it in the name of the function but I can't come up with a short one. E.g. `random_integer_exclusive` is quite long and might confuse people to think that `min` is excluded as well.

**Comment by webmaster128** [comment]
* I added a default value in `bigint.h` to preserve the old behavior. When you have `BigInt(rng, 1024)` in the code, this will now be expanded to `BigInt(rng, 1024, true)` at compile time.
* I'll integrate the comment, good idea.
* `strict_upper_bound` is what a mathematician would call it. Given that a user must not type it, it is definitely better than `max`. Since `std::rand()` includes the maximum value, I don't see a convention that max is excluded by default.

**Comment by 983** [comment]
Ah, I see. Very well then.

**Comment by webmaster128** [comment]
Well when you check how `random_integer()` is used in Botan (`git grep -C 3 "random_integer("`) the question arises whether max should be included. See all the `-1`s:

```
src/cmd/factor.cpp-BigInt rho(const BigInt& n, RandomNumberGenerator& rng)
src/cmd/factor.cpp-   {
src/cmd/factor.cpp:   BigInt x = BigInt::random_integer(rng, 0, n-1);
src/cmd/factor.cpp-   BigInt y = x;
src/cmd/factor.cpp-   BigInt d = 0;
--
src/lib/math/numbertheory/numthry.cpp-   for(size_t i = 0; i != test_iterations; ++i)
src/lib/math/numbertheory/numthry.cpp-      {
src/lib/math/numbertheory/numthry.cpp:      const BigInt a = BigInt::random_integer(rng, 2, n_minus_1);
src/lib/math/numbertheory/numthry.cpp-      BigInt y = pow_mod(a);
src/lib/math/numbertheory/numthry.cpp-
--
src/lib/pubkey/dsa/dsa.cpp-
src/lib/pubkey/dsa/dsa.cpp-   if(x == 0)
src/lib/pubkey/dsa/dsa.cpp:      x = BigInt::random_integer(rng, 2, group_q() - 1);
src/lib/pubkey/dsa/dsa.cpp-
src/lib/pubkey/dsa/dsa.cpp-   y = power_mod(group_g(), x, group_p());
--
src/lib/pubkey/ecc_key/ecc_key.cpp-
src/lib/pubkey/ecc_key/ecc_key.cpp-   if(x == 0)
src/lib/pubkey/ecc_key/ecc_key.cpp:      private_key = BigInt::random_integer(rng, 1, domain().get_order());
src/lib/pubkey/ecc_key/ecc_key.cpp-   else
src/lib/pubkey/ecc_key/ecc_key.cpp-      private_key = x;
--
src/lib/pubkey/nr/nr.cpp-
src/lib/pubkey/nr/nr.cpp-   if(x == 0)
src/lib/pubkey/nr/nr.cpp:      x = BigInt::random_integer(rng, 2, group_q() - 1);
src/lib/pubkey/nr/nr.cpp-
src/lib/pubkey/nr/nr.cpp-   y = power_mod(group_g(), x, group_p());
```

**Comment by webmaster128** [comment]
I put the open topic as a follow-up in #222.

**Pull request merged**
