### PR TITLE
Write libbotan-1.11.so* into out_dir and fix 'make clean' on Windows

### PR DESCRIPTION
**Pull request by webmaster128**
When botan is configured with an external build dir (e.g. `./configure.py  --with-build-dir=../build-botan --link-method=hardlink`) than the resulting dynamic libs and symlinks (`libbotan-1.11.so`, `libbotan-1.11.so.16`, `libbotan-1.11.so.16.16`) should be created in the build dir next to `./botan` and `./botan-test`. At the moment these files are created in the working directory, which has to be the botan source directory in order to compile.

### CODE REVIEW

**Comment by webmaster128** [comment]
Writes dynamic libraries into build directory on Unix and Windows now. Additionally I fixed 'make clean' on Windows which did not work because a Linux path separator was used (..\build-botan/botan.exe).

**Comment by webmaster128** [comment]
This is about `/` vs. `\` path separators (see change in ` src/build-data/makefile/header.in`). Can anyone think of a scenario where [os.sep](https://docs.python.org/2/library/os.html#os.sep) differs from the separator needed in the Makefile? What about cross-platform amalgamations or MinGW? cc @randombit @jsonn @cdesjardins

**Comment by jsonn** [comment]
Where does using / fail on Windows? A lot of commands support both separators.

**Comment by webmaster128** [comment]
The [del](https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/del.mspx?mfr=true) command in `make clean` tries to interpret `/` followed by text as a parameter.

**Comment by jsonn** [comment]
os.sep is the native separator, that should work at least for native Windows builds and all builds on Unix (including xcompile to Windows). It might not work for trying to xcompile for Unix from Windows, but you would be using cygwin or the like for that anyway, wouldn't you? As such I think that part is fine.

The DLL part might be better handled in combination with pullup #87.

**Comment by webmaster128** [comment]
@jsonn I don't think our PR interact semantically, because I the only thing I do is to make sure that the library is written to the build directory in an out-of-tree build in the following settings:
* gmake on Unix
* nmake on Windows

This is the setup that is expected to work by now but it is broken.

Your PR goes one step further and introduces a new build setup:
* gmake on Windows

That adds some non-trivial complexity. I'd love to see that happen and I'll be happy to help out where possible but let's take one step at a time.

**Pull request closed without merging**
