### PR TITLE
Add support for ARMv8 SHA1/SHA2 instructions

### PR DESCRIPTION
**Pull request by randombit**
Based almost entirely on @noloader's patches in #840 and #841 

Relies on #843 which is merged yet.

PMULL patch comes in different PR, probably not today.

Requires at least GCC 4.9 for the crypto intrinsics, so this will probably fail CI build. I need to work on something for restricting certain modules based on compiler version, this is also needed for Goldmont SHA-1 which requires GCC 5.0

Tested on qemu+GCC 6.3 and an AMD Opteron 1100. Opteron showed 4-5x speedup.

### CODE REVIEW

**Comment by noloader** [comment]
@randombit,

I'm on the *arm-sha* branch.

***BananaPi***

Configured with `--cc-abi="-march=armv7-a -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard"`. Its a lot of flags, but its correct for the board:

```
bananapi:botan$ cat /proc/cpuinfo
Processor       : ARMv7 Processor rev 4 (v7l)
...
Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
```

This looks ominous: *`sha1_armv8.cpp:20:106: warning: target attribute is not supported on this machine [-Wattributes]`*.

```
bananapi:botan$ gcc --version
gcc (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
...
```
And:
```
g++  -pthread -fstack-protector -march=armv7-a -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -march=armv7 -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -Ibuild/include/external -c ./src/lib/hash/sha2_32/sha2_32.cpp -o build/obj/lib/hash_sha2_32.o
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:20:106: warning: target attribute is not supported on this machine [-Wattributes]
 void SHA_160::sha1_armv8_compress_n(secure_vector<uint32_t>& digest, const uint8_t input[], size_t blocks)
                                                                                                          ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp: In static member function âstatic void Botan::SHA_160::sha1_armv8_compress_n(Botan::secure_vector<unsigned int>&, const uint8_t*, std::size_t)â:
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:59:46: error: âvsha1h_u32â was not declared in this scope
       E1 = vsha1h_u32(vgetq_lane_u32(ABCD, 0));
                                              ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:60:40: error: âvsha1cq_u32â was not declared in this scope
       ABCD = vsha1cq_u32(ABCD, E0, TMP0);
                                        ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:62:44: error: âvsha1su0q_u32â was not declared in this scope
       MSG0 = vsha1su0q_u32(MSG0, MSG1, MSG2);
                                            ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:68:38: error: âvsha1su1q_u32â was not declared in this scope
       MSG0 = vsha1su1q_u32(MSG0, MSG3);
                                      ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:94:40: error: âvsha1pq_u32â was not declared in this scope
       ABCD = vsha1pq_u32(ABCD, E1, TMP1);
                                        ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:129:40: error: âvsha1mq_u32â was not declared in this scope
       ABCD = vsha1mq_u32(ABCD, E0, TMP0);
                                        ^
Makefile:675: recipe for target 'build/obj/lib/hash_sha1_armv8.o' failed
make: *** [build/obj/lib/hash_sha1_armv8.o] Error 1
make: *** Waiting for unfinished jobs....
bananapi:botan$ git branch
* arm-sha
  master
bananapi:botan$
```

-----

***RaspberryPi 3***

[Raspberry Pi 3](https://www.google.com/search?q=Raspberry+Pi+3+site%3A+amazon.com) with the armhf image, even though its an armv8 cpu. I used `--cc=armv7-a` because of [Issue 800](https://github.com/randombit/botan/issues/800).

```
raspberrypi:botan$ ./configure.py --cpu=armv7-a
   INFO: ./configure.py invoked with options "--cpu=armv7-a"
   INFO: Platform: OS="Linux" machine="armv7l" proc=""
   INFO: Guessing target OS is linux (use --os to set)
   INFO: Guessing to use compiler gcc (use --cc to set)
   INFO: Canonicalizized CPU target armv7-a to arm32/armv7-a
   INFO: Target is gcc-linux-arm32-armv7-a
   INFO: Skipping, dependency failure - certstor_sqlite3 rdrand sessions_sqlite3
   INFO: Skipping, incompatible CPU - aes_ni aes_ssse3 chacha_sse2 clmul idea_sse2 rdrand_rng rdseed sha1_sse2 threefish_avx2
   INFO: Skipping, incompatible OS - cryptoapi_rng darwin_secrandom win32_stats
   INFO: Skipping, no enabled compression schemes - compression
   INFO: Skipping, requires external dependency - boost bzip2 lzma openssl sqlite3 tpm zlib
   INFO: Loading modules adler32 aead aes aont asn1 auto_rng base base64 bcrypt bigint blake2 block blowfish camellia cascade cast cbc cbc_mac ccm cecpq1 certstor_sql cfb chacha chacha20poly1305 cmac codec_filt comb4p crc24 crc32 cryptobox ctr curve25519 des dev_random dh dl_algo dl_group dlies dsa dyn_load eax ec_gfp ec_group ecc_key ecdh ecdsa ecgdsa ecies eckcdsa elgamal eme_oaep eme_pkcs1 eme_raw emsa1 emsa_pkcs1 emsa_pssr emsa_raw emsa_x931 entropy fd_unix ffi filters fpe_fe1 gcm gmac gost_28147 gost_3410 gost_3411 hash hash_id hex hkdf hmac hmac_drbg http_util idea iso9796 kasumi kdf kdf1 kdf1_iso18033 kdf2 keccak keypair lion locking_allocator mac mce mceies md4 md5 mdx_hash mgf1 misty1 mode_pad modes mp newhope noekeon noekeon_simd numbertheory ocb ofb par_hash passhash9 pbes2 pbkdf pbkdf1 pbkdf2 pem pk_pad pkcs11 poly1305 prf_tls prf_x942 proc_walk pubkey rc4 rfc3394 rfc6979 rmd160 rng rsa salsa20 seed serpent serpent_simd sessions_sql sha1 sha1_armv8 sha2_32 sha2_32_armv8 sha2_64 sha3 shake shake_cipher simd siphash siv skein sp800_108 sp800_56c srp6 stateful_rng stream system_rng threefish tiger tls tls_cbc tss twofish utils whirlpool x509 x919_mac xmss xtea xts
   INFO: Assuming CPU is little endian
   INFO: Using symlink to link files into build dir (use --link-method to change)
   INFO: Botan 2.0.1 (VC git:a7f0c84a031ca59c01819b62b61274dffb0dc2c6) (unreleased undated) build setup is complete
raspberrypi:botan$ make -j 2
...
mraspberrypi:botan$ make
g++  -pthread -fstack-protector -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -march=armv7-a -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -Ibuild/include/external -c ./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp -o build/obj/lib/hash_sha1_armv8.o
In file included from ./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:11:0:
/usr/lib/gcc/arm-linux-gnueabihf/4.9/include/arm_neon.h:31:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
 #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
  ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:20:106: warning: target attribute is not supported on this machine [-Wattributes]
 void SHA_160::sha1_armv8_compress_n(secure_vector<uint32_t>& digest, const uint8_t input[], size_t blocks)
                                                                                                          ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp: In static member function âstatic void Botan::SHA_160::sha1_armv8_compress_n(Botan::secure_vector<unsigned int>&, const uint8_t*, std::size_t)â:
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:22:4: error: âuint32x4_tâ was not declared in this scope
    uint32x4_t C0, C1, C2, C3;
    ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:23:15: error: expected â;â before âABCDâ
    uint32x4_t ABCD, ABCD_SAVED;
               ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:27:4: error: âC0â was not declared in this scope
    C0 = vdupq_n_u32(0x5A827999);
    ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:27:31: error: âvdupq_n_u32â was not declared in this scope
    C0 = vdupq_n_u32(0x5A827999);
                               ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:28:4: error: âC1â was not declared in this scope
    C1 = vdupq_n_u32(0x6ED9EBA1);
    ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:29:4: error: âC2â was not declared in this scope
    C2 = vdupq_n_u32(0x8F1BBCDC);
    ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:30:4: error: âC3â was not declared in this scope
    C3 = vdupq_n_u32(0xCA62C1D6);
    ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:32:4: error: âABCDâ was not declared in this scope
    ABCD = vld1q_u32(&digest[0]);
    ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:32:31: error: âvld1q_u32â was not declared in this scope
    ABCD = vld1q_u32(&digest[0]);
                               ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:37:18: error: expected â;â before âMSG0â
       uint32x4_t MSG0, MSG1, MSG2, MSG3;
                  ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:38:18: error: expected â;â before âTMP0â
       uint32x4_t TMP0, TMP1;
                  ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:41:7: error: âABCD_SAVEDâ was not declared in this scope
       ABCD_SAVED = ABCD;
       ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:45:7: error: âMSG0â was not declared in this scope
       MSG0 = vld1q_u32((const uint32_t*)(const void*)(input +  0));
       ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:46:7: error: âMSG1â was not declared in this scope
       MSG1 = vld1q_u32((const uint32_t*)(const void*)(input + 16));
       ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:47:7: error: âMSG2â was not declared in this scope
       MSG2 = vld1q_u32((const uint32_t*)(const void*)(input + 32));
       ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:48:7: error: âMSG3â was not declared in this scope
       MSG3 = vld1q_u32((const uint32_t*)(const void*)(input + 48));
       ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:50:71: error: âvreinterpretq_u8_u32â was not declared in this scope
       MSG0 = vreinterpretq_u32_u8(vrev32q_u8(vreinterpretq_u8_u32(MSG0)));
                                                                       ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:50:72: error: âvrev32q_u8â was not declared in this scope
       MSG0 = vreinterpretq_u32_u8(vrev32q_u8(vreinterpretq_u8_u32(MSG0)));
                                                                        ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:50:73: error: âvreinterpretq_u32_u8â was not declared in this scope
       MSG0 = vreinterpretq_u32_u8(vrev32q_u8(vreinterpretq_u8_u32(MSG0)));
                                                                         ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:55:7: error: âTMP0â was not declared in this scope
       TMP0 = vaddq_u32(MSG0, C0);
       ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:55:32: error: âvaddq_u32â was not declared in this scope
       TMP0 = vaddq_u32(MSG0, C0);
                                ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:56:7: error: âTMP1â was not declared in this scope
       TMP1 = vaddq_u32(MSG1, C0);
       ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:59:45: error: âvgetq_lane_u32â was not declared in this scope
       E1 = vsha1h_u32(vgetq_lane_u32(ABCD, 0));
                                             ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:59:46: error: âvsha1h_u32â was not declared in this scope
       E1 = vsha1h_u32(vgetq_lane_u32(ABCD, 0));
                                              ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:60:40: error: âvsha1cq_u32â was not declared in this scope
       ABCD = vsha1cq_u32(ABCD, E0, TMP0);
                                        ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:62:44: error: âvsha1su0q_u32â was not declared in this scope
       MSG0 = vsha1su0q_u32(MSG0, MSG1, MSG2);
                                            ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:68:38: error: âvsha1su1q_u32â was not declared in this scope
       MSG0 = vsha1su1q_u32(MSG0, MSG3);
                                      ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:94:40: error: âvsha1pq_u32â was not declared in this scope
       ABCD = vsha1pq_u32(ABCD, E1, TMP1);
                                        ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:129:40: error: âvsha1mq_u32â was not declared in this scope
       ABCD = vsha1mq_u32(ABCD, E0, TMP0);
                                        ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:199:30: error: âvst1q_u32â was not declared in this scope
    vst1q_u32(&digest[0], ABCD);
                              ^
Makefile:675: recipe for target 'build/obj/lib/hash_sha1_armv8.o' failed
make: *** [build/obj/lib/hash_sha1_armv8.o] Error 1
raspberrypi:botan$
```

Reconfigur'ing with `$ ./configure.py --cpu=armv7-a --cc-abi="-mfloat-abi=hard -mfpu=neon"` results in fewer errors because the types are available. But the SHA related symbols are still missing:

```
g++  -pthread -fstack-protector -mfloat-abi=hard -mfpu=neon -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -march=armv7-a -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -Ibuild/include/external -c ./src/lib/hash/sha2_32/sha2_32.cpp -o build/obj/lib/hash_sha2_32.o
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:20:106: warning: target attribute is not supported on this machine [-Wattributes]
 void SHA_160::sha1_armv8_compress_n(secure_vector<uint32_t>& digest, const uint8_t input[], size_t blocks)
                                                                                                          ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp: In static member function âstatic void Botan::SHA_160::sha1_armv8_compress_n(Botan::secure_vector<unsigned int>&, const uint8_t*, std::size_t)â:
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:59:46: error: âvsha1h_u32â was not declared in this scope
       E1 = vsha1h_u32(vgetq_lane_u32(ABCD, 0));
                                              ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:60:40: error: âvsha1cq_u32â was not declared in this scope
       ABCD = vsha1cq_u32(ABCD, E0, TMP0);
                                        ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:62:44: error: âvsha1su0q_u32â was not declared in this scope
       MSG0 = vsha1su0q_u32(MSG0, MSG1, MSG2);
                                            ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:68:38: error: âvsha1su1q_u32â was not declared in this scope
       MSG0 = vsha1su1q_u32(MSG0, MSG3);
                                      ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:94:40: error: âvsha1pq_u32â was not declared in this scope
       ABCD = vsha1pq_u32(ABCD, E1, TMP1);
                                        ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:129:40: error: âvsha1mq_u32â was not declared in this scope
       ABCD = vsha1mq_u32(ABCD, E0, TMP0);
                                        ^
Makefile:675: recipe for target 'build/obj/lib/hash_sha1_armv8.o' failed
make: *** [build/obj/lib/hash_sha1_armv8.o] Error 1
make: *** Waiting for unfinished jobs....
```

-----

Here's a real bastardization of things since the kernel is `armhf`, and not `aarch32`. I think it messes with procedural calling conventions badly because it results in crashes.

```
raspberrypi:botan$ ./configure.py --cpu=arm32 --cc-abi="-march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard"
   INFO: ./configure.py invoked with options "--cpu=arm32 --cc-abi=-march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard"
   INFO: Platform: OS="Linux" machine="armv7l" proc=""
   INFO: Guessing target OS is linux (use --os to set)
   INFO: Guessing to use compiler gcc (use --cc to set)
   INFO: Canonicalizized CPU target arm32 to arm32/arm32
...
raspberrypi:botan$ make -j 2
...
g++  -pthread -fstack-protector -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -Ibuild/include/external -c ./src/lib/hash/sha2_32/sha2_32.cpp -o build/obj/lib/hash_sha2_32.o
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:20:106: warning: target attribute is not supported on this machine [-Wattributes]
 void SHA_160::sha1_armv8_compress_n(secure_vector<uint32_t>& digest, const uint8_t input[], size_t blocks)
                                                                                                          ^
g++  -pthread -fstack-protector -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -Ibuild/include/external -c ./src/lib/hash/sha2_32/sha2_32_armv8/sha2_32_armv8.cpp -o build/obj/lib/hash_sha2_32_sha2_32_armv8.o
./src/lib/hash/sha2_32/sha2_32_armv8/sha2_32_armv8.cpp:20:106: warning: target attribute is not supported on this machine [-Wattributes]
 void SHA_256::compress_digest_armv8(secure_vector<uint32_t>& digest, const uint8_t input[], size_t blocks)
                                                                                                          ^
...
```

**Comment by randombit** [comment]
> This looks ominous: sha1_armv8.cpp:20:106: warning: target attribute is not supported on this machine [-Wattributes].

Not a problem. The GCC attribute is used to allow single file amalgamation without additional feature flags on the command line. If the version of GCC used doesn't support the attribute, no problem occurs unless the build was configured with `--single-amalgamation-file` *and* the user is not setting the appropriate options to enable whatever ISA extensions were used when building `botan_all.cpp`.

**Comment by noloader** [comment]
@randombit,

Based on testing results from [PR #1005](https://github.com/randombit/botan/pull/1005), things work as expected on ARMv7, ARMv7a and ARMv8 (about 6 ARM gadgets in total). The CPU detection code did not cause any problems, and SHA ran successfully. I did not benchmark SHA, however. I'll make another pass and see if the SHA benchmarks pass the sniff test.

**Comment by noloader** [comment]
@randombit,

I may have spoke too soon. I jumped on LeMaker HiKey (ARMv8a) and `arm-sha` branch. I encountered the issues below.

My question is, is `arm-sha` a valid branch? If not, then which branch should we test on? Is Master the branch now?

-----

```
g++ -fstack-protector -pthread -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -Ibuild/include/external -c ./src/lib/hash/sha2_32/sha2_32.cpp -o build/obj/lib/hash_sha2_32.o
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:20:107: warning: target attribute is not supported on this machine [-Wattributes]
 void SHA_160::sha1_armv8_compress_n(secure_vector<uint32_t>& digest, const uint8_t input8[], size_t blocks)
                                                                                                           ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp: In static member function ‘static void Botan::SHA_160::sha1_armv8_compress_n(Botan::secure_vector<unsigned int>&, const uint8_t*, std::size_t)’:
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:61:46: error: ‘vsha1h_u32’ was not declared in this scope
       E1 = vsha1h_u32(vgetq_lane_u32(ABCD, 0));
                                              ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:62:40: error: ‘vsha1cq_u32’ was not declared in this scope
       ABCD = vsha1cq_u32(ABCD, E0, TMP0);
                                        ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:64:44: error: ‘vsha1su0q_u32’ was not declared in this scope
       MSG0 = vsha1su0q_u32(MSG0, MSG1, MSG2);
                                            ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:70:38: error: ‘vsha1su1q_u32’ was not declared in this scope
       MSG0 = vsha1su1q_u32(MSG0, MSG3);
                                      ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:96:40: error: ‘vsha1pq_u32’ was not declared in this scope
       ABCD = vsha1pq_u32(ABCD, E1, TMP1);
                                        ^
./src/lib/hash/sha1/sha1_armv8/sha1_armv8.cpp:131:40: error: ‘vsha1mq_u32’ was not declared in this scope
       ABCD = vsha1mq_u32(ABCD, E0, TMP0);
                                        ^
g++ -fstack-protector -pthread -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -Ibuild/include/external -c ./src/lib/hash/sha2_32/sha2_32_armv8/sha2_32_armv8.cpp -o build/obj/lib/hash_sha2_32_sha2_32_armv8.o
Makefile:680: recipe for target 'build/obj/lib/hash_sha1_armv8.o' failed
make: *** [build/obj/lib/hash_sha1_armv8.o] Error 1
make: *** Waiting for unfinished jobs....
./src/lib/hash/sha2_32/sha2_32_armv8/sha2_32_armv8.cpp:20:107: warning: target attribute is not supported on this machine [-Wattributes]
 void SHA_256::compress_digest_armv8(secure_vector<uint32_t>& digest, const uint8_t input8[], size_t blocks)
                                                                                                           ^
./src/lib/hash/sha2_32/sha2_32_armv8/sha2_32_armv8.cpp: In static member function ‘static void Botan::SHA_256::compress_digest_armv8(Botan::secure_vector<unsigned int>&, const uint8_t*, std::size_t)’:
./src/lib/hash/sha2_32/sha2_32_armv8/sha2_32_armv8.cpp:71:40: error: ‘vsha256su0q_u32’ was not declared in this scope
       MSG0 = vsha256su0q_u32(MSG0, MSG1);
                                        ^
./src/lib/hash/sha2_32/sha2_32_armv8/sha2_32_armv8.cpp:74:50: error: ‘vsha256hq_u32’ was not declared in this scope
       STATE0 = vsha256hq_u32(STATE0, STATE1, TMP0);
                                                  ^
./src/lib/hash/sha2_32/sha2_32_armv8/sha2_32_armv8.cpp:75:49: error: ‘vsha256h2q_u32’ was not declared in this scope
       STATE1 = vsha256h2q_u32(STATE1, TMP2, TMP0);
                                                 ^
./src/lib/hash/sha2_32/sha2_32_armv8/sha2_32_armv8.cpp:76:46: error: ‘vsha256su1q_u32’ was not declared in this scope
       MSG0 = vsha256su1q_u32(MSG0, MSG2, MSG3);
                                              ^
Makefile:686: recipe for target 'build/obj/lib/hash_sha2_32_sha2_32_armv8.o' failed
make: *** [build/obj/lib/hash_sha2_32_sha2_32_armv8.o] Error 1
```

-----

For completeness, here's the configure.

```
hikey:botan$ ./configure.py
   INFO: ./configure.py invoked with options ""
   INFO: Platform: OS="Linux" machine="aarch64" proc=""
   INFO: Guessing target OS is linux (use --os to set)
   INFO: Guessing to use compiler gcc (use --cc to set)
   INFO: Detected CPU model "AArch64 Processor rev 3 (aarch64)" in /proc/cpuinfo
   INFO: Guessing target processor is a arm64/arm64 (use --cpu to set)
   INFO: Target is gcc-linux-arm64-arm64
   INFO: Skipping (dependency failure): certstor_sqlite3 rdrand sessions_sqlite3
   INFO: Skipping (incompatible CPU): aes_ni aes_ssse3 chacha_sse2 clmul idea_sse2 rdrand_rng rdseed sha1_sse2 threefish_avx2
   INFO: Skipping (incompatible OS): cryptoapi_rng darwin_secrandom getentropy win32_stats
   INFO: Skipping (no enabled compression schemes): compression
   INFO: Skipping (requires external dependency): boost bzip2 lzma openssl sqlite3 tpm zlib
   INFO: Loading modules: adler32 aead aes aont asn1 auto_rng base base64 bcrypt bigint blake2 block blowfish camellia cascade cast cbc cbc_mac ccm cecpq1 certstor_sql cfb chacha chacha20poly1305 cmac codec_filt comb4p crc24 crc32 cryptobox ctr curve25519 des dev_random dh dl_algo dl_group dlies dsa dyn_load eax ec_gfp ec_group ecc_key ecdh ecdsa ecgdsa ecies eckcdsa elgamal eme_oaep eme_pkcs1 eme_raw emsa1 emsa_pkcs1 emsa_pssr emsa_raw emsa_x931 entropy fd_unix ffi filters fpe_fe1 gcm gmac gost_28147 gost_3410 gost_3411 hash hash_id hex hkdf hmac hmac_drbg http_util idea iso9796 kasumi kdf kdf1 kdf1_iso18033 kdf2 keccak keypair lion locking_allocator mac mce mceies md4 md5 mdx_hash mgf1 misty1 mode_pad modes mp newhope noekeon noekeon_simd numbertheory ocb ofb par_hash passhash9 pbes2 pbkdf pbkdf1 pbkdf2 pem pk_pad pkcs11 poly1305 prf_tls prf_x942 proc_walk pubkey rc4 rfc3394 rfc6979 rmd160 rng rsa salsa20 seed serpent serpent_simd sessions_sql sha1 sha1_armv8 sha2_32 sha2_32_armv8 sha2_64 sha3 shake shake_cipher simd siphash siv skein sm3 sp800_108 sp800_56c srp6 stateful_rng stream system_rng threefish tiger tls tls_cbc tss twofish utils whirlpool x509 x919_mac xmss xtea xts
   INFO: Assuming CPU is little endian
   INFO: Using symlink to link files into build dir (use --link-method to change)
   INFO: Botan 2.2.0 (VC git:068a495ec3a133eb4a3304ae1cd8a6c63a0c1c1c) (unreleased undated) build setup is complete
```

**Comment by randombit** [comment]
Should be ready to go with #1052 waiting on CI

**Pull request merged**
