### PR TITLE
Refactoring to support Windows Phone

### LINKED ISSUE #794: MSVC, Windows Phone and "error C2039: 'CryptAcquireContext': is not a member of global namespace"
I'm working with [Visual C++ 2015 Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools). Once installed, open an x86 ARM Cross build tools prompt.

```
c:\botan-src>.\configure.py --cc=msvc --cpu=armv7a --cc-abi="/FI sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP"
...
c:\botan-src>nmake
...
cl  /MD /bigobj /FI sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /O2 /W4 /wd4250 /wd4251 /wd4275 /Ibuild\include /nologo /c C:\botan-src\src\lib\entropy\cryptoapi_rng\es_capi.cpp /Fobuild\obj\lib\entropy_cryptoapi_rng_es_capi.obj
es_capi.cpp
C:\botan-src\src\lib\entropy\cryptoapi_rng\es_capi.cpp(23): error C2039: 'CryptAcquireContext': is not a member of '`global namespace''
C:\botan-src\src\lib\entropy\cryptoapi_rng\es_capi.cpp(23): error C3861: 'CryptAcquireContext': identifier not found
C:\botan-src\src\lib\entropy\cryptoapi_rng\es_capi.cpp(38): error C2039: 'CryptGenRandom': is not a member of '`global namespace''
C:\botan-src\src\lib\entropy\cryptoapi_rng\es_capi.cpp(38): error C3861: 'CryptGenRandom': identifier not found
```

It looks like `system_rng.cpp` has the same issue:

```
cl  /MD /bigobj /FI sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /O2 /W4 /wd4250 /wd4251 /wd4275 /Ibuild\include /nologo /c C:\botan-src\src\lib\rng\system_rng\system_rng.cpp /Fobuild\obj\lib\rng_system_rng.obj
system_rng.cpp
C:\botan-src\src\lib\rng\system_rng\system_rng.cpp(67): error C3861: 'CryptAcquireContext': identifier not found
C:\botan-src\src\lib\rng\system_rng\system_rng.cpp(118): error C2039: 'CryptGenRandom': is not a member of '`global namespace''
C:\botan-src\src\lib\rng\system_rng\system_rng.cpp(118): error C3861: 'CryptGenRandom': identifier not found
C:\botan-src\src\lib\rng\system_rng\system_rng.cpp(158): error C2039: 'CryptGenRandom': is not a member of '`global namespace''
C:\botan-src\src\lib\rng\system_rng\system_rng.cpp(158): error C3861: 'CryptGenRandom': identifier not found
```

### PR DESCRIPTION
**Pull request by randombit**
Long description in the commit message.

@noloader If you have a chance can you test this for the phone target? I think this will resolve #794 and #796. But I have no way to compile it, so there may be some silly problem.

@securitykernel @neusdan Seem ok to you to remove the CryptoAPI entropy source? The only thing lost is that we can no longer poll multiple providers, but as actually instantiated it only ever used `RSA_FULL` anyway. Just want to make sure I'm not missing something important re Windows entropy seeding.

### CODE REVIEW

**Comment by noloader** [comment]
@randombit,

Ack. Below is the configure.

There's a small issue under Visual Studio 2015. The command prompt is `VS2015 x86 ARM cross tool`.

```
nmake
...
        cl /MD /bigobj /FI sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAPI
_FAMILY_PHONE_APP /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /O2 /Oi /W4 /wd4250
 /wd4251 /wd4275 /Ibuild\include /Ibuild\include\external /nologo /c C:\Users\Je
ff\Desktop\botan\src\lib\block\aes\aes.cpp /Fobuild\obj\lib\block_aes.obj
aes.cpp
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(175): error C3861: 'vaeseq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(176): error C3861: 'vaesmc
q_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(177): error C3861: 'vaeseq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(178): error C3861: 'vaesmc
q_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(179): error C3861: 'vaeseq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(180): error C3861: 'vaesmc
q_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(181): error C3861: 'vaeseq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(182): error C3861: 'vaesmc
q_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(183): error C3861: 'vaeseq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(184): error C3861: 'vaesmc
q_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(185): error C3861: 'vaeseq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(186): error C3861: 'vaesmc
q_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(187): error C3861: 'vaeseq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(188): error C3861: 'vaesmc
q_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(189): error C3861: 'vaeseq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(190): error C3861: 'vaesmc
q_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(191): error C3861: 'vaeseq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(192): error C3861: 'vaesmc
q_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(198): error C3861: 'vaeseq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(200): error C3861: 'vaesmc
q_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(204): error C3861: 'vaeseq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(232): error C3861: 'vaesdq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(233): error C3861: 'vaesim
cq_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(234): error C3861: 'vaesdq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(235): error C3861: 'vaesim
cq_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(236): error C3861: 'vaesdq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(237): error C3861: 'vaesim
cq_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(238): error C3861: 'vaesdq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(239): error C3861: 'vaesim
cq_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(240): error C3861: 'vaesdq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(241): error C3861: 'vaesim
cq_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(242): error C3861: 'vaesdq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(243): error C3861: 'vaesim
cq_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(244): error C3861: 'vaesdq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(245): error C3861: 'vaesim
cq_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(246): error C3861: 'vaesdq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(247): error C3861: 'vaesim
cq_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(248): error C3861: 'vaesdq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(249): error C3861: 'vaesim
cq_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(255): error C3861: 'vaesdq
_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(257): error C3861: 'vaesim
cq_u8': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\block\aes\aes.cpp(261): error C3861: 'vaesdq
_u8': identifier not found
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\x86_ARM\cl.EXE"' : return code '0x2'
Stop.
```

I believe Visual Studio 2017 is needed for AES and SHA gear. That's `_MSC_VER >= 1910`. 

I know other libraries are primed for ARM Crypto at `_MSC_VER >= 1910`. But no one has never tested it because Microsoft has their packages or installers so fouled up. They claim to install the arm64 gear (you can even check the box), but there's nothing there when we go to find it. 

----

```
c:\Users\Jeff\Desktop\botan>.\configure.py --cc=msvc --cpu=armv7a --cc-abi="/FI
sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP"
   INFO: C:\Users\Jeff\Desktop\botan\configure.py invoked with options "--cc=msv
c --cpu=armv7a --cc-abi=/FI sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAP
I_FAMILY_PHONE_APP"
   INFO: Platform: OS="Windows" machine="AMD64" proc="Intel64 Family 6 Model 58
Stepping 9, GenuineIntel"
   INFO: Guessing target OS is windows (use --os to set)
   INFO: Canonicalizized CPU target armv7a to arm32/armv7
   INFO: Target is msvc-windows-arm32-armv7
   INFO: Skipping (dependency failure): certstor_sqlite3 rdrand sessions_sqlite3

   INFO: Skipping (incompatible CPU): aes_ni aes_ssse3 chacha_sse2 clmul idea_ss
e2 rdrand_rng rdseed sha1_sse2
   INFO: Skipping (incompatible OS): darwin_secrandom dev_random fd_unix getentr
opy proc_walk
   INFO: Skipping (incompatible compiler): threefish_avx2
   INFO: Skipping (no enabled compression schemes): compression
   INFO: Skipping (requires external dependency): boost bzip2 lzma openssl sqlit
e3 tpm zlib
   INFO: Loading modules: adler32 aead aes aont aria asn1 auto_rng base base64 b
crypt bigint blake2 block blowfish camellia cascade cast cbc cbc_mac ccm cecpq1
certstor_sql cfb chacha chacha20poly1305 cmac codec_filt comb4p crc24 crc32 cryp
toapi_rng cryptobox ctr curve25519 des dh dl_algo dl_group dlies dsa dyn_load ea
x ec_gfp ec_group ecc_key ecdh ecdsa ecgdsa ecies eckcdsa elgamal eme_oaep eme_p
kcs1 eme_raw emsa1 emsa_pkcs1 emsa_pssr emsa_raw emsa_x931 entropy ffi filters f
pe_fe1 gcm gmac gost_28147 gost_3410 gost_3411 hash hash_id hex hkdf hmac hmac_d
rbg http_util idea iso9796 kasumi kdf kdf1 kdf1_iso18033 kdf2 keccak keypair lio
n locking_allocator mac mce mceies md4 md5 mdx_hash mgf1 misty1 mode_pad modes m
p newhope noekeon noekeon_simd numbertheory ocb ofb par_hash passhash9 pbes2 pbk
df pbkdf1 pbkdf2 pem pk_pad pkcs11 poly1305 prf_tls prf_x942 pubkey rc4 rfc3394
rfc6979 rmd160 rng rsa salsa20 seed serpent serpent_simd sessions_sql sha1 sha2_
32 sha2_64 sha3 shake shake_cipher simd siphash siv skein sm3 sp800_108 sp800_56
c srp6 stateful_rng stream system_rng threefish tiger tls tls_cbc tss twofish ut
ils whirlpool win32_stats x509 x919_mac xmss xtea xts
WARNING: Unknown arch in innosetup_arch arm32
WARNING: Disabling support for neon intrinsics due to missing flag for compiler
   INFO: Assuming CPU is little endian
   INFO: Using copy to link files into build dir (use --link-method to change)
   INFO: Botan 2.2.0 (VC unknown) (unreleased undated) build setup is complete
```

**Comment by randombit** [comment]
@noloader That error is with your AES patch which presumably is applied locally, not much this PR can do about that :) Good to know that doesn't exist in VC2015 though.

**Comment by neusdan** [comment]
We do not use the entropy source, just the system rng directly. I think it's ok to remove it.

**Comment by noloader** [comment]
I think we are getting closer. I'm on the `windows-phone` branch; configure shown below. AES and SHA are cleared. I'm seeing:

```
        cl /MD /bigobj /FI sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAPI
_FAMILY_PHONE_APP /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /O2 /Oi /W4 /wd4250
 /wd4251 /wd4275 /Ibuild\include /Ibuild\include\external /nologo /c C:\Users\Je
ff\Desktop\botan\src\lib\entropy\cryptoapi_rng\es_capi.cpp /Fobuild\obj\lib\entr
opy_cryptoapi_rng_es_capi.obj
es_capi.cpp
C:\Users\Jeff\Desktop\botan\src\lib\entropy\cryptoapi_rng\es_capi.cpp(23): error
 C2039: 'CryptAcquireContext': is not a member of '`global namespace''
C:\Users\Jeff\Desktop\botan\src\lib\entropy\cryptoapi_rng\es_capi.cpp(23): error
 C3861: 'CryptAcquireContext': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\entropy\cryptoapi_rng\es_capi.cpp(38): error
 C2039: 'CryptGenRandom': is not a member of '`global namespace''
C:\Users\Jeff\Desktop\botan\src\lib\entropy\cryptoapi_rng\es_capi.cpp(38): error
 C3861: 'CryptGenRandom': identifier not found
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\x86_ARM\cl.EXE"' : return code '0x2'
Stop.
```

-----

```

c:\Users\Jeff\Desktop\botan> .\configure.py --cc=msvc --cpu=armv7a --cc-abi="/FI
 sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP"
   INFO: C:\Users\Jeff\Desktop\botan\configure.py invoked with options "--cc=msv
c --cpu=armv7a --cc-abi=/FI sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAP
I_FAMILY_PHONE_APP"
   INFO: Platform: OS="Windows" machine="AMD64" proc="Intel64 Family 6 Model 58
Stepping 9, GenuineIntel"
   INFO: Guessing target OS is windows (use --os to set)
   INFO: Canonicalizized CPU target armv7a to arm32/armv7
   INFO: Target is msvc-windows-arm32-armv7
   INFO: Skipping (dependency failure): certstor_sqlite3 rdrand sessions_sqlite3

   INFO: Skipping (incompatible CPU): aes_ni aes_ssse3 chacha_sse2 clmul idea_ss
e2 rdrand_rng rdseed sha1_sse2
   INFO: Skipping (incompatible OS): darwin_secrandom dev_random fd_unix getentr
opy proc_walk
   INFO: Skipping (incompatible compiler): threefish_avx2
   INFO: Skipping (no enabled compression schemes): compression
   INFO: Skipping (requires external dependency): boost bzip2 lzma openssl sqlit
e3 tpm zlib
   INFO: Loading modules: adler32 aead aes aont aria asn1 auto_rng base base64 b
crypt bigint blake2 block blowfish camellia cascade cast cbc cbc_mac ccm cecpq1
certstor_sql cfb chacha chacha20poly1305 cmac codec_filt comb4p crc24 crc32 cryp
toapi_rng cryptobox ctr curve25519 des dh dl_algo dl_group dlies dsa dyn_load ea
x ec_gfp ec_group ecc_key ecdh ecdsa ecgdsa ecies eckcdsa elgamal eme_oaep eme_p
kcs1 eme_raw emsa1 emsa_pkcs1 emsa_pssr emsa_raw emsa_x931 entropy ffi filters f
pe_fe1 gcm gmac gost_28147 gost_3410 gost_3411 hash hash_id hex hkdf hmac hmac_d
rbg http_util idea iso9796 kasumi kdf kdf1 kdf1_iso18033 kdf2 keccak keypair lio
n locking_allocator mac mce mceies md4 md5 mdx_hash mgf1 misty1 mode_pad modes m
p newhope noekeon noekeon_simd numbertheory ocb ofb par_hash passhash9 pbes2 pbk
df pbkdf1 pbkdf2 pem pk_pad pkcs11 poly1305 prf_tls prf_x942 pubkey rc4 rfc3394
rfc6979 rmd160 rng rsa salsa20 seed serpent serpent_simd sessions_sql sha1 sha2_
32 sha2_64 sha3 shake shake_cipher simd siphash siv skein sm3 sp800_108 sp800_56
c srp6 stateful_rng stream system_rng threefish tiger tls tls_cbc tss twofish ut
ils whirlpool win32_stats x509 x919_mac xmss xtea xts
WARNING: Unknown arch in innosetup_arch arm32
WARNING: Disabling support for neon intrinsics due to missing flag for compiler
   INFO: Assuming CPU is little endian
   INFO: Using copy to link files into build dir (use --link-method to change)
   INFO: Botan 2.2.0 (VC unknown) (unreleased undated) build setup is complete
```

**Comment by noloader** [comment]
@randombit,

I deleted the former repo and re-cloned. For some reason Git was not pulling your upstream. Man that tool needs help.

Configured with `.\configure.py --cc=msvc --cpu=armv7a --cc-abi="/FI sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP"`.

Almost tested good under Visual Studio 2015 ARM Build Tools. Building with `nmake /k` (continue on error) shows you are almost there. It looks like the issue reported by @neusdan.

```
        cl /MD /bigobj /FI sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAPI
_FAMILY_PHONE_APP /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /O2 /Oi /W4 /wd4250
 /wd4251 /wd4275 /Ibuild\include /Ibuild\include\external /nologo /c C:\Users\Je
ff\Desktop\botan\src\lib\entropy\win32_stats\es_win32.cpp /Fobuild\obj\lib\entro
py_win32_stats_es_win32.obj
es_win32.cpp
C:\Users\Jeff\Desktop\botan\src\lib\entropy\win32_stats\es_win32.cpp(25): error
C2039: 'GetTickCount': is not a member of '`global namespace''
C:\Users\Jeff\Desktop\botan\src\lib\entropy\win32_stats\es_win32.cpp(25): error
C3861: 'GetTickCount': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\entropy\win32_stats\es_win32.cpp(26): error
C2039: 'GetMessagePos': is not a member of '`global namespace''
C:\Users\Jeff\Desktop\botan\src\lib\entropy\win32_stats\es_win32.cpp(26): error
C3861: 'GetMessagePos': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\entropy\win32_stats\es_win32.cpp(27): error
C2039: 'GetMessageTime': is not a member of '`global namespace''
C:\Users\Jeff\Desktop\botan\src\lib\entropy\win32_stats\es_win32.cpp(27): error
C3861: 'GetMessageTime': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\entropy\win32_stats\es_win32.cpp(28): error
C2039: 'GetInputState': is not a member of '`global namespace''
C:\Users\Jeff\Desktop\botan\src\lib\entropy\win32_stats\es_win32.cpp(28): error
C3861: 'GetInputState': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\entropy\win32_stats\es_win32.cpp(42): error
C2039: 'GetCursorPos': is not a member of '`global namespace''
...
NMAKE : warning U4010: 'build\obj\lib\entropy_win32_stats_es_win32.objj' : buil
d failed; /K specified, continuing ...
```

And:

```
        cl /MD /bigobj /FI sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAPI
_FAMILY_PHONE_APP /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /O2 /Oi /W4 /wd4250
 /wd4251 /wd4275 /Ibuild\include /Ibuild\include\external /nologo /c C:\Users\Je
ff\Desktop\botan\src\lib\rng\system_rng\system_rng.cpp /Fobuild\obj\lib\rng_syst
em_rng.obj
system_rng.cpp
C:\Users\Jeff\Desktop\botan\src\lib\rng\system_rng\system_rng.cpp(42): error C38
61: 'CryptAcquireContext': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\rng\system_rng\system_rng.cpp(54): error C20
39: 'CryptGenRandom': is not a member of '`global namespace''
C:\Users\Jeff\Desktop\botan\src\lib\rng\system_rng\system_rng.cpp(54): error C38
61: 'CryptGenRandom': identifier not found
C:\Users\Jeff\Desktop\botan\src\lib\rng\system_rng\system_rng.cpp(64): error C20
39: 'CryptGenRandom': is not a member of '`global namespace''
C:\Users\Jeff\Desktop\botan\src\lib\rng\system_rng\system_rng.cpp(64): error C38
61: 'CryptGenRandom': identifier not found
NMAKE : warning U4010: 'build\obj\lib\rng_system_rng.obj' : build failed; /K spe
cified, continuing ...
```

**Comment by randombit** [comment]
@noloader Thanks for checking this. Try adding `--os=winphone` to the configure.py line, in above you are still using the standard Win32 codepath.

AppVeyor has Windows Phone SDK installed so I'm hoping we'll be able to add this to CI tests eventually to prevent regressions.

**Comment by noloader** [comment]
Thanks @randombit.

`--os=winphone` was added to to the configure line. I'm still working on VS2015 ARM command prompt. I'm on Master.

```
        cl /MD /bigobj /FI sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAPI
_FAMILY_PHONE_APP  /EHs /GR /O2 /Oi /W4 /wd4250 /wd4251 /wd4275 /Ibuild\include
/nologo /c C:\Users\JDoe\Desktop\botan\src\lib\rng\system_rng\system_rng.cpp /Fo
build\obj\lib\rng_system_rng.obj
system_rng.cpp
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared\bcrypt.h(39):
 error C4430: missing type specifier - int assumed. Note: C++ does not support d
efault-int
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared\bcrypt.h(39):
 error C2146: syntax error: missing ';' before identifier 'NTSTATUS'
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared\bcrypt.h(40):
 error C2143: syntax error: missing ';' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared\bcrypt.h(40):
 error C4430: missing type specifier - int assumed. Note: C++ does not support d
efault-int
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared\bcrypt.h(40):
 error C2378: 'NTSTATUS': redefinition; symbol cannot be overloaded with a typed
ef
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared\bcrypt.h(39):
 note: see declaration of 'NTSTATUS'
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared\bcrypt.h(185)
: error C3646: 'dwMinLength': unknown override specifier
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared\bcrypt.h(185)
: error C4430: missing type specifier - int assumed. Note: C++ does not support
default-int
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared\bcrypt.h(186)
: error C3646: 'dwMaxLength': unknown override specifier
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared\bcrypt.h(186)
: error C4430: missing type specifier - int assumed. Note: C++ does not support
default-int
...
```

Looking at `C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared\bcrypt.h(39)`:

```
38   #ifndef _NTDEF_
39   typedef _Return_type_success_(return >= 0) LONG NTSTATUS;
40   typedef NTSTATUS *PNTSTATUS;
41   #endif
```

Looking at `C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared\bcrypt.h(185)`:

```
183   typedef struct __BCRYPT_KEY_LENGTHS_STRUCT
184   {
185       ULONG   dwMinLength;
186       ULONG   dwMaxLength;
187       ULONG   dwIncrement;
188   } BCRYPT_KEY_LENGTHS_STRUCT;
```

**Comment by randombit** [comment]
WTF? From that stackoverflow post:

> The main issue is that BCRYPT is supported for the Universal Windows Platform apps (aka 
  Windows 10 Store apps), but was not supported for Windows 8.x Store apps.

So, bcrypt.h is not supported on Windows 8.x Store, and CryptGenRandom is also not supported ... so ... ??? have fun calling `rand` I guess? What a strange OS.

Sadly AppVeyor only seems to include "Windows Phone SDK 8.0" which I guess also means we wouldn't be able to test any of this in CI, either.

**Pull request merged**
