### PR TITLE
[TLS 1.3] Post-Quantum Readiness via Hybrid Key Exchange

### PR DESCRIPTION
**Pull request by reneme**
### Pull-Request Dependencies

* https://github.com/randombit/botan/pull/2922
* https://github.com/randombit/botan/pull/2982

Both change sets are currently also displayed in this pull request. Hence, review and merge of those should make this PR fairly small (~700 lines added).

### TODO

* [ ] Add a "hybrid" key exchange method to the TLS policy
* [ ] Add a `minimum_kyber_group_size()` to the TLS policy (??)

### Description

This enables the TLS 1.3 implementation to perform hybrid key exchanges using a classical KEX (ECDH or X25519) and a post-quantum KEM (Kyber or Kyber90s). The implementation is based on [this IETF draft](https://datatracker.ietf.org/doc/html/draft-ietf-tls-hybrid-design-04) and the group identifiers for the Key Share extension are taken from [OQS](https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/oqs-kem-info.md).

### Demo

```bash
./configure.py                 \
    --build-targets=static,cli \
    --minimized-build          \
    --without-documentation    \
    --enable-modules=tls13,tls13_pqc,auto_rng,system_rng,chacha20poly1305,curve25519,kyber

make -j$(nproc) cli

./botan tls_client                                           \
    --policy=src/tests/data/tls-policy/default_tls13_pqc.txt \
    --port=443                                               \
    kms.eu-central-1.amazonaws.com
```

Using the snippets above, one should obtain a TLS 1.3 connection to Amazon's KMS endpoint (that is [already PQC-enabled](https://docs.aws.amazon.com/kms/latest/developerguide/pqtls.html) using their [s2n-tls library](https://github.com/aws/s2n-tls/)). Simply typing "GET / HTTP/1.1" [Enter][Enter] should yield an (admittedly useless) "Bad Request" response.

The PQC TLS 1.3 policy file passed to the CLI uses X25519/Kyber512 as the hybrid key exchange scheme.

### CODE REVIEW

**Comment by reneme** [comment]
Rebased to master.

**Review by randombit — COMMENTED** [review]
Broadly speaking looks good to me. Needs a rebase to resolve the merge conflicts and I can give a final review.

**Comment by reneme** [comment]
Rebased to master.

This will certainly need another look and compatibility testing round. Maybe it could even be used as a vehicle to find a better alternative to the `tls_dh_agree()` callbacks [discussed here](https://github.com/randombit/botan/pull/2988#issuecomment-1351218401). After all is basically just another group, of sorts.

I'd suggest to keep this open until most of the the remaining TLS 1.3 work is done and revisit.

**Comment by randombit** [comment]
There is a specific draft for X25519+Kyber768 which is already implemented by Zig stdlib and also (IIRC) Cloudflare https://github.com/bwesterb/draft-westerbaan-tls-xyber768d00/blob/main/draft-tls-westerbaan-xyber768d00.md

**Comment by reneme** [comment]
Closing as superseded by: https://github.com/randombit/botan/pull/3609

**Pull request closed without merging**
