### PR TITLE
Added implementation for GMAC

### PR DESCRIPTION
**Pull request by mgierlings**
# GMAC Summary of Changes
The GMAC implementation adds a new class named "GMAC" to the Botan library, providing functionality to perform Galois Message Authentication Code calculations. The class is based on the Botan MessageAuthenticationCode Interface and utilizes the GHASH class present in Botan.

## GMAC Test Suite Integration
GMAC has been integrated into Botan's built-in test bench. Commonly test vectors for MAC classes in Botan consist of only three elements “Key”, “In” and “Out”, GMAC test vectors are more complex, and require an additional initialization vector component. This component has been registered using the method „get_opt_bin()“.

Test vectors for the GMAC  class have been generated using the Bouncy Castle Crypto API Version 1.54. They are stored in „src/tests/data/mac/gmac.vec“ and can be run by compiling Botan and invoking the command “./botan-test mac”.

### CODE REVIEW

**Comment by randombit** [comment]
Forcing the entire message to be buffered in `m_aad` before processing at the end seems like it really limits the usability here.

But the processing of GCM's associated data, and thus of the GMAC input, can be incremental (though GHASH requires 16 byte inpus, GMAC could buffer just the 0 - 15 bytes not yet processed rather than the entire message). It seems better to define GMAC in terms of a GHASH and `m_cipher` directly. This does require duplicating some logic with GCM, but only a few lines for handling the nonce and computing E(0) for the tag mask, so I think either version is clear enough.

Specifying GMAC directly also avoids creating a state for the GCM CTR encryption `Cipher_Mode`, which is not used at all when GCM has an empty plaintext.

**Comment by jurajsomorovsky** [comment]
You are true, this is not that practical and streaming based computation would be helpful.

We would however like to avoid code duplications. Therefore, our take would be to extend the GCM encryption interface by method `update_authenticated_data`. This function could then directly be used by our GMAC class.

Of course this means that GCM provides an additional method that other AEAD ciphers do not provide. To stay consistent, other AEAD ciphers could be extended with such a method in the future.

What do you think?

**Comment by randombit** [comment]
I am not sure many applications really need such incremental AAD updates. Typically AADs are small and often fixed length. And, supporting incremental AAD may greatly complicate some of the other AEADs; already just supporting the promise that `set_associated_data` can be called once and used across multiple messages sometimes adds complications.

I'm not willing to add needed work (or a Not_Implemented throw) to every other AEAD to support a feature which is not useful to applications (IMO) just to support GMAC and avoid a few lines of code there. So, if GMAC is going to be added, I think it must be based on the existing `GHASH` interface, extended as required.

**Comment by mgierlings** [comment]
@randombit We've updated the pull request. The GMAC implementation now uses GHASH instead of GCM_Mode, let me know how you like this version.

**Comment by randombit** [comment]
@mgierlings Thanks I'll try to take a look at this today.

**Comment by randombit** [comment]
Looks good. I have made a small change in #691 to move the start calls up to the MAC base class, once CI clears I will merge to master.

**Comment by randombit** [comment]
Merged, thanks for addressing the comments.

**Pull request merged**
