### PR TITLE
Configure codecov to accept a 0.05% decrease in coverage

### PR DESCRIPTION
**Pull request by webmaster128**

### CODE REVIEW

**Comment by webmaster128** [comment]
Oh yeah, this works! Coverage -0.04% and all checks green :)

**Comment by webmaster128** [comment]
Let me check the other direction first before merging this: when there are 42694 lines now, 22 additional untested lines should have a large enough impact to make the test fail again.

**Comment by webmaster128** [comment]
Perfect, a decrease of 0.06% points let's codecov/project fail.

**Comment by randombit** [comment]
Thanks!

**Pull request merged**
