### PR TITLE
Disable MSVC warnings about inheritance via dominance

### PR DESCRIPTION
**Pull request by oviano**
I use the amalgamation build and the warnings below appear with MSVC 2022. I generally aim to build with warnings as errors where possible.

I tried fixing these with the "using" keyword but to no avail.

This PR defines a new macro BOTAN_DIAGNOSTIC_IGNORE_INHERITED_VIA_DOMINANCE and places it around the classes in question.

This warning only appears with MSVC, so the macro is empty for the other platforms.

It also renames BOTAN_DIAGNOSTIC_IGNORE_DEPRECATED to BOTAN_DIAGNOSTIC_IGNORE_DEPRECATED_DECLARATIONS to make its meaning clearer and consistent in length with the new added macro.

```
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(7392,4): error C2220: the following warning is treated as an error (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(7392,4): warning C4250: 'Botan::Curve25519_PrivateKey': inherits 'Botan::Curve25519_PublicKey::Botan::Curve25519_PublicKey::algo_name' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(7297,19): message : see declaration of 'Botan::Curve25519_PublicKey::algo_name' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(7392,4): warning C4250: 'Botan::Curve25519_PrivateKey': inherits 'Botan::Curve25519_PublicKey::Botan::Curve25519_PublicKey::estimated_strength' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(7299,14): message : see declaration of 'Botan::Curve25519_PublicKey::estimated_strength' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(7392,4): warning C4250: 'Botan::Curve25519_PrivateKey': inherits 'Botan::Curve25519_PublicKey::Botan::Curve25519_PublicKey::supports_operation' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(7311,12): message : see declaration of 'Botan::Curve25519_PublicKey::supports_operation' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(7392,4): warning C4250: 'Botan::Curve25519_PrivateKey': inherits 'Botan::Curve25519_PublicKey::Botan::Curve25519_PublicKey::key_length' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(7301,14): message : see declaration of 'Botan::Curve25519_PublicKey::key_length' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(7392,4): warning C4250: 'Botan::Curve25519_PrivateKey': inherits 'Botan::Curve25519_PublicKey::Botan::Curve25519_PublicKey::algorithm_identifier' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(7305,27): message : see declaration of 'Botan::Curve25519_PublicKey::algorithm_identifier' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(7392,4): warning C4250: 'Botan::Curve25519_PrivateKey': inherits 'Botan::Curve25519_PublicKey::Botan::Curve25519_PublicKey::public_key_bits' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(7307,28): message : see declaration of 'Botan::Curve25519_PublicKey::public_key_bits' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(8086,4): warning C4250: 'Botan::DH_PrivateKey': inherits 'Botan::DH_PublicKey::Botan::DH_PublicKey::algo_name' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(8013,19): message : see declaration of 'Botan::DH_PublicKey::algo_name' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(8086,4): warning C4250: 'Botan::DH_PrivateKey': inherits 'Botan::DH_PublicKey::Botan::DH_PublicKey::estimated_strength' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(8008,14): message : see declaration of 'Botan::DH_PublicKey::estimated_strength' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(8086,4): warning C4250: 'Botan::DH_PrivateKey': inherits 'Botan::DH_PublicKey::Botan::DH_PublicKey::supports_operation' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(8017,12): message : see declaration of 'Botan::DH_PublicKey::supports_operation' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(8086,4): warning C4250: 'Botan::DH_PrivateKey': inherits 'Botan::DH_PublicKey::Botan::DH_PublicKey::key_length' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(8009,14): message : see declaration of 'Botan::DH_PublicKey::key_length' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(8086,4): warning C4250: 'Botan::DH_PrivateKey': inherits 'Botan::DH_PublicKey::Botan::DH_PublicKey::check_key' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(8006,12): message : see declaration of 'Botan::DH_PublicKey::check_key' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(8086,4): warning C4250: 'Botan::DH_PrivateKey': inherits 'Botan::DH_PublicKey::Botan::DH_PublicKey::algorithm_identifier' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(8003,27): message : see declaration of 'Botan::DH_PublicKey::algorithm_identifier' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(8086,4): warning C4250: 'Botan::DH_PrivateKey': inherits 'Botan::DH_PublicKey::Botan::DH_PublicKey::public_key_bits' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(8004,28): message : see declaration of 'Botan::DH_PublicKey::public_key_bits' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9421,4): warning C4250: 'Botan::EC_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::estimated_strength' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9334,14): message : see declaration of 'Botan::EC_PublicKey::estimated_strength' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9421,4): warning C4250: 'Botan::EC_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::key_length' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9333,14): message : see declaration of 'Botan::EC_PublicKey::key_length' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9421,4): warning C4250: 'Botan::EC_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::check_key' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9289,12): message : see declaration of 'Botan::EC_PublicKey::check_key' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9421,4): warning C4250: 'Botan::EC_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::algorithm_identifier' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9285,27): message : see declaration of 'Botan::EC_PublicKey::algorithm_identifier' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9421,4): warning C4250: 'Botan::EC_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::public_key_bits' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9287,28): message : see declaration of 'Botan::EC_PublicKey::public_key_bits' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9525,4): warning C4250: 'Botan::ECDH_PrivateKey': inherits 'Botan::ECDH_PublicKey::Botan::ECDH_PublicKey::algo_name' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9457,19): message : see declaration of 'Botan::ECDH_PublicKey::algo_name' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9525,4): warning C4250: 'Botan::ECDH_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::estimated_strength' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9334,14): message : see declaration of 'Botan::EC_PublicKey::estimated_strength' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9525,4): warning C4250: 'Botan::ECDH_PrivateKey': inherits 'Botan::EC_PrivateKey::Botan::EC_PrivateKey::get_int_field' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9389,21): message : see declaration of 'Botan::EC_PrivateKey::get_int_field' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9525,4): warning C4250: 'Botan::ECDH_PrivateKey': inherits 'Botan::ECDH_PublicKey::Botan::ECDH_PublicKey::supports_operation' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9471,12): message : see declaration of 'Botan::ECDH_PublicKey::supports_operation' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9525,4): warning C4250: 'Botan::ECDH_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::key_length' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9333,14): message : see declaration of 'Botan::EC_PublicKey::key_length' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9525,4): warning C4250: 'Botan::ECDH_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::check_key' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9289,12): message : see declaration of 'Botan::EC_PublicKey::check_key' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9525,4): warning C4250: 'Botan::ECDH_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::algorithm_identifier' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9285,27): message : see declaration of 'Botan::EC_PublicKey::algorithm_identifier' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9525,4): warning C4250: 'Botan::ECDH_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::public_key_bits' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9287,28): message : see declaration of 'Botan::EC_PublicKey::public_key_bits' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9525,4): warning C4250: 'Botan::ECDH_PrivateKey': inherits 'Botan::EC_PrivateKey::Botan::EC_PrivateKey::private_key_bits' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9375,30): message : see declaration of 'Botan::EC_PrivateKey::private_key_bits' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9525,4): warning C4250: 'Botan::ECDH_PrivateKey': inherits 'Botan::EC_PrivateKey::Botan::EC_PrivateKey::raw_private_key_bits' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9377,30): message : see declaration of 'Botan::EC_PrivateKey::raw_private_key_bits' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9644,4): warning C4250: 'Botan::ECDSA_PrivateKey': inherits 'Botan::ECDSA_PublicKey::Botan::ECDSA_PublicKey::algo_name' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9577,19): message : see declaration of 'Botan::ECDSA_PublicKey::algo_name' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9644,4): warning C4250: 'Botan::ECDSA_PrivateKey': inherits 'Botan::EC_PrivateKey::Botan::EC_PrivateKey::get_int_field' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9389,21): message : see declaration of 'Botan::EC_PrivateKey::get_int_field' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9644,4): warning C4250: 'Botan::ECDSA_PrivateKey': inherits 'Botan::ECDSA_PublicKey::Botan::ECDSA_PublicKey::supports_operation' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9584,12): message : see declaration of 'Botan::ECDSA_PublicKey::supports_operation' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9644,4): warning C4250: 'Botan::ECDSA_PrivateKey': inherits 'Botan::ECDSA_PublicKey::Botan::ECDSA_PublicKey::message_parts' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9579,14): message : see declaration of 'Botan::ECDSA_PublicKey::message_parts' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9644,4): warning C4250: 'Botan::ECDSA_PrivateKey': inherits 'Botan::ECDSA_PublicKey::Botan::ECDSA_PublicKey::message_part_size' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9581,14): message : see declaration of 'Botan::ECDSA_PublicKey::message_part_size' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9644,4): warning C4250: 'Botan::ECDSA_PrivateKey': inherits 'Botan::ECDSA_PublicKey::Botan::ECDSA_PublicKey::create_verification_op' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9594,10): message : see declaration of 'Botan::ECDSA_PublicKey::create_verification_op' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9644,4): warning C4250: 'Botan::ECDSA_PrivateKey': inherits 'Botan::ECDSA_PublicKey::Botan::ECDSA_PublicKey::create_x509_verification_op' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9598,10): message : see declaration of 'Botan::ECDSA_PublicKey::create_x509_verification_op' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9745,4): warning C4250: 'Botan::Ed25519_PrivateKey': inherits 'Botan::Ed25519_PublicKey::Botan::Ed25519_PublicKey::algo_name' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9655,19): message : see declaration of 'Botan::Ed25519_PublicKey::algo_name' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9745,4): warning C4250: 'Botan::Ed25519_PrivateKey': inherits 'Botan::Ed25519_PublicKey::Botan::Ed25519_PublicKey::estimated_strength' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9657,14): message : see declaration of 'Botan::Ed25519_PublicKey::estimated_strength' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9745,4): warning C4250: 'Botan::Ed25519_PrivateKey': inherits 'Botan::Ed25519_PublicKey::Botan::Ed25519_PublicKey::supports_operation' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9667,12): message : see declaration of 'Botan::Ed25519_PublicKey::supports_operation' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9745,4): warning C4250: 'Botan::Ed25519_PrivateKey': inherits 'Botan::Ed25519_PublicKey::Botan::Ed25519_PublicKey::key_length' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9659,14): message : see declaration of 'Botan::Ed25519_PublicKey::key_length' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9745,4): warning C4250: 'Botan::Ed25519_PrivateKey': inherits 'Botan::Ed25519_PublicKey::Botan::Ed25519_PublicKey::algorithm_identifier' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9663,27): message : see declaration of 'Botan::Ed25519_PublicKey::algorithm_identifier' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9745,4): warning C4250: 'Botan::Ed25519_PrivateKey': inherits 'Botan::Ed25519_PublicKey::Botan::Ed25519_PublicKey::public_key_bits' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9665,28): message : see declaration of 'Botan::Ed25519_PublicKey::public_key_bits' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9745,4): warning C4250: 'Botan::Ed25519_PrivateKey': inherits 'Botan::Ed25519_PublicKey::Botan::Ed25519_PublicKey::create_verification_op' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9689,10): message : see declaration of 'Botan::Ed25519_PublicKey::create_verification_op' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9745,4): warning C4250: 'Botan::Ed25519_PrivateKey': inherits 'Botan::Ed25519_PublicKey::Botan::Ed25519_PublicKey::create_x509_verification_op' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(9693,10): message : see declaration of 'Botan::Ed25519_PublicKey::create_x509_verification_op' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16162,4): warning C4250: 'Botan::RSA_PrivateKey': inherits 'Botan::RSA_PublicKey::Botan::RSA_PublicKey::algo_name' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16014,19): message : see declaration of 'Botan::RSA_PublicKey::algo_name' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16162,4): warning C4250: 'Botan::RSA_PrivateKey': inherits 'Botan::RSA_PublicKey::Botan::RSA_PublicKey::estimated_strength' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16033,14): message : see declaration of 'Botan::RSA_PublicKey::estimated_strength' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16162,4): warning C4250: 'Botan::RSA_PrivateKey': inherits 'Botan::RSA_PublicKey::Botan::RSA_PublicKey::supports_operation' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16037,12): message : see declaration of 'Botan::RSA_PublicKey::supports_operation' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16162,4): warning C4250: 'Botan::RSA_PrivateKey': inherits 'Botan::RSA_PublicKey::Botan::RSA_PublicKey::key_length' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16032,14): message : see declaration of 'Botan::RSA_PublicKey::key_length' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16162,4): warning C4250: 'Botan::RSA_PrivateKey': inherits 'Botan::RSA_PublicKey::Botan::RSA_PublicKey::algorithm_identifier' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16018,27): message : see declaration of 'Botan::RSA_PublicKey::algorithm_identifier' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16162,4): warning C4250: 'Botan::RSA_PrivateKey': inherits 'Botan::RSA_PublicKey::Botan::RSA_PublicKey::public_key_bits' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16020,28): message : see declaration of 'Botan::RSA_PublicKey::public_key_bits' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16162,4): warning C4250: 'Botan::RSA_PrivateKey': inherits 'Botan::RSA_PublicKey::Botan::RSA_PublicKey::create_encryption_op' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16043,10): message : see declaration of 'Botan::RSA_PublicKey::create_encryption_op' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16162,4): warning C4250: 'Botan::RSA_PrivateKey': inherits 'Botan::RSA_PublicKey::Botan::RSA_PublicKey::create_kem_encryption_op' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16048,10): message : see declaration of 'Botan::RSA_PublicKey::create_kem_encryption_op' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16162,4): warning C4250: 'Botan::RSA_PrivateKey': inherits 'Botan::RSA_PublicKey::Botan::RSA_PublicKey::create_verification_op' via dominance (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16052,10): message : see declaration of 'Botan::RSA_PublicKey::create_verification_op' (compiling source file crypto_utils.cpp)
1>C:\Users\Oliver\Git\source\ovlibs\ovcore\thirdparty\botan\windows\x64\botan_all.h(16162,4): warning C4250: 'Botan::RSA_PrivateKey': inherits 'Botan::RSA_PublicKey::Botan::RSA_PublicKey::create_x509_verification_op' via dominance (compiling source file crypto_utils.cpp)
```

### CODE REVIEW

**Comment by lieser** [comment]
If we start "fixing" this (by suppressing the warning in the places it currently occurs), it probably makes sense to remove the disabling of the warning in the msvc compiler options.

**Comment by oviano** [comment]
Yes of course you are right, I should have taken this approach.

Will update.

**Comment by oviano** [comment]
> If we start "fixing" this (by suppressing the warning in the places it currently occurs), it probably makes sense to remove the disabling of the warning in the msvc compiler options.

Actually, pardon my ignorance but where do you propose this pragma warning disable goes?

It can't go in compiler.h as that is included as a public header so would disable the code in any other non-Botan code that ended up including it, such as botan_all.h in the amalgamation build.

Is there another file I've missed that will limit the scope of this to botan only?

**Comment by lieser** [comment]
> Actually, pardon my ignorance but where do you propose this pragma warning disable goes?

I think you misunderstood me.
Currently the msvc compiler warning flags for building botan itself contains `/wd4250`, which disables the C4250 warning for the build of botan. See https://github.com/randombit/botan/blob/015c0c2b3d70fbef54955ea6f308d765f73a4e5d/src/build-data/cc/msvc.txt#L34

As your change now suppresses the warning locally, this should no longer be needed.
And removing the global disabling would prevent new code being introduced that would again contain the warning.

**Comment by oviano** [comment]
> > Actually, pardon my ignorance but where do you propose this pragma warning disable goes?
> 
> I think you misunderstood me. Currently the msvc compiler warning flags for building botan itself contains `/wd4250`, which disables the C4250 warning for the build of botan. See
> 
> https://github.com/randombit/botan/blob/015c0c2b3d70fbef54955ea6f308d765f73a4e5d/src/build-data/cc/msvc.txt#L34
> 
> As your change now suppresses the warning locally, this should no longer be needed. And removing the global disabling would prevent new code being introduced that would again contain the warning.

Sorry yes, I'm with you now.

Since I was only building a subset of Botan (via the amalgamation) I was only seeing a subset of these warnings so I temporarily enabled all modules and worked through to remove them all, and finally took out the entry in msvc.txt.

**Review by randombit — APPROVED** [review]
In the past I've been hesitant to do something like this, on the basic theory that if you enabled the warning, and there is code in the header which triggers the warning, the warning should be issued.

But OTOH the warning is not actionable by the user, since it is kind of intrinsic to how the public key hierarchy is currently set up. So it is then just useless noise.

**Pull request merged**
