### PR TITLE
Run Windows CI build under ci_build.py

### PR DESCRIPTION
**Pull request by randombit**
I added support for clcache (https://github.com/frerich/clcache) but unfortunately it seems useless for our needs because it calls a cache miss whenever we rewrite `build.h`, which is every commit. So it's not used in the AppVeyor build. But left the support in ci_build.py since it might be useful for someone running tests locally or in a buildbot instance where they can do multiple builds targets on a single cache/checkout.

### CODE REVIEW

**Comment by webmaster128** [comment]
> but unfortunately it seems useless for our needs because it calls a cache miss whenever we rewrite build.h, which is every commit

There is two modes: non-direct mode compares preprocessed sources and direct mode compares contents of sources and includes. Both modes work as long as build.h contains the same content after re-creating.

**Comment by randombit** [comment]
> Both modes work as long as build.h contains the same content after re-creating.

The problem is `#define BOTAN_VERSION_VC_REVISION ...` in `build.h`, which changes on every new revision. So every file missed with 'header changed'. However I guess the problem may be I set direct mode, and clcache doesn't back down to preprocessor mode on a direct miss? I'll try skipping direct mode and seeing if that helps.

**Comment by webmaster128** [comment]
> However I guess the problem may be I set direct mode, and clcache doesn't back down to preprocessor mode on a direct miss?

As far as I can see in the code, it is not intended to fall back from direct mode to preprocessor mode. This is as far as I can see because the case that the source changed but preprocessed output does not change is rare and not considered. Only the other way is covered (source unchanged but preprocessed changes e.g. using __TIME__).

Thus setting CLCACHE_NODIRECT should help for all compilation units that do not expand BOTAN_VERSION_VC_REVISION when preprocessing.

**Comment by randombit** [comment]
Setting `CLCACHE_NODIRECT`, I see cache hits. Thanks. Testing this now.

**Pull request merged**
