### PR TITLE
Add option --module-policy

### PR DESCRIPTION
**Pull request by randombit**
A module policy is a file specifying three types of modules: ones which
are required, ones which are prohibited, and ones which should be used
if otherwise available (this is mostly for platform specific modules).

Finally there are whatever modules which exist in the library of which
the policy makes no mention. These will be included if an explicit
dependency of some other module pulls them in (so there is no reason
to mention base, utils, ... in the file) but skipped otherwise.

For example policy 'sane' does not mention 'utils' or 'twofish' either
way. Since utils is a dependency of other modules which are included,
but Twofish does not. However unlike an explicitly prohibited module,
not mentioned can still be requested as part of the build (here with
--enable-module=twofish)

Also fixes some test bugs noticed by compiling in different build
configs. DLIES test didn't check that the KDF and MAC existed. Adds a
typedef for MessageAuthenticationCode because typing it twice in a
single line in the DLIES test made me think it's way too long. :) Also
fix some fuzzer build problems. Due to a copy and paste bug the PKCS
certificate (it was not).

Inspired by GH #439

### CODE REVIEW

**Comment by neusdan** [comment]
Thanks for your work on this. Looks good. Just the missing emsa1 module for the BSI policy.

**Comment by neusdan** [comment]
I just noticed that you have prohibited unix_procs. why?

**Comment by randombit** [comment]
I think for most users it doesn't make sense to have unix_procs in the default build. It was written to support Unix systems that didn't support a randomness device, but at this point such systems are rare to non-existent. Having entropy sources other than the system RNG still seems useful as a hedge against system RNG failure (like this FreeBSD bug https://lists.freebsd.org/pipermail/freebsd-current/2015-February/054580.html), but executing external programs with fork+exec seems like a fairly error prone way to go about it, and interferes with application sandboxing. I've been thinking about deprecated and removing it entirely, but disabling it here seemed a reasonable start.

**Comment by neusdan** [comment]
Ah thanks for the explanation. Then it should be disabled in the BSI policy as well. 

One more question:
Why haven't you put these into if available:
```
 beos_stats
 darwin_secrandom
 egd
 proc_walk
```

**Comment by randombit** [comment]
Those should probably be included.

**Pull request merged**
