### PR TITLE
Generate JOM compatible makefiles

### PR DESCRIPTION
**Pull request by webmaster128**
JOM is not able to handle $@.

JOM is a drop-in replacement for `nmake` on Windows that allows you to compile in multiple cores. See also http://wiki.qt.io/Jom

### CODE REVIEW

**Comment by mouse07410** [comment]
Why not just use "make -j <number-of-cores>"?

________________________________

**Comment by webmaster128** [comment]
Because make aka GNU Make is not available on Windows.

**Comment by cdesjardins** [comment]
I know it would be a big job, but I think it would be better to just use cmake.

**Comment by webmaster128** [comment]
@cdesjardins I totally agree. But until that is possible, this tiny change allows Windows users to utilize all their cores. Since building Botan takes 15-20 minutes on my 4 cores Windows machine, this is significant.

**Comment by mouse07410** [comment]
I totally disagree regarding cmake: the fewer cumbersome tools a project depends on - the better. Porting to cmake would be the last one in the long list of things to do. Not to mention that it is (reasonably) straightforward to tweak a generated Makefile, while with cmake you need a degree in it to accomplish anything useful. Hopefully, Jack won't embark on this, at least until Botan-2.0 is released and debugged. :)

But I see your point about Windows support. Since it's already there, may want to enable multi-core compilation...


________________________________

**Comment by cdesjardins** [comment]
Interesting opinion, but I happen to think that using python to generate makefiles is cumbersome, while cmake is much more straight forward and far superior when it comes to cross platform build systems, with the extra bonus of good support for many IDEs. Of course standard gnu make is the easiest, but as soon as you need windows support make is no longer an option (for me) because MinGW is such a nasty beast.

**Comment by mouse07410** [comment]
While Python may be a beast, the Makefile it generated is not - and as you pointed out is the easiest to deal with.

And while Python has plenty of other uses - after all it's a full-fledged programming language so there is a benefit in learning it - cmake isn't good for anything but building packages, and I don't need nor want to spend time on yet another software-building tool.

One point of using a library like Botan is that it does not require IDE-type heavy guns to build it - Jack is taking care of most of that work. And for the small tweaks that are occasionally useful, "vi" and GNU "make" do the job perfectly.

If you don't like "raw" MinGW, try "cygwin". In fact I'm surprised you choose something else on Windows, as this tool also supplies you with a lot of useful Unix-like utilities. And it always worked for me. But then I'm surprised by the choice of doing any kind of development on Windows, so perhaps I'm not the best person to offer advice here.


________________________________

**Comment by webmaster128** [comment]
We used MinGW on Windows for quite a while but then switched to MSVC and friends because some of the libraries we used were not properly tested with g++ on Windows. The Microsoft compiler has it's downsides for sure but the switch also reduced the compile time of our own code about 50 %. So the important thing is that there are good reasons for both choices.

**Comment by randombit** [comment]
Whew!

For the record I'm pretty happy with using the Python (or, before it, Perl) to Makefile thing. Several proposed cmake builds have been offered, none of which did anything close to what configure.py does. And from long and ongoing experience I detest scons (for a long list of reasons, but slowness is sufficient - on my laptop it takes scons almost 1/4 of a second just to load enough of itself to tell me "No SConstruct found", and it does not get better from there).

Obnoxious about JOM missing $@, have you considered opening a bug with them?

**Comment by mouse07410** [comment]
On Mar 11, 2015, at 19:13 , Jack Lloyd <notifications@github.com> wrote:
> For the record I'm pretty happy with using the Python (or, before it, Perl) to Makefile thing.
> 
And please, please keep using it. I’ve been pretty happy with the Botan setup too.
> Several proposed cmake builds have been offered, none of which did anything close to what configure.py does.
> 
Please, please don’t even think about cmake. It will kill tweak-ability that, for example, allows me to build Botan with AES-NI and other instructions that system compiler doesn’t enable by default.
> And from long and ongoing experience I detest scons (for a long list of reasons, but slowness is sufficient - on my laptop it takes scons almost 1/4 of a second just to load enough of itself to tell me "No SConstruct found", and it does not get better from there).
> 
:-)
> Obnoxious about JOM missing $@, have you considered opening a bug with them?
> 
I second this. :-)
--
Uri Blumenthal
uri@mit.edu

**Comment by webmaster128** [comment]
Thanks for forcing me to dig deeper into the topic. It turn out that `$@` works great in JOM. The problem is `$?` is buggy and `$<` seems to require some special escaping to work. Bug report is submitted: [QTCREATORBUG-14125](https://bugreports.qt.io/browse/QTCREATORBUG-14125). For now this branch will replace `$?` with the source file.

**Comment by webmaster128** [comment]
Replaced by https://github.com/randombit/botan/pull/66 because I think I need to rebase the branch in order to keep the pull request up-to-date and the .patch file clean.

**Pull request closed without merging**
