### PR TITLE
ECKCDSA improved and faster verification

### PR DESCRIPTION
**Pull request by neverhub**
Shamir's Trick (multi_exponentiate) for better verification speed and calculate size of r for accurate initial checks.

### CODE REVIEW

**Comment by neverhub** [comment]
Old speed:
```
ECKCDSA-secp256r1 183 EMSA1(SHA-256) verify/sec; 5.46 ms/op (56 ops in 305.83 ms)
ECKCDSA-secp384r1 132 EMSA1(SHA-256) verify/sec; 7.53 ms/op (42 ops in 316.23 ms)
ECKCDSA-secp521r1 84 EMSA1(SHA-256) verify/sec; 11.79 ms/op (26 ops in 306.45 ms)
```
New speed:
```
ECKCDSA-secp256r1 473 EMSA1(SHA-256) verify/sec; 2.11 ms/op (142 ops in 300.20 ms)
ECKCDSA-secp384r1 312 EMSA1(SHA-256) verify/sec; 3.20 ms/op (94 ops in 301.17 ms)
ECKCDSA-secp521r1 216 EMSA1(SHA-256) verify/sec; 4.62 ms/op (66 ops in 304.91 ms)
```
Even if ECKCDSA is not widely used. Now the speed results are close to ECDSA and ECGDSA.

**Comment by randombit** [comment]
Wow, thank you. Seems ok to me on a first pass, but I would like input from @cordney as I am not so familiar with this code or signature scheme.

**Comment by cordney** [comment]
I could already take a look before the PR. Looks good, I must have somehow missed the `multi_exponentiate()`, which I already used in ECGDSA. The size calculation looks also correct. Thanks for the improvements!

**Comment by randombit** [comment]
Merged, thank you!

**Pull request merged**
