### PR TITLE
Fix GH's formatting of readme.rst

### PR DESCRIPTION
**Pull request by randombit**

### CODE REVIEW

**Review by reneme — APPROVED** [review]

**Comment by reneme** [comment]
Perhaps add a badge for Conan?

```
.. image:: https://img.shields.io/conan/v/botan   :alt: Conan Center
```

**Comment by randombit** [comment]
I'm not sure if there is a reason to favor Conan vs other repos that are all listed on the repology link (eg Vcpkg, Ubuntu, Arch, ...) is Conan specifically popular enough to matter? Conan has 7k stars vs Vcpkg 21k, for example.

**Comment by randombit** [comment]
Merging now because the way GH is spacing the badges is *really* bugging me :joy: happy to continue discussion in a PR or ticket.

**Comment by reneme** [comment]
Fair point, re:conan. I incidentally stumbled over that badge today and just wanted to point out that it exists. No need to favor conan here.

**Pull request merged**
