### PR TITLE
Adopt (temporary) PQC OID mappings from IETF hackathon

### PR DESCRIPTION
**Pull request by reneme**
As suggested in #3585, this changes the (nonetheless temporary) OID mappings for Kyber, Dilithium and SPHINCS+ to the [mappings used in the IETF interoperability hackathon](https://github.com/IETF-Hackathon/pqc-certificates/blob/b5b1cdd95ce805e08756d7ba2539f9cca3816519/docs/oid_mapping.md).

For backward compatibility to Botan 3.0.0, we will be able to read the OIDs for Kyber/Dilithium that were previously defined in Botan's private region.

With SPHINCS+ [merged earlier today](https://github.com/randombit/botan/pull/3549) no backward compatibility will be needed here. However, the hackathon does not seem to define OIDs for SPHINCS+ with SHAKE (let alone Haraka). We therefore have no other choice than to keep those in Botan's private region for now.

 @janklaussner, @randombit Thoughts on that?

### CODE REVIEW

**Comment by randombit** [comment]
@reneme Looks fine to me modulo the concerns about key encoding I raised in #3585. I have not had a chance to follow up on this aspect.

**Comment by randombit** [comment]
I'm going to defer on this one until 3.2 - the worst possible outcome here is we switch the OIDs but then the other implementations are using an incompatible key encoding. That would leave us with a bigger problem than the current situation.

**Comment by randombit** [comment]
@reneme Should we actually ship these OID mappings at all? I'm assuming at this point any standardization of formats will be for the final FIPS variants.

**Comment by reneme** [comment]
Agreed. Let's close this.

**Pull request closed without merging**
