### PR TITLE
Improve readability and usability of test-output of botan.py

### PR DESCRIPTION
**Pull request by mouse07410**
Fixed introduced Mac-specific change, returning the patch to platform-independent.

Original patch was to improve clarity and readability of the test/demo output provided by botan.py.

### CODE REVIEW

**Comment by webmaster128** [comment]
Now this does not works for you on OSX any more. So you have to manually edit the file every time you do something with it. Why not just add a case distinction like:

```
sys.platform == "darwin":
    # OS X code
else:
    # linux code
```

**Comment by webmaster128** [comment]
ps.: You can modify your pull request by just pushing additional commits. You don't need to close it.

**Comment by webmaster128** [comment]
Did you add Python 3 support (by changing `print()` style)? That would be something important to mention in the description

**Comment by mouse07410** [comment]
Any comments so far? 

I have another patch in the pipeline, making this script compatible with both Python-2 and Python-3...

**Comment by webmaster128** [comment]
Please use 4 spaces consistently in python scripts. In some setups this is required.

Apart from these stylistic remarks, I do not really know what the script is made for and I never used Botan in Python. So I think Jack has to have a look at it.

**Comment by mouse07410** [comment]
Now it should be fully compatible with Python-3. 

Note: readme.rst applies to my fork only, so probably no need to merge it. I just don't know how to isolate it from the pull request.

**Comment by mouse07410** [comment]
Re. spaces: will do (need to re-program my Emacs for that :).

**Comment by webmaster128** [comment]
Please remove your changes in the readme, because when we merge, the text will be in the main readme.

When you want to highlight what your branch does, use the following workflow:


* Backup your changes (https://patch-diff.githubusercontent.com/raw/randombit/botan/pull/247.diff)
* Create a new fork `randombit/botan:master` to `mouse07410/botan:master`
* Create a branch called for example `change-botan-py` using `git checkout -b change-botan-py`
* Apply your changes (`git apply mybackup_247.diff`)
* Create a pull request from `mouse07410/botan:change-botan-py` to `randombit/botan:master`

By having a separate branch name, one can quickly see what the branch is about.

**Comment by mouse07410** [comment]
Thank you, will do.

**Comment by mouse07410** [comment]
Done.

**Comment by mouse07410** [comment]
Any idea when this PR could get reviewed (and hopefully approved/merged)?

**Comment by randombit** [comment]
Thanks! The new output looks great. I have not had time to review PRs until tonight.

**Comment by mouse07410** [comment]
My pleasure. Now that the code is working properly on Python-2.7 and Python-3.x (tested on v3.4), the next update I'm planning is getting the .py source more "palatable". I.e. refactor those "xxx.encode()" and "xxx.decode()" where possible, probably into something like "b'xxx'"... I'll see if the source looks easier to read that way (it probably should, but one never knows until there's something to compare with :)...

**Pull request merged**
