### PR TITLE
Fix various x509 path validation bugs + path building with ambiguous DNs

### PR DESCRIPTION
**Pull request by fweissberg**
Various improvements for X509 path validation
* Some `Certificate_Status_Code`s between 500 and 1000 are considered "warnings"
* `x509_path_validate` uses the Certificate_Status_Code::SIG_ALGO_UNKNOWN instead of an exception if necessary
* Check for negative certificate serial numbers: `x509_path_validate` uses the warning Certificate_Status_Code::CERT_SERIAL_NEGATIVE
* Check for DistinguishedName attributes that are longer than permitted: `x509_path_validate` uses the warning Certificate_Status_Code::DN_TOO_LONG
* Check for unknown critical extensions in CRLs: `x509_path_validate` uses the Certificate_Status_Code::CERT_IS_REVOKED. rationale from NIST "Certificate Path Valiadation Testing" document: "When an implementation does not recognize a critical extension in the crlExtensions field, it shall assume that identified certificates have been revoked and are no longer valid"
* Check that x509v1 and x509v2 certificates do not contain extensions: `x509_path_validate` uses the Certificate_Status_Code::EXT_IN_V1_V2_CERT
* Implement a basic version of the issuing distribution point extension for CRLs: `x509_path_validate` uses the Certificate_Status_Code::NO_MATCHING_CRLDP
* Check that policy OIDs are unique within the Certificate Policies Extension: `x509_path_validate` uses the Certificate_Status_Code::DUPLICATE_CERT_POLICY

* CRL_Distribution_Points::decode_inner
    * only uris were considered, now all contents of the AlternativeName are concatenated
* AlternativeName::decode_from
    * AlternativeNames can be DistinguishedNames

* Cache some extensions in X509_CRL objects, as indicated by already existing comments (crl number, authority key id, crl_issuing_distribution_point)
    * fix: cached m_crl_number is now set correctly
    * fix: cached m_auth_key_id is now set correctly
    * add: cache m_issuing_distribution_point

* Implement `build_all_certificate_paths` that generates a list of possibly valid paths. A certificate's issuing certificate not be unambiguous in a set of certificates so there might be more than one path to check. 

[#1283](https://github.com/randombit/botan/issues/1283)
[#1359](https://github.com/randombit/botan/issues/1359)

### CODE REVIEW

**Comment by randombit** [comment]
Nice I'll review this in the next few days.

Comments from a brief scan
 - Please add copyright/license statements to new files (like X509_dn_ub.*) or files with major changes (like x509path.cpp, oids.py, etc)
 - Filenames should all be lowercase (X509_dn_ub -> x509_dn_ub)
 - Add a brief readme in `src/tests/data/x509/bsi` indicating the source of the test data.
 - Test all of the added enum values in `test_cert_status_strings`

**Comment by randombit** [comment]
@fweissberg Due to other merges there are few conflicts now, though all look easily resolvable. Can you rebase against master? Certificate_Status_Code::SIG_ALGO_UNKNOWN` can be removed.

Also the CI build is failing because `Certificate_Store::find_all_certs` is not implemented for the SQL datastore.

**Comment by fweissberg** [comment]
I'll have a look at it in the morning (in European time).

**Comment by fweissberg** [comment]
I had to remove the check that prevents adding duplicate certificates in `Certificate_Store_In_SQL::insert_cert` in order to sensibly implement `Certificate_Store_In_SQL::find_all_certs`.

**Comment by randombit** [comment]
@fweissberg Reviewed, looks good so will merge shortly. Thanks.

BTW for future work it is easier if the changes are split where possible, eg adding support for DNs in the AlternativeName could have been an independent PR since it is not connected with the path building logic.

**Pull request merged**
