### PR TITLE
Proposal to silent, when wished, some "false positives" when using sa…

### PR DESCRIPTION
**Pull request by devnexen**
…nitizers.

To be improved overtime eventually.

### CODE REVIEW

**Comment by randombit** [comment]
I don't understand. With Clang 7.0 I see no warnings running the test suite under UbSan. If there are any UbSan issues, we should fix them.

**Comment by devnexen** [comment]
Well sure but I think the test assign on purpose some bad values thus do not if to be considered as false positive or not ... Tested with clang 7 on FreeBSD though.

**Comment by randombit** [comment]
Interesting. We do have a few cases like that but they should all be guarded and only used if `--no-avoid-undefined` flag is set. Maybe something about the compilation (specific optimization flags or whatever) causes the undefined behavior to still be executed even if the flag is not set at runtime.

May be better to remove the flag and runtime tests, and guard these at build time with `#if !defined(BOTAN_HAS_SANITIZER_UNDEFINED)`

**Comment by randombit** [comment]
I think you missed a git add

**Comment by devnexen** [comment]
Yes all in fact

**Comment by randombit** [comment]
Looks good thank you

**Pull request merged**
