### PR TITLE
Fix x86 32-bit building for clang on Mac OS

### PR DESCRIPTION
**Pull request by Bi11**
-m32 must be set for 32-bit building. -m64 is the default to clang (Xcode) that released in recent a couple of years.

### CODE REVIEW

**Comment by Bi11** [comment]
With Apple clang, if MACOSX_DEPLOYMENT_TARGET is set to 10.8 or 10.7, -stdlib is default to libstdc++. It will cause a error says: 'cstdint' file not found.

**Comment by webmaster128** [comment]
Shouldn't `-stdlib=` be in the `lang_flags` along with `-std=c++11`?

**Comment by Bi11** [comment]
I don't know whether it should be applied to all Linux.
I can only confirm with Mac OS at this time, and I don't want to break anything else.
We should move `-stdlib` into `lang_flags` if this issue can be confirmed by someone familiar with Linux.

**Comment by webmaster128** [comment]
You're right. I did not see that this affects Linux. mach_abi_linking end up in CXX, so it is fine there.

**Comment by randombit** [comment]
Looks good to me. Thank you for the patch.

**Pull request merged**
