### PR TITLE
OCSP stapling enabled in TLS server

### PR DESCRIPTION
**Pull request by cryptosource-GmbH**
quote from previously exchanged email:
=>
for a project I implemented OCSP stapling in Botan in a rudimentary
version.

Previously the status_request TLS extension and the Certificate_Status
message were in the code, but the Botan server could do nothing else
than repeating the status_request extension to the client (which is
legitimate). It was not possible to actually send an OCSP response. I
implemented this now by adding a corresponding callback. The callback
will set the encoded OCSP-response, while the existing implementation
intended to provide it as an object. In our project we definitely need
to use the encoded response, since we want to use the server to also
send invalid responses for testing purposes. However, I generally think
that unnecessary encoding / decoding should be avoided. Any unsupported
feature of OCSP-responses or a bug in the encoding or decoding routines
would unnecessarily affect the OCSP stapling. So I suggest to remove the
original approach using the response object altogether (as I wrote above
it was so far unusable anyway). This I have not yet done.
<=

In the meanwhile I have also completed the signature of the OCSP-response providing callback with the server's certificate chain and the decoded status_request extension from the clientHello.

### CODE REVIEW

**Comment by randombit** [comment]
Sorry about delay here, looks OK though I want to write some covering tests before merge.

**Comment by falko-strenzke** [comment]
Ok, what exactly do you want to cover with tests? Maybe I can help...

**Comment by randombit** [comment]
Automated tests covering at least 1) a successful transfer/processing of a response 2) a transfer of an invalid response which the client rejects.

Plus ideally some way of doing OCSP in the CLI so that for example stapling can be tested with `tls_http_server` and a standard browser.

**Comment by falko-strenzke** [comment]
> Automated tests covering at least 1) a successful transfer/processing of a response 2) a transfer of an invalid response which the client rejects.
In order to determine the effort for the implementation of such tests as a precondition to get the approval to realize these in the scope of our current project, I have some further questions regarding the tests:
What do you mean exactly by "transfer/processing"? Would that be an execution of a TLS handshake in the course of the unit tests? Where would such tests be implemented exactly within the Botan test code?
What I implemented is the support of the extension in Botan TLS server, so I would only implement tests covering the behaviour regarding Botan's TLS server...

> Plus ideally some way of doing OCSP in the CLI so that for example stapling can be tested with `tls_http_server` and a standard browser.
This is straightforward, I basically have already done that within our project. I would add a command-line parameter "--stapled_response=..." the file to which this points the TLS server would then send whenever the client requests the certificate status in the ClientHello.

**Comment by randombit** [comment]
With BoGo merged we now have a way of comprehensively testing server OCSP handling, so this just needs a rebase plus enabling the relevant tests in BoGo runner. I'll look at this soon.

**Comment by randombit** [comment]
Taken up in #1967

Thanks again for contributing this

**Pull request closed without merging**
