### PR TITLE
Addresses two problems with bcrypt() in botan.py

### PR DESCRIPTION
**Pull request by mouse07410**
Fixed bcrypt() argument problem (lines 313 and 322). Fixed buffer overread in bcrypt() (line 316). Added bcrypt() demo/test (mainly to ensure it produces result similar in size between python3 and python2).

### CODE REVIEW

**Comment by mouse07410** [comment]
Please kick the CircleCI build again.

**Comment by webmaster128** [comment]
You can close and re-open a pull request to trigger a re-build. This works at least for Travis.

**Comment by mouse07410** [comment]
It worked for Travis and AppVeyor - but not for CircleCI. :-(

**Comment by webmaster128** [comment]
Okay, then you can change your commit (e.g. by removing this useless empty line https://github.com/randombit/botan/pull/464/files#diff-87e1b5c848d215e087e337ce56c392cbR719). This can be done using git-cola (Ctrl+M) and then force push (`git push -f`).

Pushing an undated commit will trigger new CI runs.

**Comment by mouse07410** [comment]
Thank you, done. I think it's ready for merging now. ;)

**Comment by mouse07410** [comment]
Since this fix is rather small - could I ask to review it? (I'm dreading to have our forks diverge.)

**Comment by randombit** [comment]
Merged. Thanks for looking into this.

**Pull request merged**
