### PR TITLE
Rewrite calls to get_byte<T>(...) to eliminate compiler warnings.

### PR DESCRIPTION
**Pull request by DanielTBrown**
Ideally, botan would compile with no warnings. This change eliminates approximately half the C++ compiler warning messages when I build botan.

Calls 'get\_byte\<T\>\(..., T input\)' are rewritten 'get\_byte\(.., static\_cast\<T\>\(input\)\)'. This change makes the cast of parameter 'input' to type 'T' explicit instead of implicit.

The 'get\_byte' expression 'sizeof\(T\)\-1\-\(byte\_num&\(sizeof\(T\)\-1\)\)' is rewritten '\(\~byte\_num)&\(sizeof\(T\)\-1\)'. This is clearer.

### CODE REVIEW

**Comment by randombit** [comment]
Can you be more specific about which compiler/warnings these are avoiding? I ask because I do not see warnings in these areas with GCC or Clang on my machine, or on VC2015 CI builds.

**Comment by DanielTBrown** [comment]
I am sorry that my original report is incomplete. Here is the missing information:

Microsoft Visual C++ 2013, compiling for 'x86_64', reports:

 warning C4267: 'argument' : conversion from 'size_t' to 'Botan::u32bit', possible loss of data

From the source code lines:

void store_be24(byte out[3], size_t val)
   {
   out[0] = get_byte<u32bit>(1, val);  <- reports warning C4267
   out[1] = get_byte<u32bit>(2, val);  <- reports warning C4267
   out[2] = get_byte<u32bit>(3, val);  <- reports warning C4267
   }

The warning message is correct. 'get_byte<u32bit>' expects a 'u32bit' as the second parameter, but 'val' is a 64-bit size_t. The problem is solved by casting 'val', and allowing the compiler to infer the 'get_byte' template to instantiate, as done in all other botan calls to 'get_byte':

   out[0] = get_byte(1, static_cast<u32bit>(val));

For reference, the parameters to 'configure.py' are:

--minimized-build --enable-modules=tls --cc=msvc --cpu=x86_64 --gen-amalgamation --disabled-shared

Microsoft Visual C++ 2013 reports approximately 60 warnings, the issue with get_byte accounts for approximately half of those warnings. I will address the other warnings as I have time.

**Comment by DanielTBrown** [comment]
The botan Makefile for Microsoft Visual C++ explicitly suppresses some warnings about implicit casts: /wd4267. That may explain why you are not seeing these warnings reported using Microsoft Visual C++ 2015.

For more information, see the Microsoft MSDN documentation for warning C4267: https://msdn.microsoft.com/en-us/library/6kck0s93.aspx

**Comment by DanielTBrown** [comment]
This pull request is superseded by request #484.

**Pull request closed without merging**
