### PR TITLE
X509_Certificate::allowed_usage fix

### PR DESCRIPTION
**Pull request by neusdan**
in my understanding it should not return true if ex_constraints() returns an empty list

### CODE REVIEW

**Comment by neusdan** [comment]
I have to lookup the test failures, but from the Doxygen documentation:

> Returns true if and only if name (referring to an extended key constraint, eg "PKIX.ServerAuth") is included in the extended key extension.

i do not unterstand why this should return true, if there are no extended key constraints.

**Comment by randombit** [comment]
I think the idea is that if no extended constraint extension is in the cert then there is no particular implication on which usages are allowed/disallowed.

**Comment by neusdan** [comment]
But I want to check if a specific extended key usage is in the certificate. Is there an other way to check this?

**Comment by randombit** [comment]
Examine return value of `ex_constraints` for the desired constraint

**Comment by neusdan** [comment]
yeah right, thx

**Comment by neusdan** [comment]
Can we add a `has_constraint( Key_Constraints usage )` and `has_ex_constraint( const std::string& ex_constraint )`
or something similar?

**Comment by randombit** [comment]
Yeah that seems fine, feel free to submit a PR with those.

**Pull request closed without merging**
