### PR TITLE
Remove dependency: base depends on mac

### PR DESCRIPTION
**Pull request by webmaster128**

### CODE REVIEW

**Comment by randombit** [comment]
OK I guess, but why?

One thing, `lookup.h` should have guards for MACs being disabled. You probably missed this because nothing in the lib or tests includes that header.

**Comment by webmaster128** [comment]
This came to my mind when thinking about a "hash depends on mac" dependency.

Just a low hanging fruit trying to reduce complicated and especially circular dependencies. I think base should not depend on anything in order to move from a chaotic dependency graph to something that looks more tree-ish. With this change, you can build the library without the mac module and if needed, the dependency should be added explicitly or via parent-folder dependencies.

**Comment by webmaster128** [comment]
Thanks for feedback, updated.

**Comment by webmaster128** [comment]
:+1:

**Pull request merged**
