### PR TITLE
NIST SP800-108 & 56c

### PR DESCRIPTION
**Pull request by flanfly**
This commit implements the KDFs defined in NIST SP800-56c and 108. The KDF API in Botan has not way to set the context and label parameters so they're both hard coded to the empty string. I'll will fix this in a subsequent PR.

The SP800-108 test vectors come from NIST's CAVP, those for SP800-56c were generated using a sightly modified version of PyCryptodome.

### CODE REVIEW

**Comment by randombit** [comment]
Very nice work here, thanks.

**Comment by randombit** [comment]
One thing I notice comparing to SP 800-108 is the KDFs all use `Label || 0x00 || Context || [L])` as the static input but here the `[L]` (encoding of the length of L) is omitted. I thought perhaps the Salt in the vector files was actually just this entire block pre-formatted to work around the lack of distinct Label/Context inputs, but that doesn't seem to be the case since some of the Salt values in the vector file lack a 0x00 byte entirely, and the final bytes don't seem to be length fields. From my read of 800-108 it does not look like this `[L]` is optional. What's the deal here?

**Comment by flanfly** [comment]
You are right. The vectors from CAVP don't aren't in the format 800-108 defines. Until the KDF API is expanded the caller has to ensure the input into the KDF is in the ``Label || 0x00 || Context || [L]`` format.

**Comment by flanfly** [comment]
Would it be acceptable for Botan to remove the CAVP test vectors and replace them with ones that actual fits the ``Label || 0x00 || Context || [L]``? I'd create them using another FLOSS implementation of SP800-108.

**Pull request merged**
