### PR TITLE
Make the cmake a bit more flexible and start on install

### PR DESCRIPTION
**Pull request by cdesjardins**

### CODE REVIEW

**Comment by randombit** [comment]
I have no opinion. It looks reasonable enough but I'll wait for @webmaster128 to review and merge.

**Comment by webmaster128** [comment]
Nice work. Question is if we really want auto-detection of configurations based on file existence. Given the current ./configure that would work but I think the more stable way would be to add those switches as cmake parameters.

**Comment by cdesjardins** [comment]
I don't know if you missed it or not, but I updated these patches a few days ago, now the user must specify -DWITH_ZLIB=1 (for example)...

**Comment by webmaster128** [comment]
Thanks. I missed that. There are no notifications for code changes on PR branches. I'll have a look at it soon.

**Pull request merged**
