### PR TITLE
Distinguish between LLVM Clang and XCode Clang

### PR DESCRIPTION
**Pull request by randombit**

### CODE REVIEW

**Comment by reneme** [comment]
That idea makes a lot of sense! Let me know if I should take this up. Judging from the commit messages you don't have a Mac handy. ;)

**Comment by reneme** [comment]
Locally, this seems to work for me. Would probably make sense to have a sharp look at all of the flags in xcode.txt.

**Comment by randombit** [comment]
OK things are looking good to me at this point.

**Comment by randombit** [comment]
I'll squash before merging

**Pull request merged**
