### PR TITLE
Add botan encryption cli app

### PR DESCRIPTION
**Pull request by webmaster128**

### CODE REVIEW

**Comment by randombit** [comment]
I think this is operating at too low a level for the CLI tool. I envisioned any such encrypt/decrypt command line tool as providing an interface at least at the level of "encrypt this file to the public key provided" and/or "encrypt this file under the given passphrase" (using PBKDF2 w/ salt and iteration count included in the serialized file).

I'm not sure that there is an existing standard worth copying here short of a full OpenPGP impl (though there may be; I'm not sure for instance what `openssl` provides) but at the very least it should provide something that is practically useful to an end-user.

**Comment by webmaster128** [comment]
Thanks for your feedback, Jack. I am developing this a little further (with low priority) and we'll see what we can make out of it.

**Comment by randombit** [comment]
@webmaster128 Took me long enough but I realized I was completely wrong in my previous response - `openssl enc` provides exactly this low-level cipher interface, and being shell-compatible (feature wise, not interface wise) is useful. Additionally a low level cipher interface provides a great example of cipher library usage, without clouding things up overmuch with versioning, PBKDF, etc. If/when PGP becomes available in the library a distinct cmdlet can be written to call that API.

Can you rebase this PR?

**Comment by webmaster128** [comment]
I just realized that you answered here @randombit. Sorry, I did not see this for months because this PR lost priority for me after I generated some sample data with it. I'll rebase this now.

**Comment by webmaster128** [comment]
> Additionally a low level cipher interface provides a great example of cipher library usage

Funny, I was just looking into this PR to support [this guy](https://stackoverflow.com/questions/43424158/botaninvalid-argument-at-memory-location-0x0000004ca34fa658)

**Comment by webmaster128** [comment]
This is ready for review

**Pull request merged**
