### PR TITLE
FIX: Missing update of XMSS private key in CLI's X.509 operations

### PR DESCRIPTION
**Pull request by reneme**
XMSS was not explicitly handled in `x509_obj.cpp` (`x509_signature_padding_for()`). Using XMSS private keys to sign certificates and CSR therefore resulted in: "Unknown X.509 signing key type: XMSS". One could conclude that we didn't want to allow XMSS for X.509 signing in the first place.
Anyway: By just passing an arbitrary EMSA to the CLI (like: `--emsa=lol`) this check could be circumvented and an XMSS signature was generated just fine. Though, update of the private key file was missed as reported in #3578.

This patch conditionally updates the private key file (as is done in `./botan sign`). Also, it adds XMSS to `x509_signature_padding_for()`, so `--emsa=` is not required (aka ignored) for XMSS.

IMO, this is a security issue and should be back-ported to the 2.x branch. Does it also justify a security advisory and/or CVE? @randombit

### CODE REVIEW

**Comment by reneme** [comment]
> If XMSS was not intended to sign X.509, what would be the expected usecase?

Apart from X.509 you could use it as a building block for your own protocols. Whenever you can establish trust in a public key without certification. E.g. to sign software updates for some proprietary gadget and bake the XMSS public key into your hardware.

Anyway, it appears that the missing XMSS handling in X.509 was merely an oversight.

**Comment by mouse07410** [comment]
Probably the "largest" use case for XMSS works be firmware signing. IMHO, _definitely_ not X.509.

**Comment by thewalker77** [comment]
Well, even for firmware signing, I would say that some standards use X.509 like DICE, and caliptra, x509 is  (to the best of my knowledge) just data exchange format

**Comment by randombit** [comment]
> If XMSS was not intended to sign X.509, what would be the expected usecase ?

Keep in mind the limitation here is just in the command line utility

**Pull request merged**
