### PR TITLE
Avoid throwing base Botan::Exception type

### PR DESCRIPTION
**Pull request by randombit**
As it is difficult to determine what the error is when such an exception is caught.

See GH #1742

### CODE REVIEW

**Comment by ChrisBFX** [comment]
Thanks a lot for looking into and working on this!
Removing the usage of the base exception and the added error_code looks good.
I'm not sure if I understand the motivation behind the ErrorType enum though. It looks like it only changes a bunch of catch() clauses into a switch case?
The combination of error_code and error_type looks a lot like what the std::error_code does (value and category), at least semantically. Anyhow i think it would be better if the enum starts at 1 (most conventions are that 0 is not an error).

**Comment by randombit** [comment]
Looking at it more, `std::error_code` and co seems kind of oddly designed and I'm not sure we want to use it directly. Or at least not until I understand it better. For now I've stuck with `error_type` and `error_code`, and if we want to support the std APIs later I think that can be built on top of these.

I renumbered the `ErrorType` enum to start at 1 thanks for the suggestion.

**Comment by dewyatt** [comment]
@randombit Just a note, making the `Exception` constructor protected breaks the softhsm build at the moment. Not sure if other projects actually use that. It seems odd to use Botan's exception class but I guess it's one of those "if you build it they will come" type of things.

**Comment by randombit** [comment]
@dewyatt Thanks for letting me know, I'll revert the part that makes the base class constructor protected.

I also just added build/test SoftHSM using latest code as part of the release checklist.

**Comment by dewyatt** [comment]
> Thanks for letting me know, I'll revert the part that makes the base class constructor protected.

@randombit That's great! I went ahead and did a PR for SoftHSM to throw `Encoding_Error` instead, which I figure should make it compatible with more commits of botan regardless.

> I also just added build/test SoftHSM using latest code as part of the release checklist.

Sweet! One thing to note just in case you're not aware, I think they use a slightly unusual branching strategy where `master` is the latest release and `develop` (their default branch) is where development really happens (more akin to Botan's master).

**Pull request merged**
