### PR TITLE
First part of configure main() cleanup

### LINKED ISSUE #990: Can we remove --chost from configure?
While refactoring main() in configure.py, I came across the --chost option [added 5 years ago](https://github.com/randombit/botan/commit/b72900c62a5c27e588a5512e65ced402bb508871) as an undocumented convenience argument.

Is this option used anywhere or can it die in favor of less complex configure code?

### PR DESCRIPTION
**Pull request by webmaster128**
Closes #990

@securitykernel Could you please have a look and test the changes I made to in-house curves (commit "Pull out HouseEccCurve class" + 3)? I don't know any way to test the code

### CODE REVIEW

**Comment by securitykernel** [comment]
House curve changes look good to me. Only thing I would like to have changed is the error message when the curve.pem was not found, currently its internal error:

```
  ERROR: Traceback (most recent call last):
  File "./configure.py", line 2832, in <module>
    main()
  File "./configure.py", line 2740, in main
    template_vars = create_template_vars(source_paths, build_config, options, using_mods, cc, arch, osinfo)
  File "./configure.py", line 1907, in create_template_vars
    variables['house_ecc_curve_defines'] = make_cpp_macros(HouseEccCurve(options.house_curve).defines())
  File "./configure.py", line 1733, in __init__
    'HOUSE_ECC_CURVE_PEM ' + self._read_pem(filename=p[0]),
  File "./configure.py", line 1742, in _read_pem
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: 'curve.pem'

An internal error occurred.

Don't panic, this is probably not your fault!
```

**Comment by webmaster128** [comment]
Good point, will implement

**Comment by webmaster128** [comment]
okay, added 3 commits including the UserError for io problems.

So this is ready from my side

**Comment by securitykernel** [comment]
Thanks!

**Comment by randombit** [comment]
LGTM thanks!

**Pull request merged**
