### PR TITLE
Support passing an OAEP label in EME name

### PR DESCRIPTION
**Pull request by securitykernel**
TPM 1.2 expects passing the owner and SRK secret encrypted with the public endorsement key.
For asymmetric encryption, the TPM 1.2 uses OAEP with the label "TCPA".

### CODE REVIEW

**Comment by randombit** [comment]
Looks OK (though these code paths are getting a little messy) but *tests please* :)

**Comment by randombit** [comment]
There is one OAEP with label test here https://github.com/pyca/cryptography/blob/master/vectors/cryptography_vectors/asymmetric/RSA/oaep-label.txt

**Comment by randombit** [comment]
Oh you're right, that is unfortunate. I'm not sure where else to source a test vector beyond writing an OpenSSL test prog.

**Comment by securitykernel** [comment]
Ok, will try OpenSSL.

**Comment by securitykernel** [comment]
Add one test vector in c94c227 generated using OpenSSL and rebased.

**Comment by randombit** [comment]
Nice thanks. I will merge after 2.5 release goes out

**Pull request merged**
