### PR TITLE
Add override specifiers

### PR DESCRIPTION
**Pull request by tiwoc**
Adding `override` to a method makes sure that it is virtual and that it overrides a method of a base class. This improves readability and triggers a compiler error if a method that is meant to override doesn't do so.

### CODE REVIEW

**Comment by tiwoc** [comment]
In the first version of this PR, I included the command line flag for GCC that helped me find many of these occurrences (`-Wsuggest-override`) in the warning flags in `src/build-data/cc/gcc.txt`. Travis CI, however, told me that the flag is sadly not available in GCC 4.8. It was introduced somewhere on the way to 5.1, which is what I used, so I removed the relevant commit.

**Comment by tiwoc** [comment]
CI fails due to #233

**Comment by webmaster128** [comment]
You can trigger a CI re-run by closing and re-opening the PR

**Comment by randombit** [comment]
Override annotations are definitely an aid to code comprehension. Thanks for doing this.

**Pull request merged**
