### PR TITLE
String comparision fixes

### LINKED ISSUE #377: String comparision
I've ran the static analyzer PVS-Studio on the Botan code base. It's shows a lot of performance warnings for places where strings are compared like this `if (s == "")` instead of `if (s.empty())`

The explanation from PVS-Studio:

> The object of the 'std::string' class knows the length of the string it is storing, but it is unknown which string it is intended to be compared to. That's why a loop is called for string comparing

It's clear that it won't make much difference but i would send a PR if you are willing to accept this change.

### PR DESCRIPTION
**Pull request by neusdan**
fix PVS-Studio perfomance warnings

closes #377

### CODE REVIEW

**Comment by webmaster128** [comment]
Reviewed, looks good to me.

**Comment by randombit** [comment]
I think

if(s.empty())
 return;

reads fine but `!s.empty()` is much harder to read than `s != ""` especially in complex conditionals. Can you change these to ``s.size() > 0`` which is still awkward but somewhat easier to parse I think.

**Comment by webmaster128** [comment]
Isn't that just a question of what we're used to? "not empty" is maybe easier to read than "not equal to an empty string" and "size greater to zero". I don't think it's worth putting development capacity into this.

**Comment by neusdan** [comment]
I have to agree that `!s.empty()` is harder to read than `s.empty()` but in my opinion `s.size() > 0` is not any better.

I think that it's also a matter of the coding style:

`if(!s.empty())` is harder to read than `if( ! s.empty() )`

But as Simon already said, it's a question of personal preference.

**Comment by randombit** [comment]
I checked and with both GCC and Clang with -O3 s != "" does generate a temporary, vs s.empty() or s.size() which of course do not. So, worth it if slightly ugly.

Really any conditional where this makes it hard to read should probably be rewritten in a cleaner way anyway, so change request retracted.

**Pull request merged**
