### PR TITLE
Documentation changes/additions: hash, symmetric crypto and pubkey

### PR DESCRIPTION
**Pull request by neverhub**
As proposed in https://github.com/randombit/botan/issues/694, we  restructured, updated and added various chapters of/ the Botan manual. In addition some sections are now covered with example code.

Not every addition is 100% complete (some sample code is still missing and will be added in the near future), but we would like to know what you think.

### CODE REVIEW

**Comment by randombit** [comment]
Overall seems fine to me. I'm wondering if the CLI shouldn't be documented in its own section rather than scattering it through the manual, but probably doesn't matter much until at least some of them are documented.

Are you planning further commits on this PR, or would you prefer I merge this now and you opening new PR for future changes?

**Comment by cordney** [comment]
I too think that we should have a separate page on the CLI in the end.

**Comment by neverhub** [comment]
Thanks for the comments.
I am planning to commit the missing code examples and your remarks to this PR.
I will also add a separate CLI section soon.

**Comment by randombit** [comment]
Is this good to merge at this point?

**Comment by neverhub** [comment]
yes it's done so far.

**Pull request merged**
