### PR TITLE
FIX: Wrapping around in CTR-BE(AES-256)

### PR DESCRIPTION
**Pull request by reneme**
It seems that CTR_BE(AES-256) doesn't properly deal with the counter wrapping around.
We stumbled over that due to a lazily written test case in our code base. I'm opening this PR in request for comments and to see if the official CI comes to the same conclusion.

The reference data was generated using pycrypto with the following script and is in agreement with the results from Botan 2.3.0:

```Python
import binascii

from Crypto.Cipher import AES
from Crypto.Util import Counter

#data = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labo"
data = "Viverra accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Viverra justo nec ultrices dui. Faucibus turpis in eu mi bibendum neque egestas. Arcu odio ut sem nulla pharetra. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Donec enim diam vulputate ut pharetra sit. Nec nam aliquam sem et. Eleifend quam adipiscing vitae proin sagittis nisl. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Aenean euismod elementum nisi quis eleifend quam. Dolor sit amet consectetur adipiscing. Vitae turpis massa sed elementum tempus egestas. Pharetra magna ac placerat vestibulum lectus mauris ultrices. In cursus turpis massa tincidunt dui ut. Aenean et tortor at risus. Donec ultrices tincidunt arcu non sodales neque. Ut aliquam purus sit amet luctus venenatis lectus."

key = binascii.unhexlify('1337') * 16
iv  = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
ctr = Counter.new(128, initial_value=iv, allow_wraparound=True)

aes = AES.new(key, AES.MODE_CTR, counter=ctr)
buf = aes.encrypt(data)


print "before"
print binascii.hexlify(data)

print "after"
print binascii.hexlify(buf)

```

Interestingly it seems to fail differently on different platforms:

AppVeyor:
```
Failure 1: CTR-BE(AES-256) producer 'base' unexpected result for encrypt
Produced: 66F72F760BDD02A2B4A6890483B66DF62D0A9284AB54CC32A9F9D29D61DB87FC4C5E016C4B64E84BA36EED545E52E0CE2664D4153B6641B779E89979156EB289F6C5894CA675D56048532025E476A55BDE4311AEA2A145E8000A963C33FD342B6FD5012945CFE8E55C3057FC838E60B43885AEBF70FD5FA8422D6E52324969A1E53BB47BFD139523715D72D79317C02A14684144DAF16AC65D050AA9A4ACAF82B7F2AC31A20592361DC872BEA0B46931C230D45767F9BEC35B8BA616677812EF3FBCD419872B4E7048C91AD93D1B66186EDC069FBD9AC26D0B25785D08E2E9385520812107069C3BE3C34EE9DD272EA56B8D35D9CB6A9496E0B4307AF3BE57ABD858E9D30C9FA447F2B8AB0C031FE21897C6A6D6F8B5453F799E74B09A01AAEA3F6E9CA00A70A1799475E72C40AB0D99529A0F99DE9393AEA7AD5883BCF533B79C9D34254993D67A77B17BA9C1C3F1E3F44C3E0DAAA13F72CA14332E08D739944559F05BDD4F63EB290894D3EA9E4BF4A863B35925E35CC4151E97AEE9935640792D3861E59BBF2B9B5D2709F692DE839E7E8829244AF0F54FA9C42429AD60236DDBBFBD134C40002A02EAE44D77639CF0CEF6B1813BC12ED8B577A46E2B808E5EF8452CD2E5A43F32166DE26EFBAC17CFD6DAF5C477F6D79C81E379E0EAC94E2FE34D191FC986109BB876A73671D4ACF59BF08ABF01D0A845FABB884E90E176B6482B210ED6E6844C87244A27C99DB2D0724A521922FE5BCA54D45A93F4326926C32FE465613FFBF2C69FCC382DE002D5200051A51744F010E16089A6DD8B2A7DCA6DFD6B6E6F4A04220E1A6B86CCD3C5C0B93326C37FA092EF1E531B544697F6316DD8F17EDCB5E0566C364FE814FF5B970A1BAA0D1911C7DA3203B2E6AB2ADD9858F0E31142713709F45C25CFE0E17BECA15ED4908AB3ED8775DA39A9DD83C6A5AED45F27E9B487B5315116589F73A8D54FBE24DC086D50BA0B915DC4F52B17705E82F6E65C8BFB35887BE779567E2257FC32C2AB85D03CB1C784C06651180E96A0B67F3211ACF40BD7FA6D43594E43688DF0E8A4141930E31928D8C3BB1FBFA48C2C65842C304E9EEB767F01561DF90B42EF4DA90A8BDD6DE480C4037230DC6BA0DB3CB6D321A382EC19B85244E6B3C41905D0DACB520D4EAE2E8A6F44A77822DA40621CAE77A4B4F70387B71F5EE2E30CC7563A39059A2C9174FA034E1899E54DCE4ACD82E5968FD8F1
Expected: 66F72F760BDD02A2B4A6890483B66DF62D0A9284AB54CC32A9F9D29D61DB87FC4C5E016C4B64E84BA36EED545E52E0CE2664D4153B6641B779E89979156EB289F6C5894CA675D56048532025E476A55BDE4311AEA2A145E8000A963C33FD342B6FD5012945CFE8E55C3057FC838E60B43885AEBF70FD5FA8422D6E52324969A1E53BB47BFD139523715D72D79317C02A14684144DAF16AC65D050AA9A4ACAF82B7F2AC31A20592361DC872BEA0B46931C230D45767F9BEC35B8BA616677812EF3FBCD419872B4E7048C91AD93D1B66186EDC069FBD9AC26D0B25785D08E2E9385520812107069C3BE3C34EE9DD272EA56B8D35D9CB6A9496E0B4307AF3BE57AB75078A58181934BFF24CCA57EA9D3D1997C6A6D6F8B5453F799E74B09A01AAEA3F6E9CA00A70A1799475E72C40AB0D99529A0F99DE9393AEA7AD5883BCF533B79C9D34254993D67A77B17BA9C1C3F1E3F44C3E0DAAA13F72CA14332E08D739944559F05BDD4F63EB290894D3EA9E4BF4A863B35925E35CC4151E97AEE9935640792D3861E59BBF2B9B5D2709F692DE839E7E8829244AF0F54FA9C42429AD60236DDBBFBD134C40002A02EAE44D77639CF0CEF6B1813BC12ED8B577A46E2B808E5EF8452CD2E5A43F32166DE26EFBAC17CFD6DAF5C477F6D79C81E379E0EAC94E2FE34D191FC986109BB876A73671D4ACF59BF08ABF01D0A845FABB884E90E176293F903675381A8F12E4B5EA39ECCC59D0724A521922FE5BCA54D45A93F4326926C32FE465613FFBF2C69FCC382DE002D5200051A51744F010E16089A6DD8B2A7DCA6DFD6B6E6F4A04220E1A6B86CCD3C5C0B93326C37FA092EF1E531B544697F6316DD8F17EDCB5E0566C364FE814FF5B970A1BAA0D1911C7DA3203B2E6AB2ADD9858F0E31142713709F45C25CFE0E17BECA15ED4908AB3ED8775DA39A9DD83C6A5AED45F27E9B487B5315116589F73A8D54FBE24DC086D50BA0B915DC4F52B17705E82F6E65C8BFB35887BE779567E2257FC32C2AB85D03CB1C784C06651180E96A0B67F3211ACF40BD7FA6D43594E43688DF0E8A4141930E31928D8C3BB1F27CCB6D2B32C0814B5666DD67EC349DDF90B42EF4DA90A8BDD6DE480C4037230DC6BA0DB3CB6D321A382EC19B85244E6B3C41905D0DACB520D4EAE2E8A6F44A77822DA40621CAE77A4B4F70387B71F5EE2E30CC7563A39059A2C9174FA034E1899E54DCE4ACD82E5968FD8F1
XOR Diff: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000AD5F638B148690F800F4615BE982DF010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009F77BB177BEEFC0B5E6391A01E2551EB00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000098683AFED6A82424FBF886A001C21FC00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 (189 bits different)
Note 1: CTR-BE(AES-256) Test #67 CTR-BE(AES-256) failed
```

Travis (gcc - shared)
```
Failure 1: CTR-BE(AES-256) producer 'base' unexpected result for encrypt
Produced: 7CF12B76148F0AF2A6B087518AAA60F77F438FCDB11DDE33ECE397CE6B949AEC4C51107B5662EB1EA72AE1511754EFD33A6A9715242F43F22DFA993D547FBEDD2B2B044B6ECB16DF1DB7FE237C8C172ED14358ACAEB057EF155EC33B76F5752565
Expected: 7CF12B76148F0AF2A6B087518AAA60F77F438FCDB11DDE33ECE397CE6B949AEC4C51107B5662EB1EA72AE1511754EFD33A6A9715242F43F22DFA993D547FBEDDFCDED21F8E6E912D535A2826FF6DE012D14358ACAEB057EF155EC33B76F5752565
XOR Diff: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000D7F5D654E0A587F24EEDD60583E1F73C0000000000000000000000000000000000 (71 bits different)
Failure 2: CTR-BE(AES-256) producer 'base' unexpected result for encrypt
Produced: 66F72F760BDD02A2B4A6890483B66DF62D0A9284AB54CC32A9F9D29D61DB87FC4C5E016C4B64E84BA36EED545E52E0CE2664D4153B6641B779E89979156EB28921305F1846D0529206BEF62067975267DE4311AEA2A145E8000A963C33FD342B6FD5012945CFE8E55C3057FC838E60B43885AEBF70FD5FA8422D6E52324969A1D34848A6F6383E038C08FFB141D226A114684144DAF16AC65D050AA9A4ACAF82B7F2AC31A20592361DC872BEA0B46931C230D45767F9BEC35B8BA616677812EFB74496493D05F8AF214845DD7D1A9E766EDC069FBD9AC26D0B25785D08E2E9385520812107069C3BE3C34EE9DD272EA56B8D35D9CB6A9496E0B4307AF3BE57ABD858E9D30C9FA447F2B8AB0C031FE21897C6A6D6F8B5453F799E74B09A01AAEA3F6E9CA00A70A1799475E72C40AB0D99529A0F99DE9393AEA7AD5883BCF533B702F87103C505D04A8651F96B591E8714F44C3E0DAAA13F72CA14332E08D739944559F05BDD4F63EB290894D3EA9E4BF4A863B35925E35CC4151E97AEE99356404F455D33EE3731C544F3EC8B7D8654D39E7E8829244AF0F54FA9C42429AD60236DDBBFBD134C40002A02EAE44D77639CF0CEF6B1813BC12ED8B577A46E2B808E4BFC92CCFB8E47008C36905A9C253F81CFD6DAF5C477F6D79C81E379E0EAC94E2FE34D191FC986109BB876A73671D4ACF59BF08ABF01D0A845FABB884E90E176B6482B210ED6E6844C87244A27C99DB2D0724A521922FE5BCA54D45A93F4326926C32FE465613FFBF2C69FCC382DE002D5200051A51744F010E16089A6DD8B2A7BF57F2DC9B2CE12BAE657FB58DE47ADC5C0B93326C37FA092EF1E531B544697F6316DD8F17EDCB5E0566C364FE814FF5B970A1BAA0D1911C7DA3203B2E6AB2A9744EFB98C5D0CE6C27DE953230812C67BECA15ED4908AB3ED8775DA39A9DD83C6A5AED45F27E9B487B5315116589F73A8D54FBE24DC086D50BA0B915DC4F52B4B51E5BABBB76CE0B596B351B40AF35D2257FC32C2AB85D03CB1C784C06651180E96A0B67F3211ACF40BD7FA6D43594E43688DF0E8A4141930E31928D8C3BB1FBFA48C2C65842C304E9EEB767F01561DF90B42EF4DA90A8BDD6DE480C4037230DC6BA0DB3CB6D321A382EC19B85244E6B3C41905D0DACB520D4EAE2E8A6F44A7EA76463E8B066CBB7B12D2D16E1FF0FDE2E30CC7563A39059A2C9174FA034E1899E54DCE4ACD82E5968FD8F1
Expected: 66F72F760BDD02A2B4A6890483B66DF62D0A9284AB54CC32A9F9D29D61DB87FC4C5E016C4B64E84BA36EED545E52E0CE2664D4153B6641B779E89979156EB289F6C5894CA675D56048532025E476A55BDE4311AEA2A145E8000A963C33FD342B6FD5012945CFE8E55C3057FC838E60B43885AEBF70FD5FA8422D6E52324969A1E53BB47BFD139523715D72D79317C02A14684144DAF16AC65D050AA9A4ACAF82B7F2AC31A20592361DC872BEA0B46931C230D45767F9BEC35B8BA616677812EF3FBCD419872B4E7048C91AD93D1B66186EDC069FBD9AC26D0B25785D08E2E9385520812107069C3BE3C34EE9DD272EA56B8D35D9CB6A9496E0B4307AF3BE57AB75078A58181934BFF24CCA57EA9D3D1997C6A6D6F8B5453F799E74B09A01AAEA3F6E9CA00A70A1799475E72C40AB0D99529A0F99DE9393AEA7AD5883BCF533B79C9D34254993D67A77B17BA9C1C3F1E3F44C3E0DAAA13F72CA14332E08D739944559F05BDD4F63EB290894D3EA9E4BF4A863B35925E35CC4151E97AEE9935640792D3861E59BBF2B9B5D2709F692DE839E7E8829244AF0F54FA9C42429AD60236DDBBFBD134C40002A02EAE44D77639CF0CEF6B1813BC12ED8B577A46E2B808E5EF8452CD2E5A43F32166DE26EFBAC17CFD6DAF5C477F6D79C81E379E0EAC94E2FE34D191FC986109BB876A73671D4ACF59BF08ABF01D0A845FABB884E90E176293F903675381A8F12E4B5EA39ECCC59D0724A521922FE5BCA54D45A93F4326926C32FE465613FFBF2C69FCC382DE002D5200051A51744F010E16089A6DD8B2A7DCA6DFD6B6E6F4A04220E1A6B86CCD3C5C0B93326C37FA092EF1E531B544697F6316DD8F17EDCB5E0566C364FE814FF5B970A1BAA0D1911C7DA3203B2E6AB2ADD9858F0E31142713709F45C25CFE0E17BECA15ED4908AB3ED8775DA39A9DD83C6A5AED45F27E9B487B5315116589F73A8D54FBE24DC086D50BA0B915DC4F52B17705E82F6E65C8BFB35887BE779567E2257FC32C2AB85D03CB1C784C06651180E96A0B67F3211ACF40BD7FA6D43594E43688DF0E8A4141930E31928D8C3BB1F27CCB6D2B32C0814B5666DD67EC349DDF90B42EF4DA90A8BDD6DE480C4037230DC6BA0DB3CB6D321A382EC19B85244E6B3C41905D0DACB520D4EAE2E8A6F44A77822DA40621CAE77A4B4F70387B71F5EE2E30CC7563A39059A2C9174FA034E1899E54DCE4ACD82E5968FD8F1
XOR Diff: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000D7F5D654E0A587F24EEDD60583E1F73C0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003673FCDD0B2BAB20FD558D66D2C5E68B00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000088F84250BA2EB6DF69815F044001F86E000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000AD5F638B148690F800F4615BE982DF010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009E6545268C960630F1E082C298DD76F7000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000366865520BAC8EEEDFAECB828B148A500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001504D7E0296BE33FBE20FDB8F2DE93960000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009F77BB177BEEFC0B5E6391A01E2551EB000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000063F12D0A2DCA158BEC459E133588B7E0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004ADCB7496F4C4E97F5741D0F06C7F2270000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005C21BB384D51306B4EA33B2A5373A52300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000098683AFED6A82424FBF886A001C21FC000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000092549C7EE91AC2CCDFA625D2E9A8EFA300000000000000000000000000000000000000000000000000000000 (836 bits different)
Note 1: CTR-BE(AES-256) Test #66 CTR-BE(AES-256) failed
Note 2: CTR-BE(AES-256) Test #67 CTR-BE(AES-256) failed
```

### CODE REVIEW

**Comment by webmaster128** [comment]
Random observation: only one test fail on Windows (`CTR-BE(AES-256) Test #67`) and two test fails on Unix (`CTR-BE(AES-256) Test #66`, `CTR-BE(AES-256) Test #67`). Interesting.

**Comment by reneme** [comment]
The issue seems to be in *ctr.cpp* `CTR_BE::add_counter()` which [has been optimized](https://github.com/randombit/botan/pull/1262/files) for 2.4.0. If I comment-out all `if`-branches except the default `else` case, it works fine.

**Comment by reneme** [comment]
Printing the counters and the XOR-Diff

```
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF   00000000000000000000000000000000
00000000000000000000000000000000   00000000000000000000000000000000   00000000000000000000000000000000
00000000000000000000000000000001   00000000000000000000000000000001   00000000000000000000000000000000
00000000000000000000000000000002   00000000000000000000000000000002   00000000000000000000000000000000
00000000000000000000000000000003   00000000000000000000000000000003   00000000000000000000000000000000
00000000000000000000000000000004   00000000000000000000000000000004   00000000000000000000000000000000
00000000000000000000000000000005   00000000000000000000000000000005   00000000000000000000000000000000
00000000000000000000000000000006   00000000000000000000000000000006   00000000000000000000000000000000
00000000000000000000000000000007   00000000000000000000000000000007   00000000000000000000000000000000
00000000000000000000000000000008   00000000000000000000000000000008   00000000000000000000000000000000
00000000000000000000000000000009   00000000000000000000000000000009   00000000000000000000000000000000
0000000000000000000000000000000A   0000000000000000000000000000000A   00000000000000000000000000000000
0000000000000000000000000000000B   0000000000000000000000000000000B   00000000000000000000000000000000
0000000000000000000000000000000C   0000000000000000000000000000000C   00000000000000000000000000000000
0000000000000000000000000000000D   0000000000000000000000000000000D   00000000000000000000000000000000
0000000000000000000000000000000E   0000000000000000000000000000000E   00000000000000000000000000000000
FFFFFFFFFFFFFFFF0000000000000010   0000000000000000000000000000000F   AD5F638B148690F800F4615BE982DF01
00000000000000000000000000000010   00000000000000000000000000000010   00000000000000000000000000000000
00000000000000000000000000000011   00000000000000000000000000000011   00000000000000000000000000000000
00000000000000000000000000000012   00000000000000000000000000000012   00000000000000000000000000000000
00000000000000000000000000000013   00000000000000000000000000000013   00000000000000000000000000000000
00000000000000000000000000000014   00000000000000000000000000000014   00000000000000000000000000000000
00000000000000000000000000000015   00000000000000000000000000000015   00000000000000000000000000000000
00000000000000000000000000000016   00000000000000000000000000000016   00000000000000000000000000000000
00000000000000000000000000000017   00000000000000000000000000000017   00000000000000000000000000000000
00000000000000000000000000000018   00000000000000000000000000000018   00000000000000000000000000000000
00000000000000000000000000000019   00000000000000000000000000000019   00000000000000000000000000000000
0000000000000000000000000000001A   0000000000000000000000000000001A   00000000000000000000000000000000
0000000000000000000000000000001B   0000000000000000000000000000001B   00000000000000000000000000000000
0000000000000000000000000000001C   0000000000000000000000000000001C   00000000000000000000000000000000
0000000000000000000000000000001D   0000000000000000000000000000001D   00000000000000000000000000000000
0000000000000000000000000000001E   0000000000000000000000000000001E   00000000000000000000000000000000
FFFFFFFFFFFFFFFF0000000000000020   0000000000000000000000000000001F   9F77BB177BEEFC0B5E6391A01E2551EB
00000000000000000000000000000020   00000000000000000000000000000020   00000000000000000000000000000000
00000000000000000000000000000021   00000000000000000000000000000021   00000000000000000000000000000000
00000000000000000000000000000022   00000000000000000000000000000022   00000000000000000000000000000000
00000000000000000000000000000023   00000000000000000000000000000023   00000000000000000000000000000000
00000000000000000000000000000024   00000000000000000000000000000024   00000000000000000000000000000000
00000000000000000000000000000025   00000000000000000000000000000025   00000000000000000000000000000000
00000000000000000000000000000026   00000000000000000000000000000026   00000000000000000000000000000000
00000000000000000000000000000027   00000000000000000000000000000027   00000000000000000000000000000000
00000000000000000000000000000028   00000000000000000000000000000028   00000000000000000000000000000000
00000000000000000000000000000029   00000000000000000000000000000029   00000000000000000000000000000000
0000000000000000000000000000002A   0000000000000000000000000000002A   00000000000000000000000000000000
0000000000000000000000000000002B   0000000000000000000000000000002B   00000000000000000000000000000000
0000000000000000000000000000002C   0000000000000000000000000000002C   00000000000000000000000000000000
0000000000000000000000000000002D   0000000000000000000000000000002D   00000000000000000000000000000000
0000000000000000000000000000002E   0000000000000000000000000000002E   00000000000000000000000000000000
FFFFFFFFFFFFFFFF0000000000000030   0000000000000000000000000000002F   98683AFED6A82424FBF886A001C21FC0
00000000000000000000000000000030   00000000000000000000000000000030   00000000000000000000000000000000
00000000000000000000000000000031   00000000000000000000000000000031   00000000000000000000000000000000
00000000000000000000000000000032   00000000000000000000000000000032   00000000000000000000000000000000
00000000000000000000000000000033   00000000000000000000000000000033   00000000000000000000000000000000
00000000000000000000000000000034   00000000000000000000000000000034   00000000000000000000000000000000
00000000000000000000000000000035   00000000000000000000000000000035   000000000000000000000000
00000000000000000000000000000036   00000000000000000000000000000036
00000000000000000000000000000037   00000000000000000000000000000037
00000000000000000000000000000038   00000000000000000000000000000038
00000000000000000000000000000039   00000000000000000000000000000039
0000000000000000000000000000003A   0000000000000000000000000000003A
0000000000000000000000000000003B   0000000000000000000000000000003B
0000000000000000000000000000003C   0000000000000000000000000000003C
0000000000000000000000000000003D   0000000000000000000000000000003D
0000000000000000000000000000003E   0000000000000000000000000000003E
```

**Comment by reneme** [comment]
Adding the carry-bit to the right half-counter fixes the problem. Wondering about the other two `if`cases now...

**Comment by randombit** [comment]
Nice find, glad you happened to catch this before the release.

In #1262 I specifically added overflow tests for ctr widths of 4,5,6 bytes, but not larger widths. :/

**Comment by randombit** [comment]
Added at test for 8 byte wide counters generated with PyCrypto, works fine. Looks like only 16-byte counters were affected - unfortunately that's the common case!

**Pull request merged**
