### PR TITLE
OCSP softfail revocation check

### PR DESCRIPTION
**Pull request by souch**
Here is a patch to have softfail OCSP revocation check:
- if the ocsp URL is empty or there is an exception in the POST_sync ocsp request, the status is set to OCSP_RESPONSE_GOOD and a warning is added to the status codes.
- it could be perhaps better to softfail in the POST_sync ocsp request only if the connection to the server fails (i.e.: do not softfail if connect ok but errors when reading data) ?
- to make the fewest modification possible, I added a special constructor to OCSP::Response that returns a specified status_code.
- note: like you said in the issue #1458, now, to have a softfail check one must use `Path_Validation_Result::successful_validation(),` to have a hardfail check one must call `Path_Validation_Result::no_warnings()` in addition
- if you think this pull request is ok, I can add a test.

### CODE REVIEW

**Comment by randombit** [comment]
This seems ok. One thing I don't like so much is the addition of m_return_status to indicate that m_status_code is in use. It seems like instead you could check if `m_responses.empty()`, and if so return the "dummy" value. The only situation where this would be a problem is if we received a completely empty OCSP response from the server. That could be handled by pre-initializing `m_status_code` in all cases (currently it is left undefined unless the special constructor is used). `OCSP_RESPONSE_INVALID` seems like the correct default value.

Also the name of `m_return_status` should make it clear this is a faked up response code not associated with an actual response (just to avoid confusion for future readers). `m_dummy_response_status` or something like that.

**Comment by randombit** [comment]
Changes look good. However on a final pass I do not understand this

```
+            else if(ocsp_signature_status == Certificate_Status_Code::OSCP_NO_REVOCATION_URL ||
+                    ocsp_signature_status == Certificate_Status_Code::OSCP_SERVER_NOT_AVAILABLE)
+               {
+               status.insert(ocsp_signature_status);
+               // softfail
+               status.insert(Certificate_Status_Code::OCSP_RESPONSE_GOOD); 
+               }
```

Specifically, I don't think we want to insert OCSP_RESPONSE_GOOD in there. That code means (quoting the to_string text) "OCSP response accepted as affirming unrevoked status for certificate" which is not at all what we want to claim, if the OCSP server was not available. I think instead you should just insert the warning status. Then certificate verification will still succeed, but not include the OCSP_RESPONSE_GOOD status.

**Comment by souch** [comment]
I did not like the insert of `OCSP_RESPONSE_GOOD` too.
But, if I do not insert `OCSP_RESPONSE_GOOD`, the func `merge_revocation_status` will insert `NO_REVOCATION_DATA` which is an error status, then `Path_Validation_Result::successful_validation()` will return false.

**Comment by souch** [comment]
Or I modify `merge_revocation_status` instead, e.g.:
```
if(code == Certificate_Status_Code::OCSP_RESPONSE_GOOD ||
   code == Certificate_Status_Code::OSCP_NO_REVOCATION_URL ||
   code == Certificate_Status_Code::OSCP_SERVER_NOT_AVAILABLE)
   {
   had_ocsp = true;
   }```

**Comment by souch** [comment]
I am preparing a new pull request "ocsp_softfail_v2" that will, hopefully, take your remarks into account.

**Comment by souch** [comment]
Moved to pull request  #1470 .

**Pull request closed without merging**
