### PR TITLE
FIX: arm64 amalgamations + better CI coverage

### LINKED ISSUE #3927: Build failure, 3.3.0 amalgamation arm64
When building using clang 16.0.6, on Ubuntu arm64, I found that I had to modify:
```
src/lib/hash/sha2_64/sha2_64_armv8/sha2_64_armv8.cpp
```
to specify `BOTAN_FUNC_ISA("+crypto,sha3")`, instead of just `"+crypto"`, as without doing so, the compilation failed with errors of the format:
```
botan_all.cpp:88261:30: error: always_inline function 'vsha512su0q_u64' requires target feature 'sha3', but would be inlined into function 'compress_digest_armv8' that is compiled without support for 'sha3'
```
Excessive compiler spew omitted for brevity; many such errors.

Unlikely to be an optimal solution, but it did resolve the issue for me.

### PR DESCRIPTION
**Pull request by reneme**
This continues the work @lieser started in #3780. It aims to fix #3927 and #3774. It also incorporates #3930.

Along with fixes to the relevant `BOTAN_FUNC_ISA()` annotations, this adds CI targets for amalgamation builds on arm64 (using GCC) and Android NDK arm64 (using clang). Also, this adds builds on the `macos-14` runner [released a month ago](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/), that is based on Apple Silicon, i.e. arm64 😅. 

**Note:** This also fixes an issue in the Python wrapper, where the `ffi_api()` declaration failed to explicitly specify a `c_int` buffer length parameter. On Apple silicon that resulted in this parameter being `0` on the C/C++ side. Not entirely sure how that ever worked on all other platforms we test in CI.

@randombit I'm somewhat worried that these inline ISA-annotations aren't necessarily in sync with whatever is defined in the `src/build-data/cc/*.txt` files. Currently, for arm64 the definitions are as such:

clang.txt
```
arm64:armv8crypto -> "-march=armv8+crypto"
arm64:armv8sha512 -> "-march=armv8.2-a+sha3"
```

gcc.txt
```
arm64:armv8crypto -> ""
arm64:armv8sm3 -> "-march=armv8.2-a+sm4"
arm64:armv8sm4 -> "-march=armv8.2-a+sm4"
arm64:armv8sha512 -> "-march=armv8.2-a+sha3"
arm64:armv8sha3 -> "-march=armv8.2-a+sha3"
```

... i.e. `clang.txt` doesn't even define all of them. I'm guessing that the inline annotations using `BOTAN_FUNC_ISA()` are saving the day for those, no?

### CODE REVIEW

**Comment by reneme** [comment]
Rebased after merging #3932

**Review by randombit — APPROVED** [review]
I agree things are not necessarily in sync with the info files. I also don’t like the repetition of having these magic (compiler-specific, sometimes undocumented) strings everywhere - ideally we’d have a header that encapsulates this like we do for the SIMD API annotations. (No need to do this here.)

Change itself lgtm.

**Comment by randombit** [comment]
Good to merge? Not sure if more was going to happen here.

**Comment by reneme** [comment]
Should be fine to merge. I didn't plan to address the discussed ISA flag duplication here.

**Pull request merged**
