### PR TITLE
RdRand and RdSeed logic changes

### PR DESCRIPTION
**Pull request by neusdan**
I like to hear your opinion on the following changes.

For RdRand it is [guaranteed](https://software.intel.com/en-us/articles/intel-digital-random-number-generator-drng-library-implementation-and-uses) to generate a random number within 10 retries. So i changed the logic to perform at max 10 retries. Additionally i want to be able to configure how often RdRand and RdSeed is polled.

Unfortunately for RdSeed there are no guarantees as to how often a thread should retry the instruction. So i made the number of retries also configurable.

### CODE REVIEW

**Comment by neusdan** [comment]
For RdSeed i also like to have a 'poll until sucessfull' option.

**Comment by randombit** [comment]
I definitely wouldn't want to rely on the less than 10 tries bound in the sense of failing with an exception (which would abort the entire poll and then propagate to the calling application). It may be the design limit for current silicon but it doesn't seem wise to trust that will always be the bound going forward, or that some unanticipated aging or environmental effect won't cause  existing hardware to behave differently in this regard in some circumstance.

**Comment by randombit** [comment]
Style things - no spaces around if(), for() etc, use snake_case for all plain functions, and if as here a function is private and static it should probably be an anonymous namespace function instead.

**Comment by neusdan** [comment]
Made the changes. But i'm not completely happy that the user is not somehow informed when the poll is failing.

**Comment by randombit** [comment]
Currently this logic filters out any 0x00000000 outputs from RDRAND since these are indistinguishable from the error case. I think this could be most easily avoided by moving the logic back into poll, then `if(1 == cf) { accum.add(...) }`

I do see your reasoning wrt to wanting to inform the user the poll failed. But that does contradict the current contract of poll which is "do your best, don't call accum if you have nothing to say". Maybe there should be a second interface here

**Comment by mouse07410** [comment]
> But i'm not completely happy that the user is not somehow informed when the poll is failing.

+1

> Maybe there should be a second interface here

This looks the best to me. Because RDSEED *does* differ from RDRAND.

**Comment by neusdan** [comment]
moved logic back into poll()

**Comment by neusdan** [comment]
Can we maybe create an issue for the second interface and integrate this as it is? or is there still something wrong?

**Comment by randombit** [comment]
LGTM, merged. Thanks

**Pull request merged**
