### PR TITLE
Repair debug config

### PR DESCRIPTION
**Pull request by webmaster128**
In order to allow proper debug builds, the build system must be more flexible at some points. Some changes needed are:

General

* Rename template variable for C++ compiler `%{cc}` -> `%{cxx}`
* Rename `so_link_flags` to `so_link_commands`

GCC

* Use `-O0` for GCC debugging

MSVC

* Use correct STL version (debug or release)
* Use linker `link`
* Use `/bigobj` to allow compiling full amalgamation
* Use `/FS` to allow writing debug symbols with parallel compile jobs
* Set `/DEBUG` for debug compilation; Remove `/DDEBUG` which did just add a random define

Linux

* Move RPATH setting from `./configure.py` to compiler settings `gcc.txt` and `clang.txt`

This is work in progress that needs special CI care. Thus the PR. I don't think this will make it into 1.11.18.

### CODE REVIEW

**Comment by cdesjardins** [comment]
Kind of related to this... If I were to make yet another request, it would be to also allow the user to select a static runtime on windows. /MT and /MTd rather than /MD and /MDd... Currently I run sed on the generated makefile to accomplish this.

**Comment by webmaster128** [comment]
@cdesjardins Thanks for your feedback! That is definitely related and worth including. Could you tell me why you prefer /MT over /MD? I am not an expert in this MSVC field and just curious.

**Comment by cdesjardins** [comment]
I like the MT options because then you do not have to force the end users to install the msvs redistributable package. You can just ship an executable with minimal external dependencies, and it should just run. I know there are some advantages to using a dynamic runtime (and in fact dynamic everything), but I don't think it really matters for my application, pure convenience is more important.

**Comment by webmaster128** [comment]
@cdesjardins Did you know that you can edit `botan/src/build-data/cc/msvc.txt` to achieve that (at the end of the file)? That way your change should survive multiple `./configure.py` calls. Could you test that please? Because if editing the `msvc.txt` by hand works, it should be easy to allow the user to override the setting via the configure script.

**Comment by cdesjardins** [comment]
Indeed a quick change to msvc.txt:

    all       -> "/MT"
    all-debug -> "/MTd"

causes the makefile to link with the static runtime:

    CXX            = cl /MTd

Both debug and release work.

**Comment by webmaster128** [comment]
Great! Then I'll leave it out of this commit because it is already very large. Could you open a ticket to make `mach_abi_linking` configurable?

**Pull request merged**
