### PR TITLE
Remove use of buffer_insert from filters, MACs, stream ciphers

### PR DESCRIPTION
**Pull request by randombit**

### CODE REVIEW

**Review by reneme — APPROVED** [review]
Generally this looks fine to me. Though, I feel, we could utilize `AlignmentBuffer<>` for some of those places.

**Comment by randombit** [comment]
> Generally this looks fine to me. Though, I feel, we could utilize AlignmentBuffer<> for some of those places.

I do not disagree! This PR sequence is just about removing `buffer_insert` and a few of the other relatively obscure functions from `mem_ops.h` to make further refactorings there easier.

**Comment by reneme** [comment]
Whoops! 😨 I took the liberty to apply `AlignmentBuffer<>` to `Poly1305` to verify my own claim. Feel free to purge my commit from from this PR, if we want to keep things clean.

**Comment by randombit** [comment]
No worries, that is even better. I was just going for minimum possible refactoring at this stage.

**Pull request merged**
