### PR TITLE
FIX: Alert handling in ASIO stream and HTTP Server

### PR DESCRIPTION
**Pull request by reneme**
Turns out that #3778 seems to be caused by a long-standing bug in the ASIO stream wrapper. Consider a client sending a ClientHello that a server has to reject with a lack of compatible ciphersuites. Botan's TLS server would signal that with a `TLS_Exception(Alert::HandshakeFailure, "...")`.

The TLS stream wrapper (as the server) didn't properly handle that (as in: send a fatal alert message, terminate the connection and report a reasonable error code back to ASIO). Instead it just closed the connection immediately.
Likewise, when receiving a fatal alert message from a peer, the ASIO stream wrapper didn't report that back to the application as an error code but also simply terminated the connection.

This surfaced because the TLS Anvil nightly test is based on `./botan tls_http_server`, which is now based on the ASIO stream: #3763. Here we add proper handling for both cases and a suitable regression test.

Fortunately, the buggy behavior was arguable "okayish": The connection was hard-reset. Just, the application and the peer didn't get a proper error message. TLS-Anvil isn't satisfied with just that, though.

@FAlbertDev Let's verify tomorrow that this helps with #3778.

### CODE REVIEW

**Comment by reneme** [comment]
Force pushed to explain it again for MSVC. It produced warnings for unreachable code that were false positives. 🤷‍♂️

**Comment by FAlbertDev** [comment]
Nice! TLS-Anvil is not yet fully satisfied but many failing tests were fixed by these changes. Before we had 62 failing tests, now we only have 8. We'll look into these as well.

**Comment by reneme** [comment]
https://github.com/randombit/botan/pull/3795/commits/9a21fe31598dec7afa3f0798fe2ba06db68e7da1 contains another fix. On application level (`./botan tls_http_server`) this time. We need to make sure that the server always calls `.async_shutdown()`, even if a TLS exception is thrown. This will flush outstanding data from the server's write buffer: e.g. a TLS alert message emitted by the stream during `async_read()`.

**Review by randombit — APPROVED** [review]
:+1:

**Pull request merged**
