### PR TITLE
Compatibility fixes for Python 2.6.

### PR DESCRIPTION
**Pull request by emilymaier**
I understand that 2.6 isn't officially supported for the configure.py script, but I was able to get it working on my 2.6 system with these tiny changes.

### CODE REVIEW

**Comment by randombit** [comment]
Thanks. This looks reasonable but I'll need to confirm it doesn't impact 2.7 or 3.x

**Comment by webmaster128** [comment]
May I ask which system you're using that at the same time has a supported compiler but no Python 2.7+? I recall that no one complained when we tasked about dropping Python 2.6 support like half a year ago.

**Comment by emilymaier** [comment]
I'm using CentOS 6.7 with the Red Hat devtools installed to get gcc 4.8

**Comment by randombit** [comment]
With your change everything still works for me with 2.7, 3.5 and PyPy 4, and this patch came in handy just the other day when I was compiling on one of the GCC cfarm machines which had 2.6. Since it's so minimal to workaround it seems worth keeping given RHEL6 is still in active support... (I too know the pain of compiling C++11 onto ancient RHEL/etc systems using upgraded compilers, with everything else still out of date). Thanks for the patch.

**Pull request closed without merging**
