### PR TITLE
Add Pipe::append_filter

### PR DESCRIPTION
**Pull request by randombit**
Similar to append but it only allows modification before start_msg. See GH #1306

### CODE REVIEW

**Comment by matejk** [comment]
append() and prepend() were made deprecated, however only append_filter() was added.

Is prepend_filter() missing also or was not implemented intentionally?

**Comment by randombit** [comment]
Hm, not necessarily intentionally - but I assumed that if we are limiting modification of a Pipe to prior to message processing, then appending is sufficient. Is there some situation I'm not thinking of, where this would be useful?

**Comment by matejk** [comment]
Our software that uses Botan to do processing on the files in certain order, which is not necessarily the same for all objects: compressions, encryptions etc.

The steps done when archiving data are saved with the object.

When getting the data back from the archive, these steps have to be done in reverse order. prepend() is very handy to create proper pipe. Of course before calling any start_msg().

**Comment by randombit** [comment]
Makes sense. I'll add a similar prepend operation for 2.5.0

**Comment by matejk** [comment]
Thank you very much.

**Pull request merged**
