### PR TITLE
Add Blake2b hash function

### PR DESCRIPTION
**Pull request by cynecx**
randombit/botan#390
Please review.

### CODE REVIEW

**Comment by randombit** [comment]
Thanks! I haven't had time to review this too carefully yet but should in the next few days. One quick thing I noticed, please use `rotate_right` (from utils/rotate.h) instead of the `rotw64` macro.

**Comment by cynecx** [comment]
No problem. Please review the last commit.

**Comment by randombit** [comment]
I reindented to match the rest of the code but besides that looks good, thank you!

**Comment by webmaster128** [comment]
Is there any reason why the "abc" test vector was added for BLAKE2b-512 only (13a3afa4c2f49c8799f87a3b54d317761e4f1a14)?

**Comment by randombit** [comment]
I assume it's because that's the single Blake2b test vector in RFC 7693

**Pull request merged**
