### PR TITLE
Pylint compliance for cmake, module resolution and amalgamtion

### PR DESCRIPTION
**Pull request by webmaster128**
This is a refactoring of the topics mentioned.

I confirmed that the generated amalgamation does not differ from current master using our own project (custom modules list, 12 different target platforms, botan_all_aesni.cpp used on some systems).

Apart from the code refactorings, there are minor improvements in the configuration results:
* include guard name is added to #endif (e.g. `#endif` -> `#endif // BOTAN_AMALGAMATION_H__`)
* botan_all_internal.h now also gets a license banner
* source files list is now sorted for convenience in CMakeLists.txt

After this, we only need those 3 things for green lint light:
1. Refactoring of configure's main()
2. Cleanup botan2.py
3. Check Python 2 pylint
All of those 3 are minor tasks compared to this current PR.

### CODE REVIEW

**Comment by randombit** [comment]
Awesome, will review this over the weekend.

**Comment by randombit** [comment]
Only problem I see so far is the verbose logging in `_resolve_dependencies` is just too verbose, and repeats itself a lot.

```
  DEBUG: Searching for base...
  DEBUG: Already loaded.
  DEBUG: Searching for base...
  DEBUG: Already loaded.
  DEBUG: Searching for hash...
  DEBUG: Already loaded.
  DEBUG: Resolving dependencies of block...
  DEBUG: Searching for base...
  DEBUG: Already loaded.
  DEBUG: Resolving dependencies of aont...
  DEBUG: Searching for ctr...
  DEBUG: Already loaded.
  DEBUG: Searching for rng...
  DEBUG: Already loaded.
  DEBUG: Searching for filters...
  DEBUG: Already loaded.
  DEBUG: Searching for base...
  DEBUG: Already loaded.
...
```

I'm not sure this level of logging helps anyone, except perhaps you while you were debugging your changes :)

I'd be ok with either removing the logs entirely (also simplifying `_resolve_dependencies` a bit by removing `level` argument), reducing the log output to just the 'informative bits' (say something like

```
diff --git a/configure.py b/configure.py
index b9b731daa..d8b697de2 100755
--- a/configure.py
+++ b/configure.py
@@ -2046,25 +2046,26 @@ class ModulesChooser(object):

     def _resolve_dependencies(self, modname, level=0):
         indent = "    "*level
-        logging.debug(indent + "Resolving dependencies of %s..." % modname)
+
+        dependencies = self._modules[modname].dependencies()
+
+        logging.debug(indent + "Resolving dependencies of %s [%s]" %
+                      (modname, ' '.join(dependencies)))

         for dependency in dependencies:
             dependency_choices = set(dependency.split('|'))

-            logging.debug(indent + "Searching for %s..." % dependency)
-
             dependency_met = False
             new_loaded_mod = None

             # Prefer what we already loaded
             if not set(dependency_choices).isdisjoint(self._to_load):
-                logging.debug(indent + "Already loaded.")
                 dependency_met = True
             else:
                 possible_mods = dependency_choices.intersection(self._maybe_dep)
                 if possible_mods:
                     new_loaded_mod = possible_mods.pop()
-                    logging.debug(indent + "Adding %s..." % new_loaded_mod)
+                    logging.debug(indent + "Adding module '%s' required by '%s'" % (new_loaded_mod, modname))
                     dependency_met = True
```

or else leaving the logs but guarding them by some additional command line flag (`--trace` or `--really-verbose` or whatever) so when we ask someone who is having problems with the build to post the output of `configure.py --verbose` it's not 1200+ lines (!). Leaving `--trace` logging for developers who are working on changes to configure, and are ok with a log firehose.

**Comment by webmaster128** [comment]
Ahh, damn, I knew about this issue but then forgot about it after I was done and did not use debug anymore.

I think I'll remove the logging code entirely as this is mostly development code. We can add it again when there are issues with dependency resolution.

**Comment by randombit** [comment]
Sounds good, thanks

**Comment by webmaster128** [comment]
okay, done

**Pull request merged**
