### PR TITLE
Set the MSVC runtime library appropriately depending on flags

### PR DESCRIPTION
**Pull request by randombit**
Fixes GH #210

### CODE REVIEW

**Comment by randombit** [comment]
I don't use Windows/MSVC but it seems like this resolves #210 by picking /MT(d) if `--disable-shared` is used and /MD(d) if building the DLL. Any comments @webmaster128 @neusdan @cdesjardins

**Comment by webmaster128** [comment]
I don't think static/dynamic STL linking should be tied to how Botan is built. I think those are orthogonal.

 . | Botan dynamic | Botan static
------------ | -------------| -------------
STL dynamic | 1 | 2
STL static | 3 | 4

1 and 2 are supported at the moment, are valid and work. At Kullo we use 2 because we want Botan to be static but need dynamic STL because we also link Qt dynamically and don't want dynamic and static STL in the same application.

I don't see how 3. helps anyone but I am not an expert here. 4 (all static) is nice to reduce dependencies and I guess this is what users in #210 and #294 want.

This PR changes choices in from 1+2 to 1+4. But I think we should support all four.

**Comment by randombit** [comment]
OK makes sense I will rework this PR. Thanks

**Comment by webmaster128** [comment]
Looks good to me. However, I don't see a reason so change default behaviour for static build here. Static Botan with dynamic STL is probably a good choice for many applications and changing the defaults from case 2 to 4 breaks builds in ways that may be hard to debug for no real benefit.

**Pull request merged**
