### PR TITLE
Fix a crash in System_RNG on macOS 10.15

### PR DESCRIPTION
**Pull request by randombit**
[Potential fix, need @mouse07410 or someone else with access to macOS 10.15 to confirm this works]

See #2268

### CODE REVIEW

**Comment by reneme** [comment]
LGTM. Though, I cannot reproduce the crash on macOS 10.15.3 with or without this patch. I used the following test program that might be too naive?:

```
#include <botan/system_rng.h>
#include <botan/hex.h>

#include <iostream>

int main() {
    uint8_t buffer[32] = {0};

    auto &rng = Botan::system_rng();

    std::cout << rng.name() << std::endl;
    std::cout << Botan::hex_encode(buffer, 32) << std::endl;

    rng.randomize(buffer, 0);

    std::cout << Botan::hex_encode(buffer, 32) << std::endl;

    return 0;
}
```

**Comment by randombit** [comment]
@reneme My understanding is your prog should be triggering this. Possibly it is only a bug in certain patch levels of 10.15? Another repro would be

```
#include <stdlib.h>

int main() {
  unsigned char buf[32] = { 0 };
  arc4random_buf(buf, 0);
  return 0; // didn't crash ...
}
```

Also are you sure `System_RNG` is using arc4random in your build? It should be unless configured with an explicit disable of ``--without-os-features=arc4random`` - you can confirm by looking for `BOTAN_TARGET_OS_HAS_ARC4RANDOM` in ``build.h``

**Comment by randombit** [comment]
In #2268 @mouse07410 also reports using Catalina 10.15.3 so wtf? Why does it only reproduce on some machines.

**Comment by reneme** [comment]
I wasn’t sure about arc4random, hence the `rng.name()` print to confirm. Also a printf in `System_RNG_Impl::randomize()` got triggered. So yeah, I’m pretty sure that I went into the

**Comment by mouse07410** [comment]
First, the test-code was
```c++
std::vector<uint8_t> out_buf(i);
```
Is that the same as 
```c++
uint8_t buffer[32] = {0};
```
I think not.

@reneme does `./botan-test system_rng` work for you? Are you on Xcode-11.3.1?

Finally, even if the #2268 problem doesn't manifest on *all* the Macs, this PR fixes the problem, and doesn't seem to cause any hurt elsewhere. Let's merge (I've merged it in my fork regardless).

**Comment by randombit** [comment]
Oh good point @mouse07410, the problem is likely specifically `arc4random_buf(nullptr, 0)` crashing.

Anyway agree fix is simple and seems to resolve the issue. Just waiting for CI to merge.

**Comment by randombit** [comment]
Ok CI has already finished just isn't reporting as such probably because of the outage GH had earlier today.

**Comment by randombit** [comment]
@reneme Just for curiosity, can you check `arc4random_buf(nullptr, 0)` on your machine?

**Comment by reneme** [comment]
@randombit @mouse07410 Will do tomorrow morning.

**Comment by reneme** [comment]
This:
```C++
#include <stdlib.h>

int main() {
    arc4random_buf(nullptr, 0);
    return 0;
}
```
comes back with a crash like that:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff6ed4d7fa libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff6ee0abc1 libsystem_pthread.dylib`pthread_kill + 432
    frame #2: 0x00007fff6ecd4a1c libsystem_c.dylib`abort + 120
    frame #3: 0x00007fff6ea44d78 libcorecrypto.dylib`cc_abort + 9
    frame #4: 0x00007fff6ea6dcdb libcorecrypto.dylib`cc_try_abort + 9
    frame #5: 0x00007fff6e9fe92c libcorecrypto.dylib`ccrng_cryptographic_generate + 538
    frame #6: 0x0000000100000f8e spike`main + 30
    frame #7: 0x00007fff6ec067fd libdyld.dylib`start + 1
```

**Comment by reneme** [comment]
I'm on macOS 10.15.3 and Xcode 11.3.1.

Both `./botan-test system_rng` and `./botan rng 0` crash similarly. If I adapt my test program posted earlier to use `std::vector<uint8_t> buffer(0)` I see the same stack trace. Obviously all of those WITHOUT applying the patch in this pull request. With the patch all of them work fine.

Though, I guess the actual culprit is the `nullptr` parameter rather than `len` being zero, right? Shouldn't we check that instead?

**Comment by randombit** [comment]
@reneme The specific condition we are checking for is nullptr/0 because that is generally considered a valid span to pass to the library. Whereas, passing say nullptr/1 should crash, or maybe shouldn't, but in any case right now that is status quo and adding null pointer checks everywhere would be a lot of checks for unclear value.

My comment about the problem being len == 0 is incorrect so I will fix that.

**Comment by mouse07410** [comment]
> My comment about the problem being `len == 0` is incorrect so I will fix that.

IMHO, it would be good to check for *both* `nullptr` *and* `len == 0`, as in either case one shouldn't call `arc4random...()`.

**Pull request merged**
