### PR TITLE
Remove unused enum

### PR DESCRIPTION
**Pull request by raumod**
The block_cipher.h file has an enum just after the definition of the class "Block_Cipher_Fixed_Params". Doing a complicated cmake setup, the amalgamated version returned multiple errors at compilation:

``` 
generated/botan/botan_all.h:2506:14: error: expected identifier before ‘(’ token
2506 |       enum { BLOCK_SIZE = BS };
         |              ^~~~~~~~~~
generated/botan/botan_all.h:2506:12: note: to match this ‘{’
2506 |       enum { BLOCK_SIZE = BS };
         |            ^
generated/botan/botan_all.h:2506:14: error: expected unqualified-id before numeric constant
2506 |       enum { BLOCK_SIZE = BS };
         |              ^~~~~~~~~~
generated/botan/botan_all.h:2507:39: error: virt-specifiers in ‘block_size’ not allowed outside a class definition
2507 |       size_t block_size() const final override { return BS; }
         |                                       ^~~~~~~~
generated/botan/botan_all.h:2507:39: error: non-member function ‘std::size_t Botan::block_size()’ cannot have cv-qualifier
generated/botan/botan_all.h: In function ‘std::size_t Botan::block_size()’:
generated/botan/botan_all.h:2507:57: error: ‘BS’ was not declared in this scope; did you mean ‘BS0’?
2507 |       size_t block_size() const final override { return BS; }
         |                                                         ^~
         |                                                         BS0
```
Without the enum definition, other errors disappear as well

This is the reason behind this change.

### CODE REVIEW

**Comment by hrantzsch** [comment]
Thanks for the PR. Unfortunately the enum cannot simply be removed, as it is required for other configurations. Can you share how you invoked `configure.py`?

**Comment by raumod** [comment]
Thanks for your reply. The configuration I used was the following:

```
python3 configure.py --cc=gcc --cc-min-version=14.0 --amalgamation --minimized-build --enable-modules=tls,x509,certstor_system,certstor_flatfile,auto_rng,system_rng --disable-shared-library
```

I noticed this error was present wen using the "block" module, however it I would remove it, it would also take down many other cryptography systems that are required.

As a side note, we are using cmake to compile our project, if we use the hidden cmake creation and link the project, it works, however the enum problems happened only in the amalgamated version.

If possible, could you explain where the enum is used in other modules??

**Comment by raumod** [comment]
For reference, this is part of the automated Makefile document created:
```

# This makefile was generated using 'configure.py --cc=gcc --cc-min-version=14.0 --amalgamation --minimized-build --enable-modules=tls,x509,certstor_system,certstor_flatfile,auto_rng,system_rng --disable-shared-library'

# Paths to relevant programs

CXX            = g++
LINKER         = $(CXX)
AR             = ar
AR_OPTIONS     = crs
PYTHON_EXE     = /usr/bin/python3

# Compiler Flags

ABI_FLAGS      =  -fstack-protector -m64 -pthread
LANG_FLAGS     = -std=c++11 -D_REENTRANT 
CXXFLAGS       = -O3 -DBOTAN_IS_BEING_BUILT
WARN_FLAGS     = -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor
LIB_FLAGS      = 
LDFLAGS        = 

EXE_LINK_CMD   = $(LINKER)

LIB_LINKS_TO        =  
BUILD_DIR_LINK_PATH = -L.
EXE_LINKS_TO        = -lbotan-2 $(LIB_LINKS_TO) 

BUILD_FLAGS    = $(ABI_FLAGS) $(LANG_FLAGS) $(CXXFLAGS) $(WARN_FLAGS)

SCRIPTS_DIR    = src/scripts
INSTALLED_LIB_DIR = /usr/local/lib

# The primary target
all: libs cli tests docs

# Executable targets
CLI           = ./botan
TEST          = ./botan-test
LIBRARIES     = ./libbotan-2.a

cli: $(CLI)
tests: $(TEST)
libs: $(LIBRARIES)
docs: build/doc.stamp

# Misc targets

.PHONY: all cli libs tests check docs clean distclean install

build/doc.stamp: doc/*.rst doc/api_ref/*.rst doc/dev_ref/*.rst
	"$(PYTHON_EXE)" "$(SCRIPTS_DIR)/build_docs.py" --build-dir="build"

clean:
	"$(PYTHON_EXE)" "$(SCRIPTS_DIR)/cleanup.py" --build-dir="build"

distclean:
	"$(PYTHON_EXE)" "$(SCRIPTS_DIR)/cleanup.py" --build-dir="build" --distclean

install: libs cli docs
	"$(PYTHON_EXE)" "$(SCRIPTS_DIR)/install.py" --prefix="/usr/local" --build-dir="build" --bindir="/usr/local/bin" --libdir="/usr/local/lib" --docdir="share/doc" --includedir="include"

check: tests
	"$(PYTHON_EXE)" "$(SCRIPTS_DIR)/check.py" --build-dir="build"

# Object Files
LIBOBJS = build/obj/lib/botan_all.o

CLIOBJS = build/obj/cli/argon2.o build/obj/cli/asn1.o build/obj/cli/bcrypt.o build/obj/cli/cc_enc.o build/obj/cli/cli.o build/obj/cli/cli_rng.o build/obj/cli/codec.o build/obj/cli/compress.o build/obj/cli/encryption.o build/obj/cli/entropy.o build/obj/cli/hash.o build/obj/cli/hmac.o build/obj/cli/main.o build/obj/cli/math.o build/obj/cli/pbkdf.o build/obj/cli/pk_crypt.o build/obj/cli/psk.o build/obj/cli/pubkey.o build/obj/cli/roughtime.o build/obj/cli/sandbox.o build/obj/cli/speed.o build/obj/cli/timing_tests.o build/obj/cli/tls_client.o build/obj/cli/tls_http_server.o build/obj/cli/tls_proxy.o build/obj/cli/tls_server.o build/obj/cli/tls_utils.o build/obj/cli/tss.o build/obj/cli/utils.o build/obj/cli/x509.o build/obj/cli/zfec.o

TESTOBJS = build/obj/test/main.o build/obj/test/test_aead.o build/obj/test/test_asn1.o build/obj/test/test_bigint.o build/obj/test/test_block.o build/obj/test/test_blowfish.o build/obj/test/test_c25519.o build/obj/test/test_certstor.o build/obj/test/test_certstor_flatfile.o build/obj/test/test_certstor_system.o build/obj/test/test_certstor_utils.o build/obj/test/test_clang_bug.o build/obj/test/test_compression.o build/obj/test/test_cryptobox.o build/obj/test/test_datastore.o build/obj/test/test_dh.o build/obj/test/test_dl_group.o build/obj/test/test_dlies.o build/obj/test/test_dsa.o build/obj/test/test_ecc_pointmul.o build/obj/test/test_ecdh.o build/obj/test/test_ecdsa.o build/obj/test/test_ecgdsa.o build/obj/test/test_ecies.o build/obj/test/test_eckcdsa.o build/obj/test/test_ed25519.o build/obj/test/test_elgamal.o build/obj/test/test_entropy.o build/obj/test/test_ffi.o build/obj/test/test_filters.o build/obj/test/test_fpe.o build/obj/test/test_gf2m.o build/obj/test/test_gost_3410.o build/obj/test/test_hash.o build/obj/test/test_hash_id.o build/obj/test/test_kdf.o build/obj/test/test_keywrap.o build/obj/test/test_mac.o build/obj/test/test_mceliece.o build/obj/test/test_modes.o build/obj/test/test_mp.o build/obj/test/test_name_constraint.o build/obj/test/test_newhope.o build/obj/test/test_ocb.o build/obj/test/test_ocsp.o build/obj/test/test_octetstring.o build/obj/test/test_oid.o build/obj/test/test_os_utils.o build/obj/test/test_otp.o build/obj/test/test_package_transform.o build/obj/test/test_pad.o build/obj/test/test_passhash.o build/obj/test/test_pbkdf.o build/obj/test/test_pem.o build/obj/test/test_pk_pad.o build/obj/test/test_pkcs11_high_level.o build/obj/test/test_pkcs11_low_level.o build/obj/test/test_psk_db.o build/obj/test/test_pubkey.o build/obj/test/test_rfc6979.o build/obj/test/test_rng.o build/obj/test/test_rng_kat.o build/obj/test/test_roughtime.o build/obj/test/test_rsa.o build/obj/test/test_runner.o build/obj/test/test_simd.o build/obj/test/test_siv.o build/obj/test/test_sm2.o build/obj/test/test_sodium.o build/obj/test/test_srp6.o build/obj/test/test_stream.o build/obj/test/test_tests.o build/obj/test/test_thread_utils.o build/obj/test/test_tls.o build/obj/test/test_tls_messages.o build/obj/test/test_tls_stream_integration.o build/obj/test/test_tpm.o build/obj/test/test_tss.o build/obj/test/test_uri.o build/obj/test/test_utils.o build/obj/test/test_workfactor.o build/obj/test/test_x509_dn.o build/obj/test/test_x509_path.o build/obj/test/test_xmss.o build/obj/test/test_zfec.o build/obj/test/tests.o build/obj/test/unit_asio_stream.o build/obj/test/unit_ecc.o build/obj/test/unit_ecdh.o build/obj/test/unit_ecdsa.o build/obj/test/unit_tls.o build/obj/test/unit_tls_policy.o build/obj/test/unit_x509.o

# Executable targets

$(CLI): $(LIBRARIES) $(CLIOBJS)
	$(EXE_LINK_CMD) $(ABI_FLAGS) $(CLIOBJS) $(BUILD_DIR_LINK_PATH) $(LDFLAGS) $(EXE_LINKS_TO) -o $@

$(TEST): $(LIBRARIES) $(TESTOBJS)
	$(EXE_LINK_CMD) $(ABI_FLAGS) $(TESTOBJS) $(BUILD_DIR_LINK_PATH) $(LDFLAGS) $(EXE_LINKS_TO) -o $@

```

**Comment by raumod** [comment]
This issue will be better handled within the fork I created for the repository, it simply adds an "_" (underscore) to the name.

Most likely this issue presented because we are using other libraries that use a macro with the same name as "BLOCK_SIZE". 

Thanks for your help

**Comment by hrantzsch** [comment]
I see. I verified that the config you posted builds without errors (both with and without `block`). You're probably right about the macro issue, given the error you're facing.

FWIW, there's a [Conan package for Botan](https://conan.io/center/botan). If at all possible, maybe consider migrating to Conan, especially if your cmake setup is complicated.

**Comment by j05070415** [comment]
谢谢，您的邮件我已收到！

**Pull request closed without merging**
