### PR TITLE
Move socket implementation into module http_util

### PR DESCRIPTION
**Pull request by webmaster128**
This removes the requirement of linking socket libraries for applications that do not use http_util.

See also  #1138

### CODE REVIEW

**Comment by randombit** [comment]
Yeah makes sense. Can you look at the Windows build?

**Comment by webmaster128** [comment]
Thanks for the quick feedback. Build looks promising now. So I guess this is ready for final review

**Comment by webmaster128** [comment]
Damn, there is an `#include <string.h>` missing for `strerror` and `errno` in the BSD_Socket implementation.

**Comment by randombit** [comment]
Fixed

**Pull request merged**
