### PR TITLE
Add support to output bakefiles

### PR DESCRIPTION
**Pull request by neusdan**
[Bakefile](http://bakefile.org/) is a tool which can be used to create Visual Studio or Xcode project files
for example. 

Currently only support for VS 2013 project files supported because the lastest release of Bakefile is not aware of VS 2015. Support for VS 2015 is in Bakefile already implemented but a new version is not yet released.

I think support for Xcode could easily be added, but i have no Apple system to test.

For me this is a huge help to modify and debug Botan.

Please apologize my Python skills. I'm not very familar with Python...

GH #207

### CODE REVIEW

**Comment by neusdan** [comment]
Usage is as easy as `bkl botan.bkl`.

This generates a Visual Studio solution which consists of 3 VS projects: the Botan DLL, the cli tool and the tests.

I've tested x86 and x64 in debug and release configuration. Everything compiles and all tests ran fine.

**Comment by randombit** [comment]
This is not totally unreasonable but I'd prefer extending the templating language sufficiently that it is possible to write a src/build-data/makefile/bakefile.in which can then be produced from the build by --makefile-style=bakefile.

This would have the pleasant side effect of removing the need for make-specific syntax being hardcoded into configure.py (eg in the build_commands function), and likely make it possible to easily support generating for everyone's various favorite pet build tool just by adding the appropriate template file.

The main missing part is a basic iteration/for-loop syntax over the object files. Unfortunately in some effort to avoid picking favorites (I assume) the Python std lib doesn't include any reasonable string template library, and forcing someone to pip install Jinja or whatever before building is a non-starter (especially since I at least build all the time on systems I don't have root on and for which base Python is available but no additional packages are installed), and so far I haven't bothered writing iteration into configures template processor.

So I guess in summary feel free to leave this PR open but I am thinking I don't want to accept this as-is, I would accept adding a bakefile.in (or a cmake.in or scons.in or vsproj.in or whatever weird thing people are into) at the point where it can be supported with no/minimal changes to the configure source. I haven't bothered with iteration so far because my personal favorite pet build tool is plain Make and that works right now ;) but clearly there is some demand for support for other build tools so I'll look into adding a basic foreach %obj syntax in the fairly near future (eg within the next release or two).

**Comment by webmaster128** [comment]
Having a more flexible Makefile generator sounds like a great idea. I was able to put together the four cmake files from the cmake branch into one file, which is working for me: [CMakeLists.txt](https://gist.github.com/webmaster128/611869f37951582a76f5).

It is a list of .cpp files, split into the groups: lib, cli, tests. The only thing that might be a bit tricky is AVX2, SSSE3 and AES-NI starting in line 339.

If the configure script could generate that, it would be cool.

@neusdan could you share a generated version of `botan.bkl`?

**Comment by neusdan** [comment]
I'm also really looking forward to a flexible Makefile generator :-)

Here is a generated bakefile:
[Botan.bkl](https://gist.github.com/neusdan/08c158b505a26cfd2d90)

**Comment by randombit** [comment]
@neusdan I have not been able to find a single-file Python string template library with a compatible license. So lacking a template library or the time to write one in the immediate future, your patch is good enough and probably useful to others. There seem to be conflicts, can you rebase?

**Comment by neusdan** [comment]
Updated the PR. Great that you going to merge this!

**Comment by randombit** [comment]
Merged, enjoy

**Pull request merged**
