### PR TITLE
Add support for Intel SHA instructions

### PR DESCRIPTION
**Pull request by randombit**
#824 Need to install SDE to test this. But it compiles at least. :)

Based on GH #807 and #808

### CODE REVIEW

**Comment by noloader** [comment]
I'm working on the Goldmont machine. I configured with `--cc-abi='-march=native". The `goldmont-sha` branch is catching a warning during a compile:

```
g++  -m64 -pthread -fstack-protector -march=native -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -momit-leaf-frame-pointer -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -c ./src/lib/hash/sha2_64/sha2_64.cpp -o build/obj/lib/hash_sha2_64.o
./src/lib/hash/sha2_32/sha2_32_x86/sha2_32_x86.cpp: In function âvoid Botan::sha2_compress_x86(uint32_t*, const uint8_t*, std::size_t)â:
./src/lib/hash/sha2_32/sha2_32_x86/sha2_32_x86.cpp:15:6: warning: no previous declaration for âvoid Botan::sha2_compress_x86(uint32_t*, const uint8_t*, std::size_t)â [-Wmissing-declarations]
 void sha2_compress_x86(uint32_t digest[], const uint8_t input[], size_t blocks)
      ^~~~~~~~~~~~~~~~~
```

However, it looks like the SHA extensions were used:

```
$ ./botan speed --msec=3000 SHA-1 SHA-256
SHA-160 [base] hash 1219.836 MiB/sec (3659.508 MiB in 3000.001 ms)
SHA-256 [base] hash 535.413 MiB/sec (1606.242 MiB in 3000.004 ms)
```

**Comment by randombit** [comment]
@noloader Can you run `./botan-test hash`?

**Comment by noloader** [comment]
@randombit,

> Can you run ./botan-test hash?

Yes sir.

```
$ ./botan-test hash
Testing Botan 2.0.0 (unreleased, revision git:573fdfd2fc8e40a08fd7e4ad5970270ec02a9d03, distribution unspecified)
Starting tests rng:HMAC_DRBG with seed '14978FF9024ACD31'
Adler32 ran 215 tests in 0.48 msec all ok
Blake2b(224) ran 2046 tests in 8.31 msec all ok
Blake2b(256) ran 2046 tests in 5.96 msec all ok
Blake2b(384) ran 2046 tests in 5.53 msec all ok
Blake2b(512) ran 2150 tests in 5.77 msec all ok
CRC24 ran 229 tests in 0.29 msec all ok
CRC32 ran 215 tests in 0.28 msec all ok
Comb4P(MD4,MD5) ran 8 tests in 0.07 msec all ok
Comb4P(SHA-160,RIPEMD-160) ran 8 tests in 0.06 msec all ok
GOST-R-34.11-94 ran 79 tests in 0.81 msec all ok
Keccak-1600(224) ran 2142 tests in 7.56 msec all ok
Keccak-1600(256) ran 2142 tests in 7.55 msec all ok
Keccak-1600(384) ran 2142 tests in 8.47 msec all ok
Keccak-1600(512) ran 2142 tests in 9.74 msec all ok
MD4 ran 596 tests in 0.84 msec all ok
MD5 ran 604 tests in 0.85 msec all ok
Parallel(MD5,SHA-160) ran 12 tests in 0.09 msec all ok
Parallel(SHA-256,SHA-512) ran 6 tests in 0.04 msec all ok
RIPEMD-160 ran 605 tests in 1.00 msec all ok
SHA-160 ran 1818 tests in 2.40 msec all ok
SHA-224 ran 28 tests in 0.06 msec all ok
SHA-256 ran 4188 tests in 6.17 msec all ok
SHA-3(224) ran 806 tests in 2.84 msec all ok
SHA-3(256) ran 806 tests in 2.73 msec all ok
SHA-3(384) ran 806 tests in 2.78 msec all ok
SHA-3(512) ran 806 tests in 4.89 msec all ok
SHA-384 ran 54 tests in 0.14 msec all ok
SHA-512 ran 54 tests in 0.12 msec all ok
SHA-512-256 ran 7 tests in 0.02 msec all ok
SHAKE-128(1120) ran 8 tests in 0.03 msec all ok
SHAKE-128(128) ran 24 tests in 0.21 msec all ok
SHAKE-256(2000) ran 8 tests in 0.04 msec all ok
SHAKE-256(256) ran 23 tests in 0.13 msec all ok
Skein-512(224) ran 2046 tests in 7.50 msec all ok
Skein-512(256) ran 2046 tests in 7.43 msec all ok
Skein-512(384) ran 2046 tests in 7.46 msec all ok
Skein-512(512) ran 2142 tests in 8.35 msec all ok
Tiger(16,3) ran 15 tests in 0.08 msec all ok
Tiger(16,4) ran 8 tests in 0.02 msec all ok
Tiger(20,3) ran 15 tests in 0.04 msec all ok
Tiger(20,4) ran 8 tests in 0.02 msec all ok
Tiger(24,3) ran 71 tests in 0.19 msec all ok
Tiger(24,4) ran 8 tests in 0.02 msec all ok
Whirlpool ran 62 tests in 0.18 msec all ok
Tests complete ran 37336 tests in 153.36 msec all tests ok
```

**Comment by randombit** [comment]
Oh we will need to handle older compiler versions. Looks like GCC only supports the SHA intrinsics from 5.0 on. Clang 3.5 seems OK on Travis. This will require a bit of build hackery but I had some things in that area in mind for 2.1 anyway. Until resolved this PR will have to hang out.

We do need to eventually work out a system for testing code our CI CPUs do not support. Currently RDSEED is not tested, for a long time the AVX2 code also was skipped, and SHA will not be tested until Canonlake-E in who knows when.

**Comment by randombit** [comment]
From the results

```
SHA-160 ran 1818 tests in 2.40 msec all ok
SHA-224 ran 28 tests in 0.06 msec all ok
SHA-256 ran 4188 tests in 6.17 msec all ok
```

vs on my machine (with just the SSE2 bit)

```
SHA-160 ran 1212 tests in 1.22 msec all ok
SHA-224 ran 14 tests in 0.06 msec all ok
SHA-256 ran 2094 tests in 2.27 msec all ok
```

So the cpuid logic seems to be working, and the tests ran over all 3 implementations on that CPU (plain C++, SSE2, and using the new instructions).

**Comment by noloader** [comment]
@randombit,

Here's a small patch that cleans up that intermediate `state` variable that was used. After removal, the routines uses Botan's `digest` directly. It tested OK on the Goldmont machine.

```
$ git diff > sha.diff
$ cat sha.diff
diff --git a/src/lib/hash/sha1/sha1_x86/sha1_x86.cpp b/src/lib/hash/sha1/sha1_x86/sha1_x86.cpp
index 9012d24..b5e4b70 100644
--- a/src/lib/hash/sha1/sha1_x86/sha1_x86.cpp
+++ b/src/lib/hash/sha1/sha1_x86/sha1_x86.cpp
@@ -26,11 +26,9 @@ void SHA_160::sha1_compress_x86(secure_vector<uint32_t>& digest,

    __m128i ABCD_SAVE, E0_SAVE, E1; // only used inside loop?

-   uint32_t* state = &digest[0];
-
    // Load initial values
-   ABCD = _mm_loadu_si128((__m128i*) state);
-   E0 = _mm_set_epi32(state[4], 0, 0, 0);
+   ABCD = _mm_loadu_si128((__m128i*) &digest[0]);
+   E0 = _mm_set_epi32(digest[4], 0, 0, 0);
    ABCD = _mm_shuffle_epi32(ABCD, 0x1B);
    __m128i MASK = _mm_set_epi64x(0x0001020304050607ULL, 0x08090a0b0c0d0e0fULL);

@@ -210,8 +208,8 @@ void SHA_160::sha1_compress_x86(secure_vector<uint32_t>& digest,

    // Save state
    ABCD = _mm_shuffle_epi32(ABCD, 0x1B);
-   _mm_storeu_si128((__m128i*) state, ABCD);
-   state[4] = _mm_extract_epi32(E0, 3);
+   _mm_storeu_si128((__m128i*) &digest[0], ABCD);
+   digest[4] = _mm_extract_epi32(E0, 3);
    }

 }
diff --git a/src/lib/hash/sha2_32/sha2_32_x86/sha2_32_x86.cpp b/src/lib/hash/sha2_32/sha2_32_x86/sha2_32_x86.cpp
index adc0db1..4de8d94 100644
--- a/src/lib/hash/sha2_32/sha2_32_x86/sha2_32_x86.cpp
+++ b/src/lib/hash/sha2_32/sha2_32_x86/sha2_32_x86.cpp
@@ -19,11 +19,9 @@ void sha2_compress_x86(uint32_t digest[], const uint8_t input[], size_t blocks)
    __m128i TMSG0, TMSG1, TMSG2, TMSG3;
    __m128i ABEF_SAVE, CDGH_SAVE;

-   uint32_t* state = &digest[0];
-
    // Load initial values
-   TMP = _mm_loadu_si128((__m128i*) &state[0]);
-   STATE1 = _mm_loadu_si128((__m128i*) &state[4]);
+   TMP = _mm_loadu_si128((__m128i*) &digest[0]);
+   STATE1 = _mm_loadu_si128((__m128i*) &digest[4]);
    MASK = _mm_set_epi64x(0x0c0d0e0f08090a0bULL, 0x0405060700010203ULL);

    TMP = _mm_shuffle_epi32(TMP, 0xB1); // CDAB
@@ -203,8 +201,8 @@ void sha2_compress_x86(uint32_t digest[], const uint8_t input[], size_t blocks)
    STATE1 = _mm_alignr_epi8(STATE1, TMP, 8); // ABEF

    // Save state
-   _mm_storeu_si128((__m128i*) &state[0], STATE0);
-   _mm_storeu_si128((__m128i*) &state[4], STATE1);
+   _mm_storeu_si128((__m128i*) &digest[0], STATE0);
+   _mm_storeu_si128((__m128i*) &digest[4], STATE1);
    }

 }
```

**Comment by noloader** [comment]
@randombit,

> Clang 3.5 seems OK on Travis....

Your mention of Clang knocked off the cobwebs on LLVM Issue 20670  [_mm_loadu_si128 parameter has wrong type](https://llvm.org/bugs/show_bug.cgi?id=20670). You might want to make the intermediate cast to `void*` to avoid a [incorrect] warning since the loads and stores are unaligned. That is, change this:

```
/usr/bin/clang++-3.5  -m64 -pthread -march=native -msse4 -msha -fPIC -fvisibility=hidden -std=c++11
-D_REENTRANT -fstack-protector -O3 -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5
-Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wunreachable-code -Ibuild/include
-c ./src/lib/hash/sha2_64/sha2_64.cpp -o build/obj/lib/hash_sha2_64.o
./src/lib/hash/sha2_32/sha2_32_x86/sha2_32_x86.cpp:23:26: warning: cast from
      'uint32_t *' (aka 'unsigned int *') to '__m128i *' increases required
      alignment from 4 to 16 [-Wcast-align]
   TMP = _mm_loadu_si128((__m128i*) &digest[0]);
                         ^~~~~~~~~~~~~~~~~~~~~

```

To:

```
TMP = _mm_loadu_si128((__m128i*)(void*) &digest[0]);
```

I probably should have included it in the original report.

Would you like it changed and tested?

**Comment by noloader** [comment]
The `goldmont-sha` branch tested OK on the Celeron J3455, which is Goldmont. It appears the SHA extensions were engaged as expected:

```
$ ./botan cpuid
CPUID flags: sse2 ssse3 sse41 sse42 rdtsc clmul aes_ni rdrand rdseed intel_sha

$ ./botan speed --msec=3000 SHA-1 SHA-224 SHA-256 SHA-384 SHA-512
SHA-160 [base] hash 1219.729 MiB/sec (3659.188 MiB in 3000.001 ms)
SHA-224 [base] hash 535.439 MiB/sec (1606.320 MiB in 3000.007 ms)
SHA-256 [base] hash 535.400 MiB/sec (1606.199 MiB in 3000.000 ms)
SHA-384 [base] hash 144.761 MiB/sec (434.285 MiB in 3000.013 ms)
SHA-512 [base] hash 144.762 MiB/sec (434.289 MiB in 3000.021 ms)
```

-----

> randombit> #824 Need to install SDE to test this. But it compiles at least. :)

I should be able to provide remote SSH access if anyone is interested.

**Comment by randombit** [comment]
With #1052 merged I think this is ready to go also

**Pull request merged**
