### PR TITLE
Get rid of "extra ';'" warnings and force semicolon after macros

### PR DESCRIPTION
**Pull request by webmaster128**

### CODE REVIEW

**Comment by randombit** [comment]
What compiler emits a warning for the extra ; and under what compiler? I don't remember ever having seen this warning under any compiler

There is an existing BOTAN_FORCE_SEMICOLON in algo_registry.h for I believe a similar warning. If handling this warning is needed, can you move that define to build.h, where it can be used by both files and any future required cases.

**Comment by webmaster128** [comment]
It is a Qt Creator diagnostics message. I don't know what the underlying engine is.

I didn't use BOTAN_FORCE_SEMICOLON here to avoid unnecessary dependencies but moving it to build.h is even better.

**Comment by neusdan** [comment]
GCC emits this warning if `-Wpedantic` is specified

**Comment by webmaster128** [comment]
@randombit Pushed the changes as suggested.

**Pull request merged**
