### PR TITLE
Update Appveyor matrix

### PR DESCRIPTION
**Pull request by webmaster128**
Closes #666

### CODE REVIEW

**Comment by webmaster128** [comment]
Let's see if this works out

**Comment by neusdan** [comment]
Can we add one build with BSI policy enabled? If this fits into the 2 hour time frame...

And i wanted to add the PKCS#11 tests to the CI builds when I find time for this. This will require compiling SoftHSM and some additional time for the test execution. 

Otherwise LGTM, thanks !

**Comment by randombit** [comment]
For the Linux SoftHSM builds, it seems softhsm2 is only in 16.04 so I was planning on having the CI just `wget` a prebuilt softhsm library from somewhere, instead of rebuilding it on each checkin. I'm not sure how what the easiest thing is for Windows is.

**Comment by randombit** [comment]
@neusdan It may be easier to fit the BSI policy into the Travis builds. Already for some where running the tests is very slow (qemu/valgrind) CI is set to build with a minimized policy, but currently always uses `modern`. I will change some of these to use BSI policy instead, I think right now we do not check within CI that BSI policy actually builds/tests at all.

**Comment by neusdan** [comment]
it would be nice to have BSI policy builds on all OSes but Travis is a good start. thanks!

**Comment by randombit** [comment]
1h43m for 588ab9e, lgtm

**Pull request merged**
