### PR TITLE
Support custom curves in TLS

### PR DESCRIPTION
**Pull request by randombit**
Same idea as #1415 but different approach. Adds a new TLS callback `std::string tls_decode_group_param(Group_Params group_param)` which, for applications that require custom curves, they must implement in order to match against their custom curve IDs. This also works for DH groups, as long as the custom assignment is within the DH range (256-511, FFDHE leaves 508-511 for private assignment).

This is a little contorted in that an application that wants to use a custom curve must both specially set their Policy (to return the curve ID) and implement this additional Callback to handle decoding the curve ID to a string. But this really seems like a niche case, and it avoids having a special global (+ global lock) just to maintain this mapping.

I'm not actually 100% sure this is the right approach either, and am contemplating trying to include the TLS ids within the EC_Group/DL_Group data directly. In which case the extra callback would go away, and the TLS id would just be specified when the ECC group is created. However this requires a big refactoring of DL_Group (ala #1435/#1441) so may take a while.

Anyway posting now for @neverhub and @securitykernel to look at.

### CODE REVIEW

**Comment by randombit** [comment]
I wrote up an implementation of shared_ptr DL_Groups and then realized it's probably a bad idea since the set of modp groups is basically unbounded, and keeping around a reference to every DL_Group an application ever processes is a recipe for trouble. We might be able to work around this by using `weak_ptr` in the registry but things get increasingly complicated for a seemingly small gain.

I'm still not completely happy with this PR but it's good enough I think, as long as @neverhub thinks it meets the same goals as #1415

**Comment by randombit** [comment]
Rebased

**Comment by securitykernel** [comment]
I contacted @neverhub last week, but it seems he's not available. First of all, thanks for implementing this! To me it seems like it handles the use case just fine. And I like the TLS callback and policy more than encapsulating the curve ID in the DL/EC group. Modulo docs (aka handbook) I think we're set with what we wanted to achieve with #1415.

**Comment by neverhub** [comment]
Sorry for the late reply. I was quite busy recently :/. I did a bunch of testing today and yesterday and i am very satisfied with the callback approach. Thank you Jack :+1:  .

This achieves all set goals of #1415. I still have a few tests with more exotic curves at hand. I will add them, if you think they are helpful.

I think i can close #1415 now.

**Comment by randombit** [comment]
@securitykernel This still needs docs but I'm going to merge now to minimize risk of conflicts, I've left a note in the 2.5 release ticket (#1396) that docs are still needed.

**Comment by securitykernel** [comment]
@randombit Thanks! We‘ll take care of it.

**Pull request merged**
