### PR TITLE
Fixed crash in compression filter when transform argument is null.

### PR DESCRIPTION
**Pull request by matejk**
Null pointer can be dereferenced in Compression_Decompression_Filter if the transform argument is null.

### CODE REVIEW

**Comment by webmaster128** [comment]
The input `transform` must not be null at all, right? Can we check that at the very beginning of the function?

That would make the scenario much simpler since we know that `tansform` is not-null for the rest of the function.

**Comment by matejk** [comment]
We detected this crash with the following code:

```
pipe.append(new Compression_Filter("unknown-compression", 6, 4*1024));
```

Compression_Filter ctor calls make_compressor that returns null and that is passed to Compression_Decompression_Filter ctor.

Concatenation of message for the exception than crashed the process.

**Comment by webmaster128** [comment]
Sure, calling "->name()" on null is a crash.

I was just asking if we can move the null-check of `transform` up to the very top of `Compression_Decompression_Filter()` to avoid setting `m_transform` to something we know that is invalid.

**Comment by matejk** [comment]
Yes, of course.

**Comment by webmaster128** [comment]
Sorry, I was waiting for a reply and did not see that you edited the comment.

Please change it how discussed such that it is beautiful before I merge.

**Comment by randombit** [comment]
lgtm

**Comment by webmaster128** [comment]
Shouldn't we Use Botan::Invalid_Argument here, @randombit?

**Comment by randombit** [comment]
@webmaster128 In 1.11, Botan::Invalid_Argument is actually a typedef of std::invalid_argument

**Comment by webmaster128** [comment]
I saw that. But what is the idea behind it? Moving from Invalid_Argument to the STL version or keep a Botan specific exception that might one day be a subclass of std::invalid_argument?
Which way is right for future code? Which exception handler would you recommand to a user?

**Comment by matejk** [comment]
@randombit Shall the exception be changed to Botan::Invalid_Argument?

**Comment by webmaster128** [comment]
@matejk Please move the null pointer check for `transform` to the very top of the function body. This case should be checked as early as possible, because then we know if the dynamic_cast worked or not. And ping me because we do not get notified about PR branch changes.

Then I can get this done with any of the exception names used. This is inconsistent anyway and does not matter at the moment.

**Comment by matejk** [comment]
@webmaster128: I reorganised the code as you suggested.

**Pull request merged**
