### PR TITLE
Don't crash if openssl can't allocate a new context and catch ffi exception

### PR DESCRIPTION
**Pull request by catap**
This is a contribution from [Ribose Inc](https://www.ribose.com/) (@riboseinc).

### CODE REVIEW

**Comment by catap** [comment]
I think that this pull request is overwrite https://github.com/randombit/botan/pull/1095

**Comment by randombit** [comment]
I don't understand the reasoning behind the `catch(...) { throw; }` blocks can you explain?

**Comment by catap** [comment]
@randombit when `retrace` return NULL for `malloc` calls and it calls was from `new` operator for example, it throw `std::base_alloc`.

If try has only `catch(std::exception& e)` this exception hasn't catched and the full application stoped.

**Comment by catap** [comment]
I found an example of this crash:
```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff990c6d42 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff991b4457 libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff9902c420 libsystem_c.dylib`abort + 129
    frame #3: 0x00007fff97b8284a libc++abi.dylib`abort_message + 266
    frame #4: 0x00007fff97ba7c37 libc++abi.dylib`default_terminate_handler() + 243
    frame #5: 0x00007fff986b5713 libobjc.A.dylib`_objc_terminate() + 124
    frame #6: 0x00007fff97ba4d69 libc++abi.dylib`std::__terminate(void (*)()) + 8
    frame #7: 0x00007fff97ba47de libc++abi.dylib`__cxa_throw + 121
    frame #8: 0x00007fff97ba4e67 libc++abi.dylib`operator new(unsigned long) + 87
    frame #9: 0x000000010015fbf0 libbotan-2.0.dylib`botan_mp_init + 20
    frame #10: 0x00000001000ab8a0 librnp.0.dylib`PGPV_BN_new at bn.c:81
    frame #11: 0x00000001000dddc9 librnp.0.dylib`pgp_genkey_rsa(seckey=0x0000000101202e18, numbits=1024) at rsa.c:305
    frame #12: 0x00000001000b2bd7 librnp.0.dylib`pgp_generate_keypair(key_desc=0x00007fff5fbff0c4, userid="rnpkeys_generatekey_verifyUserIdOption_MD5") at crypto.c:255
    frame #13: 0x00000001000d9196 librnp.0.dylib`rnp_generate_key(rnp=0x00007fff5fbff060, id="rnpkeys_generatekey_verifyUserIdOption_MD5") at rnp.c:1349
    frame #14: 0x0000000100004f23 rnp_tests`rnpkeys_generatekey_verifyUserIdOption(state=0x00007fff5fbff598) at rnp_tests_generatekey.c:366
    frame #15: 0x0000000100007e64 rnp_tests`main at rnp_tests.c:129
    frame #16: 0x00007fff98f98235 libdyld.dylib`start + 1
(lldb) 
```

**Comment by catap** [comment]
ping?

**Comment by webmaster128** [comment]
But when you catch std::base_alloc with `catch(...)` and throw it again with `throw`, the application will still crash because of "uncaught exception of type std::bad_alloc", right?

**Comment by catap** [comment]
@webmaster128, @randombit I got your point. Yes, you're right.

updating it ASAP

**Comment by catap** [comment]
Ok, just removing this crazy commit. Sorry :(

**Comment by randombit** [comment]
Closing in favor of #1128

**Pull request closed without merging**
