### PR TITLE
add BOTAN_NORETURN macro and mark those functions that do not return with it

### PR DESCRIPTION
**Pull request by neusdan**
#402

### CODE REVIEW

**Comment by randombit** [comment]
The build.h modification looks fine as does the assert.

I do not think noreturn is appropriate on any of the `encode_into` calls; they are throwing simply due to encoding of those values not being implemented, but I don't want to commit to them not ever being implemented in the future with a noreturn API contract.

Similarly it does not seem right on Credentials_Manager::psk, since while the default throws, a subclass might well return if a PSK is defined. I have no idea what a compiler does with a virtual noreturn, but I would guess it either ignores the noreturn or happily generates code assuming no subclass will ever return either. I find it kind of weird GCC would suggest this one.

For `http_transact_fail` it makes sense, but I wonder why on earth this is exposed to callers? It is just an internal implementation detail I'm pretty sure. (I did this, I just can't remember what I was thinking at the time.) Probably it should be pulled out of the header entirely and be an anon namespace function in the source file, as there is no reason for any application to ever call it. I'll handle this.

Please trim the PR to just buildh.in and assert.h for now.

**Comment by neusdan** [comment]
Good points. What about the warning flag?

**Comment by neusdan** [comment]
somethings wrong with the amalgamation build

**Comment by neusdan** [comment]
ok, that was dumb ;-) it goes before the function declaration

**Pull request merged**
